// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tools/config-gen. DO NOT EDIT.
// GENERATED CODE - DO NOT EDIT MANUALLY.

package cfg

import (
	"encoding/base64"
	"fmt"

	"github.com/googlecloudplatform/gcsfuse/v3/cfg/pb"
	"google.golang.org/protobuf/proto"
)

// ToProto maps a cfg.Config into its flat Protobuf pb.Config representation.
// High-risk text fields (strings, paths) are booleanized to prevent PII leakage.
func ToProto(config *Config) *pb.Config {
	if config == nil {
		return nil
	}

	return &pb.Config{
		IsAppNameSet:                                          config.AppName != "",
		IsCacheDirSet:                                         string(config.CacheDir) != "",
		CloudProfilerAllocatedHeap:                            config.CloudProfiler.AllocatedHeap,
		CloudProfilerCpu:                                      config.CloudProfiler.Cpu,
		CloudProfilerEnabled:                                  config.CloudProfiler.Enabled,
		CloudProfilerGoroutines:                               config.CloudProfiler.Goroutines,
		CloudProfilerHeap:                                     config.CloudProfiler.Heap,
		IsCloudProfilerLabelSet:                               config.CloudProfiler.Label != "",
		CloudProfilerMutex:                                    config.CloudProfiler.Mutex,
		IsCloudProfilerServiceNameSet:                         config.CloudProfiler.ServiceName != "",
		DebugExitOnInvariantViolation:                         config.Debug.ExitOnInvariantViolation,
		DebugFuse:                                             config.Debug.Fuse,
		DebugGcs:                                              config.Debug.Gcs,
		DebugLogMutex:                                         config.Debug.LogMutex,
		DisableAutoconfig:                                     config.DisableAutoconfig,
		DummyIoEnable:                                         config.DummyIo.Enable,
		DummyIoPerMbLatency:                                   int64(config.DummyIo.PerMbLatency),
		DummyIoReaderLatency:                                  int64(config.DummyIo.ReaderLatency),
		EnableAtomicRenameObject:                              config.EnableAtomicRenameObject,
		EnableGoogleLibAuth:                                   config.EnableGoogleLibAuth,
		EnableHns:                                             config.EnableHns,
		EnableNewReader:                                       config.EnableNewReader,
		EnableStandardSymlinks:                                config.EnableStandardSymlinks,
		EnableTypeCacheDeprecation:                            config.EnableTypeCacheDeprecation,
		EnableUnsupportedPathSupport:                          config.EnableUnsupportedPathSupport,
		FileCacheCacheFileForRangeRead:                        config.FileCache.CacheFileForRangeRead,
		FileCacheDownloadChunkSizeMb:                          config.FileCache.DownloadChunkSizeMb,
		FileCacheEnableCrc:                                    config.FileCache.EnableCrc,
		FileCacheEnableExperimentalSharedChunkCache:           config.FileCache.EnableExperimentalSharedChunkCache,
		FileCacheEnableODirect:                                config.FileCache.EnableODirect,
		FileCacheEnableParallelDownloads:                      config.FileCache.EnableParallelDownloads,
		IsFileCacheExcludeRegexSet:                            config.FileCache.ExcludeRegex != "",
		FileCacheExperimentalDisableSizeCalculationFix:        config.FileCache.ExperimentalDisableSizeCalculationFix,
		FileCacheExperimentalEnableChunkCache:                 config.FileCache.ExperimentalEnableChunkCache,
		FileCacheExperimentalParallelDownloadsDefaultOn:       config.FileCache.ExperimentalParallelDownloadsDefaultOn,
		IsFileCacheIncludeRegexSet:                            config.FileCache.IncludeRegex != "",
		FileCacheMaxParallelDownloads:                         config.FileCache.MaxParallelDownloads,
		FileCacheMaxSizeMb:                                    config.FileCache.MaxSizeMb,
		FileCacheParallelDownloadsPerFile:                     config.FileCache.ParallelDownloadsPerFile,
		FileCacheSharedCacheChunkSizeMb:                       config.FileCache.SharedCacheChunkSizeMb,
		FileCacheWriteBufferSize:                              config.FileCache.WriteBufferSize,
		FileSystemCongestionThreshold:                         config.FileSystem.CongestionThreshold,
		FileSystemDirMode:                                     int32(config.FileSystem.DirMode),
		FileSystemDisableParallelDirops:                       config.FileSystem.DisableParallelDirops,
		FileSystemEnableKernelReader:                          config.FileSystem.EnableKernelReader,
		FileSystemExperimentalEnableDentryCache:               config.FileSystem.ExperimentalEnableDentryCache,
		FileSystemExperimentalEnablePirlo:                     config.FileSystem.ExperimentalEnablePirlo,
		FileSystemExperimentalEnableReaddirplus:               config.FileSystem.ExperimentalEnableReaddirplus,
		FileSystemExperimentalODirect:                         config.FileSystem.ExperimentalODirect,
		FileSystemFileMode:                                    int32(config.FileSystem.FileMode),
		FileSystemFuseMaxRequestSizeKb:                        config.FileSystem.FuseMaxRequestSizeKb,
		FileSystemFuseMaxWriteSizeKb:                          config.FileSystem.FuseMaxWriteSizeKb,
		IsFileSystemFuseOptionsSet:                            len(config.FileSystem.FuseOptions) > 0,
		FileSystemGid:                                         config.FileSystem.Gid,
		FileSystemIgnoreInterrupts:                            config.FileSystem.IgnoreInterrupts,
		FileSystemInactiveMrdCacheSize:                        config.FileSystem.InactiveMrdCacheSize,
		FileSystemKernelListCacheTtlSecs:                      config.FileSystem.KernelListCacheTtlSecs,
		IsFileSystemKernelParamsFileSet:                       string(config.FileSystem.KernelParamsFile) != "",
		FileSystemMaxBackground:                               config.FileSystem.MaxBackground,
		FileSystemMaxReadAheadKb:                              config.FileSystem.MaxReadAheadKb,
		FileSystemRenameDirLimit:                              config.FileSystem.RenameDirLimit,
		FileSystemStrongConsistencyOnOpen:                     config.FileSystem.StrongConsistencyOnOpen,
		IsFileSystemTempDirSet:                                string(config.FileSystem.TempDir) != "",
		FileSystemUid:                                         config.FileSystem.Uid,
		Foreground:                                            config.Foreground,
		GcsAuthAnonymousAccess:                                config.GcsAuth.AnonymousAccess,
		IsGcsAuthKeyFileSet:                                   string(config.GcsAuth.KeyFile) != "",
		GcsAuthReuseTokenFromUrl:                              config.GcsAuth.ReuseTokenFromUrl,
		IsGcsAuthTokenUrlSet:                                  config.GcsAuth.TokenUrl != "",
		IsGcsConnectionBillingProjectSet:                      config.GcsConnection.BillingProject != "",
		GcsConnectionClientProtocol:                           string(config.GcsConnection.ClientProtocol),
		IsGcsConnectionCustomEndpointSet:                      config.GcsConnection.CustomEndpoint != "",
		GcsConnectionEnableHttpDnsCache:                       config.GcsConnection.EnableHttpDnsCache,
		GcsConnectionExperimentalEnableJsonRead:               config.GcsConnection.ExperimentalEnableJsonRead,
		IsGcsConnectionExperimentalLocalSocketAddressSet:      config.GcsConnection.ExperimentalLocalSocketAddress != "",
		GcsConnectionGrpcConnPoolSize:                         config.GcsConnection.GrpcConnPoolSize,
		GcsConnectionGrpcPathStrategy:                         string(config.GcsConnection.GrpcPathStrategy),
		GcsConnectionHttpClientTimeout:                        int64(config.GcsConnection.HttpClientTimeout),
		GcsConnectionLimitBytesPerSec:                         config.GcsConnection.LimitBytesPerSec,
		GcsConnectionLimitOpsPerSec:                           config.GcsConnection.LimitOpsPerSec,
		GcsConnectionMaxConnsPerHost:                          config.GcsConnection.MaxConnsPerHost,
		GcsConnectionMaxIdleConnsPerHost:                      config.GcsConnection.MaxIdleConnsPerHost,
		GcsConnectionSequentialReadSizeMb:                     config.GcsConnection.SequentialReadSizeMb,
		GcsRetriesChunkRetryDeadlineSecs:                      config.GcsRetries.ChunkRetryDeadlineSecs,
		GcsRetriesChunkTransferTimeoutSecs:                    config.GcsRetries.ChunkTransferTimeoutSecs,
		GcsRetriesEnableMountRetries:                          config.GcsRetries.EnableMountRetries,
		GcsRetriesMaxRetryAttempts:                            config.GcsRetries.MaxRetryAttempts,
		GcsRetriesMaxRetrySleep:                               int64(config.GcsRetries.MaxRetrySleep),
		GcsRetriesMultiplier:                                  config.GcsRetries.Multiplier,
		GcsRetriesReadStallEnable:                             config.GcsRetries.ReadStall.Enable,
		GcsRetriesReadStallInitialReqTimeout:                  int64(config.GcsRetries.ReadStall.InitialReqTimeout),
		GcsRetriesReadStallMaxReqTimeout:                      int64(config.GcsRetries.ReadStall.MaxReqTimeout),
		GcsRetriesReadStallMinReqTimeout:                      int64(config.GcsRetries.ReadStall.MinReqTimeout),
		GcsRetriesReadStallReqIncreaseRate:                    config.GcsRetries.ReadStall.ReqIncreaseRate,
		GcsRetriesReadStallReqTargetPercentile:                config.GcsRetries.ReadStall.ReqTargetPercentile,
		ImplicitDirs:                                          config.ImplicitDirs,
		ListEnableEmptyManagedFolders:                         config.List.EnableEmptyManagedFolders,
		LoggingExperimentalEnableOtelLogging:                  config.Logging.ExperimentalEnableOtelLogging,
		IsLoggingExperimentalOtelLoggingEndpointSet:           config.Logging.ExperimentalOtelLoggingEndpoint != "",
		IsLoggingExperimentalOtelLoggingProjectIdSet:          config.Logging.ExperimentalOtelLoggingProjectId != "",
		IsLoggingFilePathSet:                                  string(config.Logging.FilePath) != "",
		IsLoggingFormatSet:                                    config.Logging.Format != "",
		LoggingLogRotateBackupFileCount:                       config.Logging.LogRotate.BackupFileCount,
		LoggingLogRotateCompress:                              config.Logging.LogRotate.Compress,
		LoggingLogRotateMaxFileSizeMb:                         config.Logging.LogRotate.MaxFileSizeMb,
		LoggingSeverity:                                       string(config.Logging.Severity),
		IsLoggingWireLogSet:                                   string(config.Logging.WireLog) != "",
		MachineType:                                           string(config.MachineType),
		MetadataCacheDeprecatedStatCacheCapacity:              config.MetadataCache.DeprecatedStatCacheCapacity,
		MetadataCacheDeprecatedStatCacheTtl:                   int64(config.MetadataCache.DeprecatedStatCacheTtl),
		MetadataCacheDeprecatedTypeCacheTtl:                   int64(config.MetadataCache.DeprecatedTypeCacheTtl),
		MetadataCacheEnableMetadataPrefetch:                   config.MetadataCache.EnableMetadataPrefetch,
		MetadataCacheEnableNonexistentTypeCache:               config.MetadataCache.EnableNonexistentTypeCache,
		MetadataCacheExperimentalEnableOptimizedMetadataCache: config.MetadataCache.ExperimentalEnableOptimizedMetadataCache,
		IsMetadataCacheExperimentalMetadataPrefetchOnMountSet: config.MetadataCache.ExperimentalMetadataPrefetchOnMount != "",
		MetadataCacheMetadataPrefetchEntriesLimit:             config.MetadataCache.MetadataPrefetchEntriesLimit,
		MetadataCacheMetadataPrefetchMaxWorkers:               config.MetadataCache.MetadataPrefetchMaxWorkers,
		MetadataCacheNegativeTtlSecs:                          config.MetadataCache.NegativeTtlSecs,
		MetadataCacheStatCacheMaxSizeMb:                       config.MetadataCache.StatCacheMaxSizeMb,
		MetadataCacheTtlSecs:                                  config.MetadataCache.TtlSecs,
		MetadataCacheTypeCacheMaxSizeMb:                       config.MetadataCache.TypeCacheMaxSizeMb,
		MetricsBufferSize:                                     config.Metrics.BufferSize,
		MetricsCloudMetricsExportIntervalSecs:                 config.Metrics.CloudMetricsExportIntervalSecs,
		MetricsExperimentalEnableGrpcMetrics:                  config.Metrics.ExperimentalEnableGrpcMetrics,
		MetricsExperimentalEnableOtelMetrics:                  config.Metrics.ExperimentalEnableOtelMetrics,
		IsMetricsExperimentalOtelMetricsEndpointSet:           config.Metrics.ExperimentalOtelMetricsEndpoint != "",
		IsMetricsExperimentalOtelMetricsProjectIdSet:          config.Metrics.ExperimentalOtelMetricsProjectId != "",
		MetricsPrometheusPort:                                 config.Metrics.PrometheusPort,
		MetricsStackdriverExportInterval:                      int64(config.Metrics.StackdriverExportInterval),
		MetricsUseNewNames:                                    config.Metrics.UseNewNames,
		MetricsWorkers:                                        config.Metrics.Workers,
		IsMountIdSet:                                          config.MountId != "",
		MrdPoolSize:                                           config.Mrd.PoolSize,
		IsOnlyDirSet:                                          config.OnlyDir != "",
		Profile:                                               string(config.Profile),
		ReadBlockSizeMb:                                       config.Read.BlockSizeMb,
		ReadEnableBufferedRead:                                config.Read.EnableBufferedRead,
		ReadEnableGrpcReadChecksums:                           config.Read.EnableGrpcReadChecksums,
		ReadGlobalMaxBlocks:                                   config.Read.GlobalMaxBlocks,
		ReadInactiveStreamTimeout:                             int64(config.Read.InactiveStreamTimeout),
		ReadMaxBlocksPerHandle:                                config.Read.MaxBlocksPerHandle,
		ReadMinBlocksPerHandle:                                config.Read.MinBlocksPerHandle,
		ReadRandomSeekThreshold:                               config.Read.RandomSeekThreshold,
		ReadStartBlocksPerHandle:                              config.Read.StartBlocksPerHandle,
		IsTraceExportersSet:                                   len(config.Trace.Exporters) > 0,
		IsTraceProjectIdSet:                                   config.Trace.ProjectId != "",
		TraceSamplingRatio:                                    config.Trace.SamplingRatio,
		WorkloadInsightForwardMergeThresholdMb:                config.WorkloadInsight.ForwardMergeThresholdMb,
		IsWorkloadInsightOutputFileSet:                        config.WorkloadInsight.OutputFile != "",
		WorkloadInsightVisualize:                              config.WorkloadInsight.Visualize,
		WriteBlockSizeMb:                                      config.Write.BlockSizeMb,
		WriteCreateEmptyFile:                                  config.Write.CreateEmptyFile,
		WriteEnableRapidAppends:                               config.Write.EnableRapidAppends,
		WriteEnableRapidWrites:                                config.Write.EnableRapidWrites,
		WriteEnableStreamingWrites:                            config.Write.EnableStreamingWrites,
		WriteFinalizeFileForRapid:                             config.Write.FinalizeFileForRapid,
		WriteGlobalMaxBlocks:                                  config.Write.GlobalMaxBlocks,
		WriteMaxBlocksPerFile:                                 config.Write.MaxBlocksPerFile,
	}
}

// SerializeConfigToProtoBase64 maps the given Config to its flat Protobuf representation,
// marshals it using proto3 binary encoding, and encodes it into URL-safe Base64 without padding.
func SerializeConfigToProtoBase64(config *Config) (string, error) {
	if config == nil {
		return "", nil
	}

	protoConfig := ToProto(config)
	data, err := proto.Marshal(protoConfig)
	if err != nil {
		return "", fmt.Errorf("marshaling config proto: %w", err)
	}

	return base64.RawURLEncoding.EncodeToString(data), nil
}
