// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tools/config-gen. DO NOT EDIT.
// GENERATED CODE - DO NOT EDIT MANUALLY.

package cfg

import (
	"encoding/base64"
	"fmt"

	"github.com/googlecloudplatform/gcsfuse/v3/cfg/pb"
	"google.golang.org/protobuf/proto"
)

// ToProto maps a cfg.Config into its flat Protobuf pb.Config representation.
// High-risk text fields (strings, paths) are booleanized to prevent PII leakage.
func ToProto(c *Config) *pb.Config {
	if c == nil {
		return nil
	}

	return &pb.Config{
		IsAppNameSet:                                          c.AppName != "",
		IsCacheDirSet:                                         string(c.CacheDir) != "",
		CloudProfilerAllocatedHeap:                            c.CloudProfiler.AllocatedHeap,
		CloudProfilerCpu:                                      c.CloudProfiler.Cpu,
		CloudProfilerEnabled:                                  c.CloudProfiler.Enabled,
		CloudProfilerGoroutines:                               c.CloudProfiler.Goroutines,
		CloudProfilerHeap:                                     c.CloudProfiler.Heap,
		IsCloudProfilerLabelSet:                               c.CloudProfiler.Label != "",
		CloudProfilerMutex:                                    c.CloudProfiler.Mutex,
		IsCloudProfilerServiceNameSet:                         c.CloudProfiler.ServiceName != "",
		DebugExitOnInvariantViolation:                         c.Debug.ExitOnInvariantViolation,
		DebugFuse:                                             c.Debug.Fuse,
		DebugGcs:                                              c.Debug.Gcs,
		DebugLogMutex:                                         c.Debug.LogMutex,
		DisableAutoconfig:                                     c.DisableAutoconfig,
		DummyIoEnable:                                         c.DummyIo.Enable,
		DummyIoPerMbLatency:                                   int64(c.DummyIo.PerMbLatency),
		DummyIoReaderLatency:                                  int64(c.DummyIo.ReaderLatency),
		EnableAtomicRenameObject:                              c.EnableAtomicRenameObject,
		EnableGoogleLibAuth:                                   c.EnableGoogleLibAuth,
		EnableHns:                                             c.EnableHns,
		EnableNewReader:                                       c.EnableNewReader,
		EnableStandardSymlinks:                                c.EnableStandardSymlinks,
		EnableTypeCacheDeprecation:                            c.EnableTypeCacheDeprecation,
		EnableUnsupportedPathSupport:                          c.EnableUnsupportedPathSupport,
		FileCacheCacheFileForRangeRead:                        c.FileCache.CacheFileForRangeRead,
		FileCacheDownloadChunkSizeMb:                          int32(c.FileCache.DownloadChunkSizeMb),
		FileCacheEnableCrc:                                    c.FileCache.EnableCrc,
		FileCacheEnableExperimentalSharedChunkCache:           c.FileCache.EnableExperimentalSharedChunkCache,
		FileCacheEnableODirect:                                c.FileCache.EnableODirect,
		FileCacheEnableParallelDownloads:                      c.FileCache.EnableParallelDownloads,
		IsFileCacheExcludeRegexSet:                            c.FileCache.ExcludeRegex != "",
		FileCacheExperimentalDisableSizeCalculationFix:        c.FileCache.ExperimentalDisableSizeCalculationFix,
		FileCacheExperimentalEnableChunkCache:                 c.FileCache.ExperimentalEnableChunkCache,
		FileCacheExperimentalParallelDownloadsDefaultOn:       c.FileCache.ExperimentalParallelDownloadsDefaultOn,
		IsFileCacheIncludeRegexSet:                            c.FileCache.IncludeRegex != "",
		FileCacheMaxParallelDownloads:                         int32(c.FileCache.MaxParallelDownloads),
		FileCacheMaxSizeMb:                                    int32(c.FileCache.MaxSizeMb),
		FileCacheParallelDownloadsPerFile:                     int32(c.FileCache.ParallelDownloadsPerFile),
		FileCacheSharedCacheChunkSizeMb:                       int32(c.FileCache.SharedCacheChunkSizeMb),
		FileCacheWriteBufferSize:                              int32(c.FileCache.WriteBufferSize),
		FileSystemCongestionThreshold:                         int32(c.FileSystem.CongestionThreshold),
		FileSystemDirMode:                                     int32(c.FileSystem.DirMode),
		FileSystemDisableParallelDirops:                       c.FileSystem.DisableParallelDirops,
		FileSystemEnableKernelReader:                          c.FileSystem.EnableKernelReader,
		FileSystemExperimentalEnableDentryCache:               c.FileSystem.ExperimentalEnableDentryCache,
		FileSystemExperimentalEnablePirlo:                     c.FileSystem.ExperimentalEnablePirlo,
		FileSystemExperimentalEnableReaddirplus:               c.FileSystem.ExperimentalEnableReaddirplus,
		FileSystemExperimentalODirect:                         c.FileSystem.ExperimentalODirect,
		FileSystemFileMode:                                    int32(c.FileSystem.FileMode),
		FileSystemFuseMaxRequestSizeKb:                        int32(c.FileSystem.FuseMaxRequestSizeKb),
		FileSystemFuseMaxWriteSizeKb:                          int32(c.FileSystem.FuseMaxWriteSizeKb),
		IsFileSystemFuseOptionsSet:                            len(c.FileSystem.FuseOptions) > 0,
		FileSystemGid:                                         int32(c.FileSystem.Gid),
		FileSystemIgnoreInterrupts:                            c.FileSystem.IgnoreInterrupts,
		FileSystemInactiveMrdCacheSize:                        int32(c.FileSystem.InactiveMrdCacheSize),
		FileSystemKernelListCacheTtlSecs:                      int32(c.FileSystem.KernelListCacheTtlSecs),
		IsFileSystemKernelParamsFileSet:                       string(c.FileSystem.KernelParamsFile) != "",
		FileSystemMaxBackground:                               int32(c.FileSystem.MaxBackground),
		FileSystemMaxReadAheadKb:                              int32(c.FileSystem.MaxReadAheadKb),
		FileSystemRenameDirLimit:                              int32(c.FileSystem.RenameDirLimit),
		FileSystemStrongConsistencyOnOpen:                     c.FileSystem.StrongConsistencyOnOpen,
		IsFileSystemTempDirSet:                                string(c.FileSystem.TempDir) != "",
		FileSystemUid:                                         int32(c.FileSystem.Uid),
		Foreground:                                            c.Foreground,
		GcsAuthAnonymousAccess:                                c.GcsAuth.AnonymousAccess,
		IsGcsAuthKeyFileSet:                                   string(c.GcsAuth.KeyFile) != "",
		GcsAuthReuseTokenFromUrl:                              c.GcsAuth.ReuseTokenFromUrl,
		IsGcsAuthTokenUrlSet:                                  c.GcsAuth.TokenUrl != "",
		IsGcsConnectionBillingProjectSet:                      c.GcsConnection.BillingProject != "",
		GcsConnectionClientProtocol:                           string(c.GcsConnection.ClientProtocol),
		IsGcsConnectionCustomEndpointSet:                      c.GcsConnection.CustomEndpoint != "",
		GcsConnectionEnableHttpDnsCache:                       c.GcsConnection.EnableHttpDnsCache,
		GcsConnectionExperimentalEnableJsonRead:               c.GcsConnection.ExperimentalEnableJsonRead,
		IsGcsConnectionExperimentalLocalSocketAddressSet:      c.GcsConnection.ExperimentalLocalSocketAddress != "",
		GcsConnectionGrpcConnPoolSize:                         int32(c.GcsConnection.GrpcConnPoolSize),
		GcsConnectionGrpcPathStrategy:                         string(c.GcsConnection.GrpcPathStrategy),
		GcsConnectionHttpClientTimeout:                        int64(c.GcsConnection.HttpClientTimeout),
		GcsConnectionLimitBytesPerSec:                         c.GcsConnection.LimitBytesPerSec,
		GcsConnectionLimitOpsPerSec:                           c.GcsConnection.LimitOpsPerSec,
		GcsConnectionMaxConnsPerHost:                          int32(c.GcsConnection.MaxConnsPerHost),
		GcsConnectionMaxIdleConnsPerHost:                      int32(c.GcsConnection.MaxIdleConnsPerHost),
		GcsConnectionSequentialReadSizeMb:                     int32(c.GcsConnection.SequentialReadSizeMb),
		GcsRetriesChunkRetryDeadlineSecs:                      int32(c.GcsRetries.ChunkRetryDeadlineSecs),
		GcsRetriesChunkTransferTimeoutSecs:                    int32(c.GcsRetries.ChunkTransferTimeoutSecs),
		GcsRetriesEnableMountRetries:                          c.GcsRetries.EnableMountRetries,
		GcsRetriesMaxRetryAttempts:                            int32(c.GcsRetries.MaxRetryAttempts),
		GcsRetriesMaxRetrySleep:                               int64(c.GcsRetries.MaxRetrySleep),
		GcsRetriesMultiplier:                                  c.GcsRetries.Multiplier,
		GcsRetriesReadStallEnable:                             c.GcsRetries.ReadStall.Enable,
		GcsRetriesReadStallInitialReqTimeout:                  int64(c.GcsRetries.ReadStall.InitialReqTimeout),
		GcsRetriesReadStallMaxReqTimeout:                      int64(c.GcsRetries.ReadStall.MaxReqTimeout),
		GcsRetriesReadStallMinReqTimeout:                      int64(c.GcsRetries.ReadStall.MinReqTimeout),
		GcsRetriesReadStallReqIncreaseRate:                    c.GcsRetries.ReadStall.ReqIncreaseRate,
		GcsRetriesReadStallReqTargetPercentile:                c.GcsRetries.ReadStall.ReqTargetPercentile,
		ImplicitDirs:                                          c.ImplicitDirs,
		ListEnableEmptyManagedFolders:                         c.List.EnableEmptyManagedFolders,
		LoggingExperimentalEnableOtelLogging:                  c.Logging.ExperimentalEnableOtelLogging,
		IsLoggingExperimentalOtelLoggingEndpointSet:           c.Logging.ExperimentalOtelLoggingEndpoint != "",
		IsLoggingExperimentalOtelLoggingProjectIdSet:          c.Logging.ExperimentalOtelLoggingProjectId != "",
		IsLoggingFilePathSet:                                  string(c.Logging.FilePath) != "",
		IsLoggingFormatSet:                                    c.Logging.Format != "",
		LoggingLogRotateBackupFileCount:                       int32(c.Logging.LogRotate.BackupFileCount),
		LoggingLogRotateCompress:                              c.Logging.LogRotate.Compress,
		LoggingLogRotateMaxFileSizeMb:                         int32(c.Logging.LogRotate.MaxFileSizeMb),
		LoggingSeverity:                                       string(c.Logging.Severity),
		IsLoggingWireLogSet:                                   string(c.Logging.WireLog) != "",
		IsMachineTypeSet:                                      c.MachineType != "",
		MetadataCacheDeprecatedStatCacheCapacity:              int32(c.MetadataCache.DeprecatedStatCacheCapacity),
		MetadataCacheDeprecatedStatCacheTtl:                   int64(c.MetadataCache.DeprecatedStatCacheTtl),
		MetadataCacheDeprecatedTypeCacheTtl:                   int64(c.MetadataCache.DeprecatedTypeCacheTtl),
		MetadataCacheEnableMetadataPrefetch:                   c.MetadataCache.EnableMetadataPrefetch,
		MetadataCacheEnableNonexistentTypeCache:               c.MetadataCache.EnableNonexistentTypeCache,
		MetadataCacheExperimentalEnableOptimizedMetadataCache: c.MetadataCache.ExperimentalEnableOptimizedMetadataCache,
		IsMetadataCacheExperimentalMetadataPrefetchOnMountSet: c.MetadataCache.ExperimentalMetadataPrefetchOnMount != "",
		MetadataCacheMetadataPrefetchEntriesLimit:             int32(c.MetadataCache.MetadataPrefetchEntriesLimit),
		MetadataCacheMetadataPrefetchMaxWorkers:               int32(c.MetadataCache.MetadataPrefetchMaxWorkers),
		MetadataCacheNegativeTtlSecs:                          int32(c.MetadataCache.NegativeTtlSecs),
		MetadataCacheStatCacheMaxSizeMb:                       int32(c.MetadataCache.StatCacheMaxSizeMb),
		MetadataCacheTtlSecs:                                  int32(c.MetadataCache.TtlSecs),
		MetadataCacheTypeCacheMaxSizeMb:                       int32(c.MetadataCache.TypeCacheMaxSizeMb),
		MetricsBufferSize:                                     int32(c.Metrics.BufferSize),
		MetricsCloudMetricsExportIntervalSecs:                 int32(c.Metrics.CloudMetricsExportIntervalSecs),
		MetricsExperimentalEnableGrpcMetrics:                  c.Metrics.ExperimentalEnableGrpcMetrics,
		MetricsExperimentalEnableOtelMetrics:                  c.Metrics.ExperimentalEnableOtelMetrics,
		IsMetricsExperimentalOtelMetricsEndpointSet:           c.Metrics.ExperimentalOtelMetricsEndpoint != "",
		IsMetricsExperimentalOtelMetricsProjectIdSet:          c.Metrics.ExperimentalOtelMetricsProjectId != "",
		MetricsPrometheusPort:                                 int32(c.Metrics.PrometheusPort),
		MetricsStackdriverExportInterval:                      int64(c.Metrics.StackdriverExportInterval),
		MetricsUseNewNames:                                    c.Metrics.UseNewNames,
		MetricsWorkers:                                        int32(c.Metrics.Workers),
		IsMountIdSet:                                          c.MountId != "",
		MrdPoolSize:                                           int32(c.Mrd.PoolSize),
		IsOnlyDirSet:                                          c.OnlyDir != "",
		IsProfileSet:                                          c.Profile != "",
		ReadBlockSizeMb:                                       int32(c.Read.BlockSizeMb),
		ReadEnableBufferedRead:                                c.Read.EnableBufferedRead,
		ReadEnableGrpcReadChecksums:                           c.Read.EnableGrpcReadChecksums,
		ReadGlobalMaxBlocks:                                   int32(c.Read.GlobalMaxBlocks),
		ReadInactiveStreamTimeout:                             int64(c.Read.InactiveStreamTimeout),
		ReadMaxBlocksPerHandle:                                int32(c.Read.MaxBlocksPerHandle),
		ReadMinBlocksPerHandle:                                int32(c.Read.MinBlocksPerHandle),
		ReadRandomSeekThreshold:                               int32(c.Read.RandomSeekThreshold),
		ReadStartBlocksPerHandle:                              int32(c.Read.StartBlocksPerHandle),
		IsTraceExportersSet:                                   len(c.Trace.Exporters) > 0,
		IsTraceProjectIdSet:                                   c.Trace.ProjectId != "",
		TraceSamplingRatio:                                    c.Trace.SamplingRatio,
		WorkloadInsightForwardMergeThresholdMb:                int32(c.WorkloadInsight.ForwardMergeThresholdMb),
		IsWorkloadInsightOutputFileSet:                        c.WorkloadInsight.OutputFile != "",
		WorkloadInsightVisualize:                              c.WorkloadInsight.Visualize,
		WriteBlockSizeMb:                                      c.Write.BlockSizeMb,
		WriteCreateEmptyFile:                                  c.Write.CreateEmptyFile,
		WriteEnableRapidAppends:                               c.Write.EnableRapidAppends,
		WriteEnableRapidWrites:                                c.Write.EnableRapidWrites,
		WriteEnableStreamingWrites:                            c.Write.EnableStreamingWrites,
		WriteFinalizeFileForRapid:                             c.Write.FinalizeFileForRapid,
		WriteGlobalMaxBlocks:                                  int32(c.Write.GlobalMaxBlocks),
		WriteMaxBlocksPerFile:                                 int32(c.Write.MaxBlocksPerFile),
	}
}

// SerializeConfigToProtoBase64 maps the given Config to its flat Protobuf representation,
// marshals it using proto3 binary encoding, and encodes it into URL-safe Base64 without padding.
func SerializeConfigToProtoBase64(c *Config) (string, error) {
	if c == nil {
		return "", nil
	}

	p := ToProto(c)
	data, err := proto.Marshal(p)
	if err != nil {
		return "", fmt.Errorf("marshaling config proto: %w", err)
	}

	return base64.RawURLEncoding.EncodeToString(data), nil
}
