codecov:
  strict_yaml_branch: master
coverage:
  round: down
  precision: 2
  status:
    project:  
      default:
        target: 100%
        threshold: 0% 
    patch:
      default:
        target: 100%
        threshold: 0%
