apiVersion: v1
kind: Pod
metadata:
  name: gcs-fuse-csi-example-pod
  namespace: <customer-namespace>
  annotations:
    gke-gcsfuse/volumes: "true"
    # gke-gcsfuse/metadata-prefetch-memory-limit: "0" # min GKE version: `1.32.3-gke.1717000` for this annotation to take effect
    # gke-gcsfuse/metadata-prefetch-cpu-limit: "0" # min GKE version: `1.32.3-gke.1717000` for this annotation to take effect
spec:
  containers:
    # Your workload container spec
    ...
    volumeMounts:
    - name: training-bucket-vol
      mountPath: /training-data
  serviceAccountName: <YOUR_K8S_SA>
  volumes:
  # In-Memory (RAM disk) file cache if dataset fits. Uncomment to use
  #   - name: gke-gcsfuse-cache # gcsfuse file cache backed by RAM Disk
  #     emptyDir:
  #       medium: Memory
  - name: training-bucket-vol
    persistentVolumeClaim:
      claimName: training-bucket-pvc
