// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tools/config-gen. DO NOT EDIT.
// GENERATED CODE - DO NOT EDIT MANUALLY.

package cfg

import (
	"encoding/base64"
	"fmt"

	"github.com/googlecloudplatform/gcsfuse/v3/cfg/pb"
	"google.golang.org/protobuf/proto"
)

// ToProto maps a cfg.Config into its flat Protobuf pb.Config representation.
// High-risk text fields (strings, paths) are booleanized to prevent PII leakage.
func ToProto(c *Config) *pb.Config {
	if c == nil {
		return nil
	}

	return &pb.Config{
	{{- range .ProtoMappings}}
		{{.ProtoFieldName}}: {{.GoExpression}},
	{{- end}}
	}
}

// SerializeConfigToProtoBase64 maps the given Config to its flat Protobuf representation,
// marshals it using proto3 binary encoding, and encodes it into URL-safe Base64 without padding.
func SerializeConfigToProtoBase64(c *Config) (string, error) {
	if c == nil {
		return "", nil
	}

	p := ToProto(c)
	data, err := proto.Marshal(p)
	if err != nil {
		return "", fmt.Errorf("marshaling config proto: %w", err)
	}

	return base64.RawURLEncoding.EncodeToString(data), nil
}
