gcs-connection:
  client-protocol: grpc
  grpc-path-strategy: direct-path-only
file-cache:
  enable-parallel-downloads: true
  max-parallel-downloads: 8
  download-chunk-size-mb: 16
  max-size-mb: 102400
metadata-cache:
  ttl-secs: 3600
  stat-cache-max-size-mb: 1000
