write:
    create-empty-file: false
logging:
    severity: TRACE
    format: ""
    file-path: ""
    log-rotate:
        max-file-size-mb: 512
        backup-file-count: 10
        compress: true
file-cache:
    max-size-mb: 3
    cache-file-for-range-read: false
cache-dir: /usr/local/google/home/tulsishah/cache-dir
metadata-cache: {}
list:
    enable-empty-managed-folders: false
grpc: {}
auth-config:
    anonymous-access: false
enable-hns: false
file-system:
    ignore-interrupts: false
    disable-parallel-dirops: false
    kernel-list-cache-ttl-secs: 0
