targetHost: http://localhost:9000
retryConfig:
- method: XmlRead
  retryInstruction: "stall-for-10s-at-0KiB"
  retryCount: 1
  # To add forced error scenarios for resumable uploads, we need to define skipCount one.
  # This is because the first GET request creates the file in our tests. Subsequent requests
  # actually upload the data, and it's these requests we want to stall for testing.
  skipCount: 1
