// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// GENERATED CODE - DO NOT EDIT MANUALLY.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cfg/config.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloudProfilerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllocatedHeap bool                   `protobuf:"varint,1,opt,name=allocated_heap,json=allocatedHeap,proto3" json:"allocated_heap,omitempty"`
	Cpu           bool                   `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Goroutines    bool                   `protobuf:"varint,4,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	Heap          bool                   `protobuf:"varint,5,opt,name=heap,proto3" json:"heap,omitempty"`
	Label         string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Mutex         bool                   `protobuf:"varint,7,opt,name=mutex,proto3" json:"mutex,omitempty"`
	ServiceName   string                 `protobuf:"bytes,8,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudProfilerConfig) Reset() {
	*x = CloudProfilerConfig{}
	mi := &file_cfg_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudProfilerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudProfilerConfig) ProtoMessage() {}

func (x *CloudProfilerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudProfilerConfig.ProtoReflect.Descriptor instead.
func (*CloudProfilerConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{0}
}

func (x *CloudProfilerConfig) GetAllocatedHeap() bool {
	if x != nil {
		return x.AllocatedHeap
	}
	return false
}

func (x *CloudProfilerConfig) GetCpu() bool {
	if x != nil {
		return x.Cpu
	}
	return false
}

func (x *CloudProfilerConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CloudProfilerConfig) GetGoroutines() bool {
	if x != nil {
		return x.Goroutines
	}
	return false
}

func (x *CloudProfilerConfig) GetHeap() bool {
	if x != nil {
		return x.Heap
	}
	return false
}

func (x *CloudProfilerConfig) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CloudProfilerConfig) GetMutex() bool {
	if x != nil {
		return x.Mutex
	}
	return false
}

func (x *CloudProfilerConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type Config struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	AppName                      string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	CacheDir                     string                 `protobuf:"bytes,2,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	CloudProfiler                *CloudProfilerConfig   `protobuf:"bytes,3,opt,name=cloud_profiler,json=cloudProfiler,proto3" json:"cloud_profiler,omitempty"`
	Debug                        *DebugConfig           `protobuf:"bytes,4,opt,name=debug,proto3" json:"debug,omitempty"`
	DisableAutoconfig            bool                   `protobuf:"varint,5,opt,name=disable_autoconfig,json=disableAutoconfig,proto3" json:"disable_autoconfig,omitempty"`
	DisableListAccessCheck       bool                   `protobuf:"varint,6,opt,name=disable_list_access_check,json=disableListAccessCheck,proto3" json:"disable_list_access_check,omitempty"`
	DummyIo                      *DummyIoConfig         `protobuf:"bytes,7,opt,name=dummy_io,json=dummyIo,proto3" json:"dummy_io,omitempty"`
	EnableAtomicRenameObject     bool                   `protobuf:"varint,8,opt,name=enable_atomic_rename_object,json=enableAtomicRenameObject,proto3" json:"enable_atomic_rename_object,omitempty"`
	EnableGoogleLibAuth          bool                   `protobuf:"varint,9,opt,name=enable_google_lib_auth,json=enableGoogleLibAuth,proto3" json:"enable_google_lib_auth,omitempty"`
	EnableHns                    bool                   `protobuf:"varint,10,opt,name=enable_hns,json=enableHns,proto3" json:"enable_hns,omitempty"`
	EnableNewReader              bool                   `protobuf:"varint,11,opt,name=enable_new_reader,json=enableNewReader,proto3" json:"enable_new_reader,omitempty"`
	EnableStandardSymlinks       bool                   `protobuf:"varint,12,opt,name=enable_standard_symlinks,json=enableStandardSymlinks,proto3" json:"enable_standard_symlinks,omitempty"`
	EnableTypeCacheDeprecation   bool                   `protobuf:"varint,13,opt,name=enable_type_cache_deprecation,json=enableTypeCacheDeprecation,proto3" json:"enable_type_cache_deprecation,omitempty"`
	EnableUnsupportedPathSupport bool                   `protobuf:"varint,14,opt,name=enable_unsupported_path_support,json=enableUnsupportedPathSupport,proto3" json:"enable_unsupported_path_support,omitempty"`
	FileCache                    *FileCacheConfig       `protobuf:"bytes,15,opt,name=file_cache,json=fileCache,proto3" json:"file_cache,omitempty"`
	FileSystem                   *FileSystemConfig      `protobuf:"bytes,16,opt,name=file_system,json=fileSystem,proto3" json:"file_system,omitempty"`
	Foreground                   bool                   `protobuf:"varint,17,opt,name=foreground,proto3" json:"foreground,omitempty"`
	GcsAuth                      *GcsAuthConfig         `protobuf:"bytes,18,opt,name=gcs_auth,json=gcsAuth,proto3" json:"gcs_auth,omitempty"`
	GcsConnection                *GcsConnectionConfig   `protobuf:"bytes,19,opt,name=gcs_connection,json=gcsConnection,proto3" json:"gcs_connection,omitempty"`
	GcsRetries                   *GcsRetriesConfig      `protobuf:"bytes,20,opt,name=gcs_retries,json=gcsRetries,proto3" json:"gcs_retries,omitempty"`
	ImplicitDirs                 bool                   `protobuf:"varint,21,opt,name=implicit_dirs,json=implicitDirs,proto3" json:"implicit_dirs,omitempty"`
	List                         *ListConfig            `protobuf:"bytes,22,opt,name=list,proto3" json:"list,omitempty"`
	Logging                      *LoggingConfig         `protobuf:"bytes,23,opt,name=logging,proto3" json:"logging,omitempty"`
	MachineType                  string                 `protobuf:"bytes,24,opt,name=machine_type,json=machineType,proto3" json:"machine_type,omitempty"`
	MetadataCache                *MetadataCacheConfig   `protobuf:"bytes,25,opt,name=metadata_cache,json=metadataCache,proto3" json:"metadata_cache,omitempty"`
	Metrics                      *MetricsConfig         `protobuf:"bytes,26,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Mrd                          *MrdConfig             `protobuf:"bytes,27,opt,name=mrd,proto3" json:"mrd,omitempty"`
	OnlyDir                      string                 `protobuf:"bytes,28,opt,name=only_dir,json=onlyDir,proto3" json:"only_dir,omitempty"`
	Profile                      string                 `protobuf:"bytes,29,opt,name=profile,proto3" json:"profile,omitempty"`
	Read                         *ReadConfig            `protobuf:"bytes,30,opt,name=read,proto3" json:"read,omitempty"`
	Trace                        *TraceConfig           `protobuf:"bytes,31,opt,name=trace,proto3" json:"trace,omitempty"`
	WorkloadInsight              *WorkloadInsightConfig `protobuf:"bytes,32,opt,name=workload_insight,json=workloadInsight,proto3" json:"workload_insight,omitempty"`
	Write                        *WriteConfig           `protobuf:"bytes,33,opt,name=write,proto3" json:"write,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_cfg_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *Config) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *Config) GetCloudProfiler() *CloudProfilerConfig {
	if x != nil {
		return x.CloudProfiler
	}
	return nil
}

func (x *Config) GetDebug() *DebugConfig {
	if x != nil {
		return x.Debug
	}
	return nil
}

func (x *Config) GetDisableAutoconfig() bool {
	if x != nil {
		return x.DisableAutoconfig
	}
	return false
}

func (x *Config) GetDisableListAccessCheck() bool {
	if x != nil {
		return x.DisableListAccessCheck
	}
	return false
}

func (x *Config) GetDummyIo() *DummyIoConfig {
	if x != nil {
		return x.DummyIo
	}
	return nil
}

func (x *Config) GetEnableAtomicRenameObject() bool {
	if x != nil {
		return x.EnableAtomicRenameObject
	}
	return false
}

func (x *Config) GetEnableGoogleLibAuth() bool {
	if x != nil {
		return x.EnableGoogleLibAuth
	}
	return false
}

func (x *Config) GetEnableHns() bool {
	if x != nil {
		return x.EnableHns
	}
	return false
}

func (x *Config) GetEnableNewReader() bool {
	if x != nil {
		return x.EnableNewReader
	}
	return false
}

func (x *Config) GetEnableStandardSymlinks() bool {
	if x != nil {
		return x.EnableStandardSymlinks
	}
	return false
}

func (x *Config) GetEnableTypeCacheDeprecation() bool {
	if x != nil {
		return x.EnableTypeCacheDeprecation
	}
	return false
}

func (x *Config) GetEnableUnsupportedPathSupport() bool {
	if x != nil {
		return x.EnableUnsupportedPathSupport
	}
	return false
}

func (x *Config) GetFileCache() *FileCacheConfig {
	if x != nil {
		return x.FileCache
	}
	return nil
}

func (x *Config) GetFileSystem() *FileSystemConfig {
	if x != nil {
		return x.FileSystem
	}
	return nil
}

func (x *Config) GetForeground() bool {
	if x != nil {
		return x.Foreground
	}
	return false
}

func (x *Config) GetGcsAuth() *GcsAuthConfig {
	if x != nil {
		return x.GcsAuth
	}
	return nil
}

func (x *Config) GetGcsConnection() *GcsConnectionConfig {
	if x != nil {
		return x.GcsConnection
	}
	return nil
}

func (x *Config) GetGcsRetries() *GcsRetriesConfig {
	if x != nil {
		return x.GcsRetries
	}
	return nil
}

func (x *Config) GetImplicitDirs() bool {
	if x != nil {
		return x.ImplicitDirs
	}
	return false
}

func (x *Config) GetList() *ListConfig {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *Config) GetLogging() *LoggingConfig {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *Config) GetMachineType() string {
	if x != nil {
		return x.MachineType
	}
	return ""
}

func (x *Config) GetMetadataCache() *MetadataCacheConfig {
	if x != nil {
		return x.MetadataCache
	}
	return nil
}

func (x *Config) GetMetrics() *MetricsConfig {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Config) GetMrd() *MrdConfig {
	if x != nil {
		return x.Mrd
	}
	return nil
}

func (x *Config) GetOnlyDir() string {
	if x != nil {
		return x.OnlyDir
	}
	return ""
}

func (x *Config) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Config) GetRead() *ReadConfig {
	if x != nil {
		return x.Read
	}
	return nil
}

func (x *Config) GetTrace() *TraceConfig {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Config) GetWorkloadInsight() *WorkloadInsightConfig {
	if x != nil {
		return x.WorkloadInsight
	}
	return nil
}

func (x *Config) GetWrite() *WriteConfig {
	if x != nil {
		return x.Write
	}
	return nil
}

type DebugConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ExitOnInvariantViolation bool                   `protobuf:"varint,1,opt,name=exit_on_invariant_violation,json=exitOnInvariantViolation,proto3" json:"exit_on_invariant_violation,omitempty"`
	Fuse                     bool                   `protobuf:"varint,2,opt,name=fuse,proto3" json:"fuse,omitempty"`
	Gcs                      bool                   `protobuf:"varint,3,opt,name=gcs,proto3" json:"gcs,omitempty"`
	LogMutex                 bool                   `protobuf:"varint,4,opt,name=log_mutex,json=logMutex,proto3" json:"log_mutex,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DebugConfig) Reset() {
	*x = DebugConfig{}
	mi := &file_cfg_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugConfig) ProtoMessage() {}

func (x *DebugConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugConfig.ProtoReflect.Descriptor instead.
func (*DebugConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{2}
}

func (x *DebugConfig) GetExitOnInvariantViolation() bool {
	if x != nil {
		return x.ExitOnInvariantViolation
	}
	return false
}

func (x *DebugConfig) GetFuse() bool {
	if x != nil {
		return x.Fuse
	}
	return false
}

func (x *DebugConfig) GetGcs() bool {
	if x != nil {
		return x.Gcs
	}
	return false
}

func (x *DebugConfig) GetLogMutex() bool {
	if x != nil {
		return x.LogMutex
	}
	return false
}

type DummyIoConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	PerMbLatency  int64                  `protobuf:"varint,2,opt,name=per_mb_latency,json=perMbLatency,proto3" json:"per_mb_latency,omitempty"`
	ReaderLatency int64                  `protobuf:"varint,3,opt,name=reader_latency,json=readerLatency,proto3" json:"reader_latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyIoConfig) Reset() {
	*x = DummyIoConfig{}
	mi := &file_cfg_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyIoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyIoConfig) ProtoMessage() {}

func (x *DummyIoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyIoConfig.ProtoReflect.Descriptor instead.
func (*DummyIoConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{3}
}

func (x *DummyIoConfig) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *DummyIoConfig) GetPerMbLatency() int64 {
	if x != nil {
		return x.PerMbLatency
	}
	return 0
}

func (x *DummyIoConfig) GetReaderLatency() int64 {
	if x != nil {
		return x.ReaderLatency
	}
	return 0
}

type FileCacheConfig struct {
	state                                  protoimpl.MessageState `protogen:"open.v1"`
	CacheFileForRangeRead                  bool                   `protobuf:"varint,1,opt,name=cache_file_for_range_read,json=cacheFileForRangeRead,proto3" json:"cache_file_for_range_read,omitempty"`
	DownloadChunkSizeMb                    int64                  `protobuf:"varint,2,opt,name=download_chunk_size_mb,json=downloadChunkSizeMb,proto3" json:"download_chunk_size_mb,omitempty"`
	EnableCrc                              bool                   `protobuf:"varint,3,opt,name=enable_crc,json=enableCrc,proto3" json:"enable_crc,omitempty"`
	EnableExperimentalSharedChunkCache     bool                   `protobuf:"varint,4,opt,name=enable_experimental_shared_chunk_cache,json=enableExperimentalSharedChunkCache,proto3" json:"enable_experimental_shared_chunk_cache,omitempty"`
	EnableODirect                          bool                   `protobuf:"varint,5,opt,name=enable_o_direct,json=enableODirect,proto3" json:"enable_o_direct,omitempty"`
	EnableParallelDownloads                bool                   `protobuf:"varint,6,opt,name=enable_parallel_downloads,json=enableParallelDownloads,proto3" json:"enable_parallel_downloads,omitempty"`
	ExcludeRegex                           string                 `protobuf:"bytes,7,opt,name=exclude_regex,json=excludeRegex,proto3" json:"exclude_regex,omitempty"`
	ExperimentalDisableSizeCalculationFix  bool                   `protobuf:"varint,8,opt,name=experimental_disable_size_calculation_fix,json=experimentalDisableSizeCalculationFix,proto3" json:"experimental_disable_size_calculation_fix,omitempty"`
	ExperimentalEnableChunkCache           bool                   `protobuf:"varint,9,opt,name=experimental_enable_chunk_cache,json=experimentalEnableChunkCache,proto3" json:"experimental_enable_chunk_cache,omitempty"`
	ExperimentalParallelDownloadsDefaultOn bool                   `protobuf:"varint,10,opt,name=experimental_parallel_downloads_default_on,json=experimentalParallelDownloadsDefaultOn,proto3" json:"experimental_parallel_downloads_default_on,omitempty"`
	IncludeRegex                           string                 `protobuf:"bytes,11,opt,name=include_regex,json=includeRegex,proto3" json:"include_regex,omitempty"`
	MaxParallelDownloads                   int64                  `protobuf:"varint,12,opt,name=max_parallel_downloads,json=maxParallelDownloads,proto3" json:"max_parallel_downloads,omitempty"`
	MaxSizeMb                              int64                  `protobuf:"varint,13,opt,name=max_size_mb,json=maxSizeMb,proto3" json:"max_size_mb,omitempty"`
	ParallelDownloadsPerFile               int64                  `protobuf:"varint,14,opt,name=parallel_downloads_per_file,json=parallelDownloadsPerFile,proto3" json:"parallel_downloads_per_file,omitempty"`
	SharedCacheChunkSizeMb                 int64                  `protobuf:"varint,15,opt,name=shared_cache_chunk_size_mb,json=sharedCacheChunkSizeMb,proto3" json:"shared_cache_chunk_size_mb,omitempty"`
	WriteBufferSize                        int64                  `protobuf:"varint,16,opt,name=write_buffer_size,json=writeBufferSize,proto3" json:"write_buffer_size,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *FileCacheConfig) Reset() {
	*x = FileCacheConfig{}
	mi := &file_cfg_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCacheConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCacheConfig) ProtoMessage() {}

func (x *FileCacheConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCacheConfig.ProtoReflect.Descriptor instead.
func (*FileCacheConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{4}
}

func (x *FileCacheConfig) GetCacheFileForRangeRead() bool {
	if x != nil {
		return x.CacheFileForRangeRead
	}
	return false
}

func (x *FileCacheConfig) GetDownloadChunkSizeMb() int64 {
	if x != nil {
		return x.DownloadChunkSizeMb
	}
	return 0
}

func (x *FileCacheConfig) GetEnableCrc() bool {
	if x != nil {
		return x.EnableCrc
	}
	return false
}

func (x *FileCacheConfig) GetEnableExperimentalSharedChunkCache() bool {
	if x != nil {
		return x.EnableExperimentalSharedChunkCache
	}
	return false
}

func (x *FileCacheConfig) GetEnableODirect() bool {
	if x != nil {
		return x.EnableODirect
	}
	return false
}

func (x *FileCacheConfig) GetEnableParallelDownloads() bool {
	if x != nil {
		return x.EnableParallelDownloads
	}
	return false
}

func (x *FileCacheConfig) GetExcludeRegex() string {
	if x != nil {
		return x.ExcludeRegex
	}
	return ""
}

func (x *FileCacheConfig) GetExperimentalDisableSizeCalculationFix() bool {
	if x != nil {
		return x.ExperimentalDisableSizeCalculationFix
	}
	return false
}

func (x *FileCacheConfig) GetExperimentalEnableChunkCache() bool {
	if x != nil {
		return x.ExperimentalEnableChunkCache
	}
	return false
}

func (x *FileCacheConfig) GetExperimentalParallelDownloadsDefaultOn() bool {
	if x != nil {
		return x.ExperimentalParallelDownloadsDefaultOn
	}
	return false
}

func (x *FileCacheConfig) GetIncludeRegex() string {
	if x != nil {
		return x.IncludeRegex
	}
	return ""
}

func (x *FileCacheConfig) GetMaxParallelDownloads() int64 {
	if x != nil {
		return x.MaxParallelDownloads
	}
	return 0
}

func (x *FileCacheConfig) GetMaxSizeMb() int64 {
	if x != nil {
		return x.MaxSizeMb
	}
	return 0
}

func (x *FileCacheConfig) GetParallelDownloadsPerFile() int64 {
	if x != nil {
		return x.ParallelDownloadsPerFile
	}
	return 0
}

func (x *FileCacheConfig) GetSharedCacheChunkSizeMb() int64 {
	if x != nil {
		return x.SharedCacheChunkSizeMb
	}
	return 0
}

func (x *FileCacheConfig) GetWriteBufferSize() int64 {
	if x != nil {
		return x.WriteBufferSize
	}
	return 0
}

type FileSystemConfig struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	CongestionThreshold           int64                  `protobuf:"varint,1,opt,name=congestion_threshold,json=congestionThreshold,proto3" json:"congestion_threshold,omitempty"`
	DirMode                       uint32                 `protobuf:"varint,2,opt,name=dir_mode,json=dirMode,proto3" json:"dir_mode,omitempty"`
	DisableParallelDirops         bool                   `protobuf:"varint,3,opt,name=disable_parallel_dirops,json=disableParallelDirops,proto3" json:"disable_parallel_dirops,omitempty"`
	EnableKernelReader            bool                   `protobuf:"varint,4,opt,name=enable_kernel_reader,json=enableKernelReader,proto3" json:"enable_kernel_reader,omitempty"`
	ExperimentalEnableDentryCache bool                   `protobuf:"varint,5,opt,name=experimental_enable_dentry_cache,json=experimentalEnableDentryCache,proto3" json:"experimental_enable_dentry_cache,omitempty"`
	ExperimentalEnablePirlo       bool                   `protobuf:"varint,6,opt,name=experimental_enable_pirlo,json=experimentalEnablePirlo,proto3" json:"experimental_enable_pirlo,omitempty"`
	ExperimentalEnableReaddirplus bool                   `protobuf:"varint,7,opt,name=experimental_enable_readdirplus,json=experimentalEnableReaddirplus,proto3" json:"experimental_enable_readdirplus,omitempty"`
	ExperimentalODirect           bool                   `protobuf:"varint,8,opt,name=experimental_o_direct,json=experimentalODirect,proto3" json:"experimental_o_direct,omitempty"`
	FileMode                      uint32                 `protobuf:"varint,9,opt,name=file_mode,json=fileMode,proto3" json:"file_mode,omitempty"`
	FuseOptions                   []string               `protobuf:"bytes,10,rep,name=fuse_options,json=fuseOptions,proto3" json:"fuse_options,omitempty"`
	Gid                           int64                  `protobuf:"varint,11,opt,name=gid,proto3" json:"gid,omitempty"`
	IgnoreInterrupts              bool                   `protobuf:"varint,12,opt,name=ignore_interrupts,json=ignoreInterrupts,proto3" json:"ignore_interrupts,omitempty"`
	InactiveMrdCacheSize          int64                  `protobuf:"varint,13,opt,name=inactive_mrd_cache_size,json=inactiveMrdCacheSize,proto3" json:"inactive_mrd_cache_size,omitempty"`
	KernelListCacheTtlSecs        int64                  `protobuf:"varint,14,opt,name=kernel_list_cache_ttl_secs,json=kernelListCacheTtlSecs,proto3" json:"kernel_list_cache_ttl_secs,omitempty"`
	KernelParamsFile              string                 `protobuf:"bytes,15,opt,name=kernel_params_file,json=kernelParamsFile,proto3" json:"kernel_params_file,omitempty"`
	MaxBackground                 int64                  `protobuf:"varint,16,opt,name=max_background,json=maxBackground,proto3" json:"max_background,omitempty"`
	MaxReadAheadKb                int64                  `protobuf:"varint,17,opt,name=max_read_ahead_kb,json=maxReadAheadKb,proto3" json:"max_read_ahead_kb,omitempty"`
	RenameDirLimit                int64                  `protobuf:"varint,18,opt,name=rename_dir_limit,json=renameDirLimit,proto3" json:"rename_dir_limit,omitempty"`
	TempDir                       string                 `protobuf:"bytes,19,opt,name=temp_dir,json=tempDir,proto3" json:"temp_dir,omitempty"`
	Uid                           int64                  `protobuf:"varint,20,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *FileSystemConfig) Reset() {
	*x = FileSystemConfig{}
	mi := &file_cfg_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSystemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSystemConfig) ProtoMessage() {}

func (x *FileSystemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSystemConfig.ProtoReflect.Descriptor instead.
func (*FileSystemConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{5}
}

func (x *FileSystemConfig) GetCongestionThreshold() int64 {
	if x != nil {
		return x.CongestionThreshold
	}
	return 0
}

func (x *FileSystemConfig) GetDirMode() uint32 {
	if x != nil {
		return x.DirMode
	}
	return 0
}

func (x *FileSystemConfig) GetDisableParallelDirops() bool {
	if x != nil {
		return x.DisableParallelDirops
	}
	return false
}

func (x *FileSystemConfig) GetEnableKernelReader() bool {
	if x != nil {
		return x.EnableKernelReader
	}
	return false
}

func (x *FileSystemConfig) GetExperimentalEnableDentryCache() bool {
	if x != nil {
		return x.ExperimentalEnableDentryCache
	}
	return false
}

func (x *FileSystemConfig) GetExperimentalEnablePirlo() bool {
	if x != nil {
		return x.ExperimentalEnablePirlo
	}
	return false
}

func (x *FileSystemConfig) GetExperimentalEnableReaddirplus() bool {
	if x != nil {
		return x.ExperimentalEnableReaddirplus
	}
	return false
}

func (x *FileSystemConfig) GetExperimentalODirect() bool {
	if x != nil {
		return x.ExperimentalODirect
	}
	return false
}

func (x *FileSystemConfig) GetFileMode() uint32 {
	if x != nil {
		return x.FileMode
	}
	return 0
}

func (x *FileSystemConfig) GetFuseOptions() []string {
	if x != nil {
		return x.FuseOptions
	}
	return nil
}

func (x *FileSystemConfig) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *FileSystemConfig) GetIgnoreInterrupts() bool {
	if x != nil {
		return x.IgnoreInterrupts
	}
	return false
}

func (x *FileSystemConfig) GetInactiveMrdCacheSize() int64 {
	if x != nil {
		return x.InactiveMrdCacheSize
	}
	return 0
}

func (x *FileSystemConfig) GetKernelListCacheTtlSecs() int64 {
	if x != nil {
		return x.KernelListCacheTtlSecs
	}
	return 0
}

func (x *FileSystemConfig) GetKernelParamsFile() string {
	if x != nil {
		return x.KernelParamsFile
	}
	return ""
}

func (x *FileSystemConfig) GetMaxBackground() int64 {
	if x != nil {
		return x.MaxBackground
	}
	return 0
}

func (x *FileSystemConfig) GetMaxReadAheadKb() int64 {
	if x != nil {
		return x.MaxReadAheadKb
	}
	return 0
}

func (x *FileSystemConfig) GetRenameDirLimit() int64 {
	if x != nil {
		return x.RenameDirLimit
	}
	return 0
}

func (x *FileSystemConfig) GetTempDir() string {
	if x != nil {
		return x.TempDir
	}
	return ""
}

func (x *FileSystemConfig) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GcsAuthConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AnonymousAccess   bool                   `protobuf:"varint,1,opt,name=anonymous_access,json=anonymousAccess,proto3" json:"anonymous_access,omitempty"`
	KeyFile           string                 `protobuf:"bytes,2,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	ReuseTokenFromUrl bool                   `protobuf:"varint,3,opt,name=reuse_token_from_url,json=reuseTokenFromUrl,proto3" json:"reuse_token_from_url,omitempty"`
	TokenUrl          string                 `protobuf:"bytes,4,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GcsAuthConfig) Reset() {
	*x = GcsAuthConfig{}
	mi := &file_cfg_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcsAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcsAuthConfig) ProtoMessage() {}

func (x *GcsAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcsAuthConfig.ProtoReflect.Descriptor instead.
func (*GcsAuthConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{6}
}

func (x *GcsAuthConfig) GetAnonymousAccess() bool {
	if x != nil {
		return x.AnonymousAccess
	}
	return false
}

func (x *GcsAuthConfig) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *GcsAuthConfig) GetReuseTokenFromUrl() bool {
	if x != nil {
		return x.ReuseTokenFromUrl
	}
	return false
}

func (x *GcsAuthConfig) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

type GcsConnectionConfig struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	BillingProject                 string                 `protobuf:"bytes,1,opt,name=billing_project,json=billingProject,proto3" json:"billing_project,omitempty"`
	ClientProtocol                 string                 `protobuf:"bytes,2,opt,name=client_protocol,json=clientProtocol,proto3" json:"client_protocol,omitempty"`
	CustomEndpoint                 string                 `protobuf:"bytes,3,opt,name=custom_endpoint,json=customEndpoint,proto3" json:"custom_endpoint,omitempty"`
	EnableHttpDnsCache             bool                   `protobuf:"varint,4,opt,name=enable_http_dns_cache,json=enableHttpDnsCache,proto3" json:"enable_http_dns_cache,omitempty"`
	ExperimentalEnableJsonRead     bool                   `protobuf:"varint,5,opt,name=experimental_enable_json_read,json=experimentalEnableJsonRead,proto3" json:"experimental_enable_json_read,omitempty"`
	ExperimentalLocalSocketAddress string                 `protobuf:"bytes,6,opt,name=experimental_local_socket_address,json=experimentalLocalSocketAddress,proto3" json:"experimental_local_socket_address,omitempty"`
	GrpcConnPoolSize               int64                  `protobuf:"varint,7,opt,name=grpc_conn_pool_size,json=grpcConnPoolSize,proto3" json:"grpc_conn_pool_size,omitempty"`
	GrpcPathStrategy               string                 `protobuf:"bytes,8,opt,name=grpc_path_strategy,json=grpcPathStrategy,proto3" json:"grpc_path_strategy,omitempty"`
	HttpClientTimeout              int64                  `protobuf:"varint,9,opt,name=http_client_timeout,json=httpClientTimeout,proto3" json:"http_client_timeout,omitempty"`
	LimitBytesPerSec               float64                `protobuf:"fixed64,10,opt,name=limit_bytes_per_sec,json=limitBytesPerSec,proto3" json:"limit_bytes_per_sec,omitempty"`
	LimitOpsPerSec                 float64                `protobuf:"fixed64,11,opt,name=limit_ops_per_sec,json=limitOpsPerSec,proto3" json:"limit_ops_per_sec,omitempty"`
	MaxConnsPerHost                int64                  `protobuf:"varint,12,opt,name=max_conns_per_host,json=maxConnsPerHost,proto3" json:"max_conns_per_host,omitempty"`
	MaxIdleConnsPerHost            int64                  `protobuf:"varint,13,opt,name=max_idle_conns_per_host,json=maxIdleConnsPerHost,proto3" json:"max_idle_conns_per_host,omitempty"`
	SequentialReadSizeMb           int64                  `protobuf:"varint,14,opt,name=sequential_read_size_mb,json=sequentialReadSizeMb,proto3" json:"sequential_read_size_mb,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GcsConnectionConfig) Reset() {
	*x = GcsConnectionConfig{}
	mi := &file_cfg_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcsConnectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcsConnectionConfig) ProtoMessage() {}

func (x *GcsConnectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcsConnectionConfig.ProtoReflect.Descriptor instead.
func (*GcsConnectionConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{7}
}

func (x *GcsConnectionConfig) GetBillingProject() string {
	if x != nil {
		return x.BillingProject
	}
	return ""
}

func (x *GcsConnectionConfig) GetClientProtocol() string {
	if x != nil {
		return x.ClientProtocol
	}
	return ""
}

func (x *GcsConnectionConfig) GetCustomEndpoint() string {
	if x != nil {
		return x.CustomEndpoint
	}
	return ""
}

func (x *GcsConnectionConfig) GetEnableHttpDnsCache() bool {
	if x != nil {
		return x.EnableHttpDnsCache
	}
	return false
}

func (x *GcsConnectionConfig) GetExperimentalEnableJsonRead() bool {
	if x != nil {
		return x.ExperimentalEnableJsonRead
	}
	return false
}

func (x *GcsConnectionConfig) GetExperimentalLocalSocketAddress() string {
	if x != nil {
		return x.ExperimentalLocalSocketAddress
	}
	return ""
}

func (x *GcsConnectionConfig) GetGrpcConnPoolSize() int64 {
	if x != nil {
		return x.GrpcConnPoolSize
	}
	return 0
}

func (x *GcsConnectionConfig) GetGrpcPathStrategy() string {
	if x != nil {
		return x.GrpcPathStrategy
	}
	return ""
}

func (x *GcsConnectionConfig) GetHttpClientTimeout() int64 {
	if x != nil {
		return x.HttpClientTimeout
	}
	return 0
}

func (x *GcsConnectionConfig) GetLimitBytesPerSec() float64 {
	if x != nil {
		return x.LimitBytesPerSec
	}
	return 0
}

func (x *GcsConnectionConfig) GetLimitOpsPerSec() float64 {
	if x != nil {
		return x.LimitOpsPerSec
	}
	return 0
}

func (x *GcsConnectionConfig) GetMaxConnsPerHost() int64 {
	if x != nil {
		return x.MaxConnsPerHost
	}
	return 0
}

func (x *GcsConnectionConfig) GetMaxIdleConnsPerHost() int64 {
	if x != nil {
		return x.MaxIdleConnsPerHost
	}
	return 0
}

func (x *GcsConnectionConfig) GetSequentialReadSizeMb() int64 {
	if x != nil {
		return x.SequentialReadSizeMb
	}
	return 0
}

type GcsRetriesConfig struct {
	state                                   protoimpl.MessageState     `protogen:"open.v1"`
	ChunkRetryDeadlineSecs                  int64                      `protobuf:"varint,1,opt,name=chunk_retry_deadline_secs,json=chunkRetryDeadlineSecs,proto3" json:"chunk_retry_deadline_secs,omitempty"`
	ChunkTransferTimeoutSecs                int64                      `protobuf:"varint,2,opt,name=chunk_transfer_timeout_secs,json=chunkTransferTimeoutSecs,proto3" json:"chunk_transfer_timeout_secs,omitempty"`
	EnableMountRetries                      bool                       `protobuf:"varint,3,opt,name=enable_mount_retries,json=enableMountRetries,proto3" json:"enable_mount_retries,omitempty"`
	ExperimentalNonrapidFolderApiStallRetry bool                       `protobuf:"varint,4,opt,name=experimental_nonrapid_folder_api_stall_retry,json=experimentalNonrapidFolderApiStallRetry,proto3" json:"experimental_nonrapid_folder_api_stall_retry,omitempty"`
	MaxRetryAttempts                        int64                      `protobuf:"varint,5,opt,name=max_retry_attempts,json=maxRetryAttempts,proto3" json:"max_retry_attempts,omitempty"`
	MaxRetrySleep                           int64                      `protobuf:"varint,6,opt,name=max_retry_sleep,json=maxRetrySleep,proto3" json:"max_retry_sleep,omitempty"`
	Multiplier                              float64                    `protobuf:"fixed64,7,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	ReadStall                               *ReadStallGcsRetriesConfig `protobuf:"bytes,8,opt,name=read_stall,json=readStall,proto3" json:"read_stall,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *GcsRetriesConfig) Reset() {
	*x = GcsRetriesConfig{}
	mi := &file_cfg_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcsRetriesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcsRetriesConfig) ProtoMessage() {}

func (x *GcsRetriesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcsRetriesConfig.ProtoReflect.Descriptor instead.
func (*GcsRetriesConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{8}
}

func (x *GcsRetriesConfig) GetChunkRetryDeadlineSecs() int64 {
	if x != nil {
		return x.ChunkRetryDeadlineSecs
	}
	return 0
}

func (x *GcsRetriesConfig) GetChunkTransferTimeoutSecs() int64 {
	if x != nil {
		return x.ChunkTransferTimeoutSecs
	}
	return 0
}

func (x *GcsRetriesConfig) GetEnableMountRetries() bool {
	if x != nil {
		return x.EnableMountRetries
	}
	return false
}

func (x *GcsRetriesConfig) GetExperimentalNonrapidFolderApiStallRetry() bool {
	if x != nil {
		return x.ExperimentalNonrapidFolderApiStallRetry
	}
	return false
}

func (x *GcsRetriesConfig) GetMaxRetryAttempts() int64 {
	if x != nil {
		return x.MaxRetryAttempts
	}
	return 0
}

func (x *GcsRetriesConfig) GetMaxRetrySleep() int64 {
	if x != nil {
		return x.MaxRetrySleep
	}
	return 0
}

func (x *GcsRetriesConfig) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *GcsRetriesConfig) GetReadStall() *ReadStallGcsRetriesConfig {
	if x != nil {
		return x.ReadStall
	}
	return nil
}

type ListConfig struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	EnableEmptyManagedFolders bool                   `protobuf:"varint,1,opt,name=enable_empty_managed_folders,json=enableEmptyManagedFolders,proto3" json:"enable_empty_managed_folders,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListConfig) Reset() {
	*x = ListConfig{}
	mi := &file_cfg_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfig) ProtoMessage() {}

func (x *ListConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfig.ProtoReflect.Descriptor instead.
func (*ListConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{9}
}

func (x *ListConfig) GetEnableEmptyManagedFolders() bool {
	if x != nil {
		return x.EnableEmptyManagedFolders
	}
	return false
}

type LogRotateLoggingConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BackupFileCount int64                  `protobuf:"varint,1,opt,name=backup_file_count,json=backupFileCount,proto3" json:"backup_file_count,omitempty"`
	Compress        bool                   `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`
	MaxFileSizeMb   int64                  `protobuf:"varint,3,opt,name=max_file_size_mb,json=maxFileSizeMb,proto3" json:"max_file_size_mb,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogRotateLoggingConfig) Reset() {
	*x = LogRotateLoggingConfig{}
	mi := &file_cfg_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRotateLoggingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRotateLoggingConfig) ProtoMessage() {}

func (x *LogRotateLoggingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRotateLoggingConfig.ProtoReflect.Descriptor instead.
func (*LogRotateLoggingConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{10}
}

func (x *LogRotateLoggingConfig) GetBackupFileCount() int64 {
	if x != nil {
		return x.BackupFileCount
	}
	return 0
}

func (x *LogRotateLoggingConfig) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *LogRotateLoggingConfig) GetMaxFileSizeMb() int64 {
	if x != nil {
		return x.MaxFileSizeMb
	}
	return 0
}

type LoggingConfig struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	FilePath      string                  `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Format        string                  `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	LogRotate     *LogRotateLoggingConfig `protobuf:"bytes,3,opt,name=log_rotate,json=logRotate,proto3" json:"log_rotate,omitempty"`
	Severity      string                  `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	WireLog       string                  `protobuf:"bytes,5,opt,name=wire_log,json=wireLog,proto3" json:"wire_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingConfig) Reset() {
	*x = LoggingConfig{}
	mi := &file_cfg_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingConfig) ProtoMessage() {}

func (x *LoggingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingConfig.ProtoReflect.Descriptor instead.
func (*LoggingConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{11}
}

func (x *LoggingConfig) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LoggingConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *LoggingConfig) GetLogRotate() *LogRotateLoggingConfig {
	if x != nil {
		return x.LogRotate
	}
	return nil
}

func (x *LoggingConfig) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LoggingConfig) GetWireLog() string {
	if x != nil {
		return x.WireLog
	}
	return ""
}

type MetadataCacheConfig struct {
	state                               protoimpl.MessageState `protogen:"open.v1"`
	DeprecatedStatCacheCapacity         int64                  `protobuf:"varint,1,opt,name=deprecated_stat_cache_capacity,json=deprecatedStatCacheCapacity,proto3" json:"deprecated_stat_cache_capacity,omitempty"`
	DeprecatedStatCacheTtl              int64                  `protobuf:"varint,2,opt,name=deprecated_stat_cache_ttl,json=deprecatedStatCacheTtl,proto3" json:"deprecated_stat_cache_ttl,omitempty"`
	DeprecatedTypeCacheTtl              int64                  `protobuf:"varint,3,opt,name=deprecated_type_cache_ttl,json=deprecatedTypeCacheTtl,proto3" json:"deprecated_type_cache_ttl,omitempty"`
	EnableMetadataPrefetch              bool                   `protobuf:"varint,4,opt,name=enable_metadata_prefetch,json=enableMetadataPrefetch,proto3" json:"enable_metadata_prefetch,omitempty"`
	EnableNonexistentTypeCache          bool                   `protobuf:"varint,5,opt,name=enable_nonexistent_type_cache,json=enableNonexistentTypeCache,proto3" json:"enable_nonexistent_type_cache,omitempty"`
	ExperimentalMetadataPrefetchOnMount string                 `protobuf:"bytes,6,opt,name=experimental_metadata_prefetch_on_mount,json=experimentalMetadataPrefetchOnMount,proto3" json:"experimental_metadata_prefetch_on_mount,omitempty"`
	MetadataPrefetchEntriesLimit        int64                  `protobuf:"varint,7,opt,name=metadata_prefetch_entries_limit,json=metadataPrefetchEntriesLimit,proto3" json:"metadata_prefetch_entries_limit,omitempty"`
	MetadataPrefetchMaxWorkers          int64                  `protobuf:"varint,8,opt,name=metadata_prefetch_max_workers,json=metadataPrefetchMaxWorkers,proto3" json:"metadata_prefetch_max_workers,omitempty"`
	NegativeTtlSecs                     int64                  `protobuf:"varint,9,opt,name=negative_ttl_secs,json=negativeTtlSecs,proto3" json:"negative_ttl_secs,omitempty"`
	StatCacheMaxSizeMb                  int64                  `protobuf:"varint,10,opt,name=stat_cache_max_size_mb,json=statCacheMaxSizeMb,proto3" json:"stat_cache_max_size_mb,omitempty"`
	TtlSecs                             int64                  `protobuf:"varint,11,opt,name=ttl_secs,json=ttlSecs,proto3" json:"ttl_secs,omitempty"`
	TypeCacheMaxSizeMb                  int64                  `protobuf:"varint,12,opt,name=type_cache_max_size_mb,json=typeCacheMaxSizeMb,proto3" json:"type_cache_max_size_mb,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *MetadataCacheConfig) Reset() {
	*x = MetadataCacheConfig{}
	mi := &file_cfg_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataCacheConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataCacheConfig) ProtoMessage() {}

func (x *MetadataCacheConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataCacheConfig.ProtoReflect.Descriptor instead.
func (*MetadataCacheConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{12}
}

func (x *MetadataCacheConfig) GetDeprecatedStatCacheCapacity() int64 {
	if x != nil {
		return x.DeprecatedStatCacheCapacity
	}
	return 0
}

func (x *MetadataCacheConfig) GetDeprecatedStatCacheTtl() int64 {
	if x != nil {
		return x.DeprecatedStatCacheTtl
	}
	return 0
}

func (x *MetadataCacheConfig) GetDeprecatedTypeCacheTtl() int64 {
	if x != nil {
		return x.DeprecatedTypeCacheTtl
	}
	return 0
}

func (x *MetadataCacheConfig) GetEnableMetadataPrefetch() bool {
	if x != nil {
		return x.EnableMetadataPrefetch
	}
	return false
}

func (x *MetadataCacheConfig) GetEnableNonexistentTypeCache() bool {
	if x != nil {
		return x.EnableNonexistentTypeCache
	}
	return false
}

func (x *MetadataCacheConfig) GetExperimentalMetadataPrefetchOnMount() string {
	if x != nil {
		return x.ExperimentalMetadataPrefetchOnMount
	}
	return ""
}

func (x *MetadataCacheConfig) GetMetadataPrefetchEntriesLimit() int64 {
	if x != nil {
		return x.MetadataPrefetchEntriesLimit
	}
	return 0
}

func (x *MetadataCacheConfig) GetMetadataPrefetchMaxWorkers() int64 {
	if x != nil {
		return x.MetadataPrefetchMaxWorkers
	}
	return 0
}

func (x *MetadataCacheConfig) GetNegativeTtlSecs() int64 {
	if x != nil {
		return x.NegativeTtlSecs
	}
	return 0
}

func (x *MetadataCacheConfig) GetStatCacheMaxSizeMb() int64 {
	if x != nil {
		return x.StatCacheMaxSizeMb
	}
	return 0
}

func (x *MetadataCacheConfig) GetTtlSecs() int64 {
	if x != nil {
		return x.TtlSecs
	}
	return 0
}

func (x *MetadataCacheConfig) GetTypeCacheMaxSizeMb() int64 {
	if x != nil {
		return x.TypeCacheMaxSizeMb
	}
	return 0
}

type MetricsConfig struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	BufferSize                     int64                  `protobuf:"varint,1,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	CloudMetricsExportIntervalSecs int64                  `protobuf:"varint,2,opt,name=cloud_metrics_export_interval_secs,json=cloudMetricsExportIntervalSecs,proto3" json:"cloud_metrics_export_interval_secs,omitempty"`
	ExperimentalEnableGrpcMetrics  bool                   `protobuf:"varint,3,opt,name=experimental_enable_grpc_metrics,json=experimentalEnableGrpcMetrics,proto3" json:"experimental_enable_grpc_metrics,omitempty"`
	PrometheusPort                 int64                  `protobuf:"varint,4,opt,name=prometheus_port,json=prometheusPort,proto3" json:"prometheus_port,omitempty"`
	StackdriverExportInterval      int64                  `protobuf:"varint,5,opt,name=stackdriver_export_interval,json=stackdriverExportInterval,proto3" json:"stackdriver_export_interval,omitempty"`
	UseNewNames                    bool                   `protobuf:"varint,6,opt,name=use_new_names,json=useNewNames,proto3" json:"use_new_names,omitempty"`
	Workers                        int64                  `protobuf:"varint,7,opt,name=workers,proto3" json:"workers,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *MetricsConfig) Reset() {
	*x = MetricsConfig{}
	mi := &file_cfg_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsConfig) ProtoMessage() {}

func (x *MetricsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsConfig.ProtoReflect.Descriptor instead.
func (*MetricsConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsConfig) GetBufferSize() int64 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *MetricsConfig) GetCloudMetricsExportIntervalSecs() int64 {
	if x != nil {
		return x.CloudMetricsExportIntervalSecs
	}
	return 0
}

func (x *MetricsConfig) GetExperimentalEnableGrpcMetrics() bool {
	if x != nil {
		return x.ExperimentalEnableGrpcMetrics
	}
	return false
}

func (x *MetricsConfig) GetPrometheusPort() int64 {
	if x != nil {
		return x.PrometheusPort
	}
	return 0
}

func (x *MetricsConfig) GetStackdriverExportInterval() int64 {
	if x != nil {
		return x.StackdriverExportInterval
	}
	return 0
}

func (x *MetricsConfig) GetUseNewNames() bool {
	if x != nil {
		return x.UseNewNames
	}
	return false
}

func (x *MetricsConfig) GetWorkers() int64 {
	if x != nil {
		return x.Workers
	}
	return 0
}

type MrdConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolSize      int64                  `protobuf:"varint,1,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MrdConfig) Reset() {
	*x = MrdConfig{}
	mi := &file_cfg_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MrdConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MrdConfig) ProtoMessage() {}

func (x *MrdConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MrdConfig.ProtoReflect.Descriptor instead.
func (*MrdConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{14}
}

func (x *MrdConfig) GetPoolSize() int64 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

type ReadConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BlockSizeMb           int64                  `protobuf:"varint,1,opt,name=block_size_mb,json=blockSizeMb,proto3" json:"block_size_mb,omitempty"`
	EnableBufferedRead    bool                   `protobuf:"varint,2,opt,name=enable_buffered_read,json=enableBufferedRead,proto3" json:"enable_buffered_read,omitempty"`
	GlobalMaxBlocks       int64                  `protobuf:"varint,3,opt,name=global_max_blocks,json=globalMaxBlocks,proto3" json:"global_max_blocks,omitempty"`
	InactiveStreamTimeout int64                  `protobuf:"varint,4,opt,name=inactive_stream_timeout,json=inactiveStreamTimeout,proto3" json:"inactive_stream_timeout,omitempty"`
	MaxBlocksPerHandle    int64                  `protobuf:"varint,5,opt,name=max_blocks_per_handle,json=maxBlocksPerHandle,proto3" json:"max_blocks_per_handle,omitempty"`
	MinBlocksPerHandle    int64                  `protobuf:"varint,6,opt,name=min_blocks_per_handle,json=minBlocksPerHandle,proto3" json:"min_blocks_per_handle,omitempty"`
	RandomSeekThreshold   int64                  `protobuf:"varint,7,opt,name=random_seek_threshold,json=randomSeekThreshold,proto3" json:"random_seek_threshold,omitempty"`
	StartBlocksPerHandle  int64                  `protobuf:"varint,8,opt,name=start_blocks_per_handle,json=startBlocksPerHandle,proto3" json:"start_blocks_per_handle,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReadConfig) Reset() {
	*x = ReadConfig{}
	mi := &file_cfg_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfig) ProtoMessage() {}

func (x *ReadConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfig.ProtoReflect.Descriptor instead.
func (*ReadConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{15}
}

func (x *ReadConfig) GetBlockSizeMb() int64 {
	if x != nil {
		return x.BlockSizeMb
	}
	return 0
}

func (x *ReadConfig) GetEnableBufferedRead() bool {
	if x != nil {
		return x.EnableBufferedRead
	}
	return false
}

func (x *ReadConfig) GetGlobalMaxBlocks() int64 {
	if x != nil {
		return x.GlobalMaxBlocks
	}
	return 0
}

func (x *ReadConfig) GetInactiveStreamTimeout() int64 {
	if x != nil {
		return x.InactiveStreamTimeout
	}
	return 0
}

func (x *ReadConfig) GetMaxBlocksPerHandle() int64 {
	if x != nil {
		return x.MaxBlocksPerHandle
	}
	return 0
}

func (x *ReadConfig) GetMinBlocksPerHandle() int64 {
	if x != nil {
		return x.MinBlocksPerHandle
	}
	return 0
}

func (x *ReadConfig) GetRandomSeekThreshold() int64 {
	if x != nil {
		return x.RandomSeekThreshold
	}
	return 0
}

func (x *ReadConfig) GetStartBlocksPerHandle() int64 {
	if x != nil {
		return x.StartBlocksPerHandle
	}
	return 0
}

type ReadStallGcsRetriesConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enable              bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	InitialReqTimeout   int64                  `protobuf:"varint,2,opt,name=initial_req_timeout,json=initialReqTimeout,proto3" json:"initial_req_timeout,omitempty"`
	MaxReqTimeout       int64                  `protobuf:"varint,3,opt,name=max_req_timeout,json=maxReqTimeout,proto3" json:"max_req_timeout,omitempty"`
	MinReqTimeout       int64                  `protobuf:"varint,4,opt,name=min_req_timeout,json=minReqTimeout,proto3" json:"min_req_timeout,omitempty"`
	ReqIncreaseRate     float64                `protobuf:"fixed64,5,opt,name=req_increase_rate,json=reqIncreaseRate,proto3" json:"req_increase_rate,omitempty"`
	ReqTargetPercentile float64                `protobuf:"fixed64,6,opt,name=req_target_percentile,json=reqTargetPercentile,proto3" json:"req_target_percentile,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReadStallGcsRetriesConfig) Reset() {
	*x = ReadStallGcsRetriesConfig{}
	mi := &file_cfg_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStallGcsRetriesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStallGcsRetriesConfig) ProtoMessage() {}

func (x *ReadStallGcsRetriesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStallGcsRetriesConfig.ProtoReflect.Descriptor instead.
func (*ReadStallGcsRetriesConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{16}
}

func (x *ReadStallGcsRetriesConfig) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *ReadStallGcsRetriesConfig) GetInitialReqTimeout() int64 {
	if x != nil {
		return x.InitialReqTimeout
	}
	return 0
}

func (x *ReadStallGcsRetriesConfig) GetMaxReqTimeout() int64 {
	if x != nil {
		return x.MaxReqTimeout
	}
	return 0
}

func (x *ReadStallGcsRetriesConfig) GetMinReqTimeout() int64 {
	if x != nil {
		return x.MinReqTimeout
	}
	return 0
}

func (x *ReadStallGcsRetriesConfig) GetReqIncreaseRate() float64 {
	if x != nil {
		return x.ReqIncreaseRate
	}
	return 0
}

func (x *ReadStallGcsRetriesConfig) GetReqTargetPercentile() float64 {
	if x != nil {
		return x.ReqTargetPercentile
	}
	return 0
}

type TraceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exporters     []string               `protobuf:"bytes,1,rep,name=exporters,proto3" json:"exporters,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SamplingRatio float64                `protobuf:"fixed64,3,opt,name=sampling_ratio,json=samplingRatio,proto3" json:"sampling_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceConfig) Reset() {
	*x = TraceConfig{}
	mi := &file_cfg_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceConfig) ProtoMessage() {}

func (x *TraceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceConfig.ProtoReflect.Descriptor instead.
func (*TraceConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{17}
}

func (x *TraceConfig) GetExporters() []string {
	if x != nil {
		return x.Exporters
	}
	return nil
}

func (x *TraceConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TraceConfig) GetSamplingRatio() float64 {
	if x != nil {
		return x.SamplingRatio
	}
	return 0
}

type WorkloadInsightConfig struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ForwardMergeThresholdMb int64                  `protobuf:"varint,1,opt,name=forward_merge_threshold_mb,json=forwardMergeThresholdMb,proto3" json:"forward_merge_threshold_mb,omitempty"`
	OutputFile              string                 `protobuf:"bytes,2,opt,name=output_file,json=outputFile,proto3" json:"output_file,omitempty"`
	Visualize               bool                   `protobuf:"varint,3,opt,name=visualize,proto3" json:"visualize,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *WorkloadInsightConfig) Reset() {
	*x = WorkloadInsightConfig{}
	mi := &file_cfg_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadInsightConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadInsightConfig) ProtoMessage() {}

func (x *WorkloadInsightConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadInsightConfig.ProtoReflect.Descriptor instead.
func (*WorkloadInsightConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{18}
}

func (x *WorkloadInsightConfig) GetForwardMergeThresholdMb() int64 {
	if x != nil {
		return x.ForwardMergeThresholdMb
	}
	return 0
}

func (x *WorkloadInsightConfig) GetOutputFile() string {
	if x != nil {
		return x.OutputFile
	}
	return ""
}

func (x *WorkloadInsightConfig) GetVisualize() bool {
	if x != nil {
		return x.Visualize
	}
	return false
}

type WriteConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BlockSizeMb           int64                  `protobuf:"varint,1,opt,name=block_size_mb,json=blockSizeMb,proto3" json:"block_size_mb,omitempty"`
	CreateEmptyFile       bool                   `protobuf:"varint,2,opt,name=create_empty_file,json=createEmptyFile,proto3" json:"create_empty_file,omitempty"`
	EnableRapidAppends    bool                   `protobuf:"varint,3,opt,name=enable_rapid_appends,json=enableRapidAppends,proto3" json:"enable_rapid_appends,omitempty"`
	EnableRapidWrites     bool                   `protobuf:"varint,4,opt,name=enable_rapid_writes,json=enableRapidWrites,proto3" json:"enable_rapid_writes,omitempty"`
	EnableStreamingWrites bool                   `protobuf:"varint,5,opt,name=enable_streaming_writes,json=enableStreamingWrites,proto3" json:"enable_streaming_writes,omitempty"`
	FinalizeFileOnClose   bool                   `protobuf:"varint,6,opt,name=finalize_file_on_close,json=finalizeFileOnClose,proto3" json:"finalize_file_on_close,omitempty"`
	GlobalMaxBlocks       int64                  `protobuf:"varint,7,opt,name=global_max_blocks,json=globalMaxBlocks,proto3" json:"global_max_blocks,omitempty"`
	MaxBlocksPerFile      int64                  `protobuf:"varint,8,opt,name=max_blocks_per_file,json=maxBlocksPerFile,proto3" json:"max_blocks_per_file,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WriteConfig) Reset() {
	*x = WriteConfig{}
	mi := &file_cfg_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfig) ProtoMessage() {}

func (x *WriteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfig.ProtoReflect.Descriptor instead.
func (*WriteConfig) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{19}
}

func (x *WriteConfig) GetBlockSizeMb() int64 {
	if x != nil {
		return x.BlockSizeMb
	}
	return 0
}

func (x *WriteConfig) GetCreateEmptyFile() bool {
	if x != nil {
		return x.CreateEmptyFile
	}
	return false
}

func (x *WriteConfig) GetEnableRapidAppends() bool {
	if x != nil {
		return x.EnableRapidAppends
	}
	return false
}

func (x *WriteConfig) GetEnableRapidWrites() bool {
	if x != nil {
		return x.EnableRapidWrites
	}
	return false
}

func (x *WriteConfig) GetEnableStreamingWrites() bool {
	if x != nil {
		return x.EnableStreamingWrites
	}
	return false
}

func (x *WriteConfig) GetFinalizeFileOnClose() bool {
	if x != nil {
		return x.FinalizeFileOnClose
	}
	return false
}

func (x *WriteConfig) GetGlobalMaxBlocks() int64 {
	if x != nil {
		return x.GlobalMaxBlocks
	}
	return 0
}

func (x *WriteConfig) GetMaxBlocksPerFile() int64 {
	if x != nil {
		return x.MaxBlocksPerFile
	}
	return 0
}

var File_cfg_config_proto protoreflect.FileDescriptor

const file_cfg_config_proto_rawDesc = "" +
	"\n" +
	"\x10cfg/config.proto\x12\x03cfg\"\xeb\x01\n" +
	"\x13CloudProfilerConfig\x12%\n" +
	"\x0eallocated_heap\x18\x01 \x01(\bR\rallocatedHeap\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\bR\x03cpu\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x04 \x01(\bR\n" +
	"goroutines\x12\x12\n" +
	"\x04heap\x18\x05 \x01(\bR\x04heap\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12\x14\n" +
	"\x05mutex\x18\a \x01(\bR\x05mutex\x12!\n" +
	"\fservice_name\x18\b \x01(\tR\vserviceName\"\x97\f\n" +
	"\x06Config\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1b\n" +
	"\tcache_dir\x18\x02 \x01(\tR\bcacheDir\x12?\n" +
	"\x0ecloud_profiler\x18\x03 \x01(\v2\x18.cfg.CloudProfilerConfigR\rcloudProfiler\x12&\n" +
	"\x05debug\x18\x04 \x01(\v2\x10.cfg.DebugConfigR\x05debug\x12-\n" +
	"\x12disable_autoconfig\x18\x05 \x01(\bR\x11disableAutoconfig\x129\n" +
	"\x19disable_list_access_check\x18\x06 \x01(\bR\x16disableListAccessCheck\x12-\n" +
	"\bdummy_io\x18\a \x01(\v2\x12.cfg.DummyIoConfigR\adummyIo\x12=\n" +
	"\x1benable_atomic_rename_object\x18\b \x01(\bR\x18enableAtomicRenameObject\x123\n" +
	"\x16enable_google_lib_auth\x18\t \x01(\bR\x13enableGoogleLibAuth\x12\x1d\n" +
	"\n" +
	"enable_hns\x18\n" +
	" \x01(\bR\tenableHns\x12*\n" +
	"\x11enable_new_reader\x18\v \x01(\bR\x0fenableNewReader\x128\n" +
	"\x18enable_standard_symlinks\x18\f \x01(\bR\x16enableStandardSymlinks\x12A\n" +
	"\x1denable_type_cache_deprecation\x18\r \x01(\bR\x1aenableTypeCacheDeprecation\x12E\n" +
	"\x1fenable_unsupported_path_support\x18\x0e \x01(\bR\x1cenableUnsupportedPathSupport\x123\n" +
	"\n" +
	"file_cache\x18\x0f \x01(\v2\x14.cfg.FileCacheConfigR\tfileCache\x126\n" +
	"\vfile_system\x18\x10 \x01(\v2\x15.cfg.FileSystemConfigR\n" +
	"fileSystem\x12\x1e\n" +
	"\n" +
	"foreground\x18\x11 \x01(\bR\n" +
	"foreground\x12-\n" +
	"\bgcs_auth\x18\x12 \x01(\v2\x12.cfg.GcsAuthConfigR\agcsAuth\x12?\n" +
	"\x0egcs_connection\x18\x13 \x01(\v2\x18.cfg.GcsConnectionConfigR\rgcsConnection\x126\n" +
	"\vgcs_retries\x18\x14 \x01(\v2\x15.cfg.GcsRetriesConfigR\n" +
	"gcsRetries\x12#\n" +
	"\rimplicit_dirs\x18\x15 \x01(\bR\fimplicitDirs\x12#\n" +
	"\x04list\x18\x16 \x01(\v2\x0f.cfg.ListConfigR\x04list\x12,\n" +
	"\alogging\x18\x17 \x01(\v2\x12.cfg.LoggingConfigR\alogging\x12!\n" +
	"\fmachine_type\x18\x18 \x01(\tR\vmachineType\x12?\n" +
	"\x0emetadata_cache\x18\x19 \x01(\v2\x18.cfg.MetadataCacheConfigR\rmetadataCache\x12,\n" +
	"\ametrics\x18\x1a \x01(\v2\x12.cfg.MetricsConfigR\ametrics\x12 \n" +
	"\x03mrd\x18\x1b \x01(\v2\x0e.cfg.MrdConfigR\x03mrd\x12\x19\n" +
	"\bonly_dir\x18\x1c \x01(\tR\aonlyDir\x12\x18\n" +
	"\aprofile\x18\x1d \x01(\tR\aprofile\x12#\n" +
	"\x04read\x18\x1e \x01(\v2\x0f.cfg.ReadConfigR\x04read\x12&\n" +
	"\x05trace\x18\x1f \x01(\v2\x10.cfg.TraceConfigR\x05trace\x12E\n" +
	"\x10workload_insight\x18  \x01(\v2\x1a.cfg.WorkloadInsightConfigR\x0fworkloadInsight\x12&\n" +
	"\x05write\x18! \x01(\v2\x10.cfg.WriteConfigR\x05write\"\x8f\x01\n" +
	"\vDebugConfig\x12=\n" +
	"\x1bexit_on_invariant_violation\x18\x01 \x01(\bR\x18exitOnInvariantViolation\x12\x12\n" +
	"\x04fuse\x18\x02 \x01(\bR\x04fuse\x12\x10\n" +
	"\x03gcs\x18\x03 \x01(\bR\x03gcs\x12\x1b\n" +
	"\tlog_mutex\x18\x04 \x01(\bR\blogMutex\"t\n" +
	"\rDummyIoConfig\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12$\n" +
	"\x0eper_mb_latency\x18\x02 \x01(\x03R\fperMbLatency\x12%\n" +
	"\x0ereader_latency\x18\x03 \x01(\x03R\rreaderLatency\"\x9b\a\n" +
	"\x0fFileCacheConfig\x128\n" +
	"\x19cache_file_for_range_read\x18\x01 \x01(\bR\x15cacheFileForRangeRead\x123\n" +
	"\x16download_chunk_size_mb\x18\x02 \x01(\x03R\x13downloadChunkSizeMb\x12\x1d\n" +
	"\n" +
	"enable_crc\x18\x03 \x01(\bR\tenableCrc\x12R\n" +
	"&enable_experimental_shared_chunk_cache\x18\x04 \x01(\bR\"enableExperimentalSharedChunkCache\x12&\n" +
	"\x0fenable_o_direct\x18\x05 \x01(\bR\renableODirect\x12:\n" +
	"\x19enable_parallel_downloads\x18\x06 \x01(\bR\x17enableParallelDownloads\x12#\n" +
	"\rexclude_regex\x18\a \x01(\tR\fexcludeRegex\x12X\n" +
	")experimental_disable_size_calculation_fix\x18\b \x01(\bR%experimentalDisableSizeCalculationFix\x12E\n" +
	"\x1fexperimental_enable_chunk_cache\x18\t \x01(\bR\x1cexperimentalEnableChunkCache\x12Z\n" +
	"*experimental_parallel_downloads_default_on\x18\n" +
	" \x01(\bR&experimentalParallelDownloadsDefaultOn\x12#\n" +
	"\rinclude_regex\x18\v \x01(\tR\fincludeRegex\x124\n" +
	"\x16max_parallel_downloads\x18\f \x01(\x03R\x14maxParallelDownloads\x12\x1e\n" +
	"\vmax_size_mb\x18\r \x01(\x03R\tmaxSizeMb\x12=\n" +
	"\x1bparallel_downloads_per_file\x18\x0e \x01(\x03R\x18parallelDownloadsPerFile\x12:\n" +
	"\x1ashared_cache_chunk_size_mb\x18\x0f \x01(\x03R\x16sharedCacheChunkSizeMb\x12*\n" +
	"\x11write_buffer_size\x18\x10 \x01(\x03R\x0fwriteBufferSize\"\x94\a\n" +
	"\x10FileSystemConfig\x121\n" +
	"\x14congestion_threshold\x18\x01 \x01(\x03R\x13congestionThreshold\x12\x19\n" +
	"\bdir_mode\x18\x02 \x01(\rR\adirMode\x126\n" +
	"\x17disable_parallel_dirops\x18\x03 \x01(\bR\x15disableParallelDirops\x120\n" +
	"\x14enable_kernel_reader\x18\x04 \x01(\bR\x12enableKernelReader\x12G\n" +
	" experimental_enable_dentry_cache\x18\x05 \x01(\bR\x1dexperimentalEnableDentryCache\x12:\n" +
	"\x19experimental_enable_pirlo\x18\x06 \x01(\bR\x17experimentalEnablePirlo\x12F\n" +
	"\x1fexperimental_enable_readdirplus\x18\a \x01(\bR\x1dexperimentalEnableReaddirplus\x122\n" +
	"\x15experimental_o_direct\x18\b \x01(\bR\x13experimentalODirect\x12\x1b\n" +
	"\tfile_mode\x18\t \x01(\rR\bfileMode\x12!\n" +
	"\ffuse_options\x18\n" +
	" \x03(\tR\vfuseOptions\x12\x10\n" +
	"\x03gid\x18\v \x01(\x03R\x03gid\x12+\n" +
	"\x11ignore_interrupts\x18\f \x01(\bR\x10ignoreInterrupts\x125\n" +
	"\x17inactive_mrd_cache_size\x18\r \x01(\x03R\x14inactiveMrdCacheSize\x12:\n" +
	"\x1akernel_list_cache_ttl_secs\x18\x0e \x01(\x03R\x16kernelListCacheTtlSecs\x12,\n" +
	"\x12kernel_params_file\x18\x0f \x01(\tR\x10kernelParamsFile\x12%\n" +
	"\x0emax_background\x18\x10 \x01(\x03R\rmaxBackground\x12)\n" +
	"\x11max_read_ahead_kb\x18\x11 \x01(\x03R\x0emaxReadAheadKb\x12(\n" +
	"\x10rename_dir_limit\x18\x12 \x01(\x03R\x0erenameDirLimit\x12\x19\n" +
	"\btemp_dir\x18\x13 \x01(\tR\atempDir\x12\x10\n" +
	"\x03uid\x18\x14 \x01(\x03R\x03uid\"\xa3\x01\n" +
	"\rGcsAuthConfig\x12)\n" +
	"\x10anonymous_access\x18\x01 \x01(\bR\x0fanonymousAccess\x12\x19\n" +
	"\bkey_file\x18\x02 \x01(\tR\akeyFile\x12/\n" +
	"\x14reuse_token_from_url\x18\x03 \x01(\bR\x11reuseTokenFromUrl\x12\x1b\n" +
	"\ttoken_url\x18\x04 \x01(\tR\btokenUrl\"\xd2\x05\n" +
	"\x13GcsConnectionConfig\x12'\n" +
	"\x0fbilling_project\x18\x01 \x01(\tR\x0ebillingProject\x12'\n" +
	"\x0fclient_protocol\x18\x02 \x01(\tR\x0eclientProtocol\x12'\n" +
	"\x0fcustom_endpoint\x18\x03 \x01(\tR\x0ecustomEndpoint\x121\n" +
	"\x15enable_http_dns_cache\x18\x04 \x01(\bR\x12enableHttpDnsCache\x12A\n" +
	"\x1dexperimental_enable_json_read\x18\x05 \x01(\bR\x1aexperimentalEnableJsonRead\x12I\n" +
	"!experimental_local_socket_address\x18\x06 \x01(\tR\x1eexperimentalLocalSocketAddress\x12-\n" +
	"\x13grpc_conn_pool_size\x18\a \x01(\x03R\x10grpcConnPoolSize\x12,\n" +
	"\x12grpc_path_strategy\x18\b \x01(\tR\x10grpcPathStrategy\x12.\n" +
	"\x13http_client_timeout\x18\t \x01(\x03R\x11httpClientTimeout\x12-\n" +
	"\x13limit_bytes_per_sec\x18\n" +
	" \x01(\x01R\x10limitBytesPerSec\x12)\n" +
	"\x11limit_ops_per_sec\x18\v \x01(\x01R\x0elimitOpsPerSec\x12+\n" +
	"\x12max_conns_per_host\x18\f \x01(\x03R\x0fmaxConnsPerHost\x124\n" +
	"\x17max_idle_conns_per_host\x18\r \x01(\x03R\x13maxIdleConnsPerHost\x125\n" +
	"\x17sequential_read_size_mb\x18\x0e \x01(\x03R\x14sequentialReadSizeMb\"\xd2\x03\n" +
	"\x10GcsRetriesConfig\x129\n" +
	"\x19chunk_retry_deadline_secs\x18\x01 \x01(\x03R\x16chunkRetryDeadlineSecs\x12=\n" +
	"\x1bchunk_transfer_timeout_secs\x18\x02 \x01(\x03R\x18chunkTransferTimeoutSecs\x120\n" +
	"\x14enable_mount_retries\x18\x03 \x01(\bR\x12enableMountRetries\x12]\n" +
	",experimental_nonrapid_folder_api_stall_retry\x18\x04 \x01(\bR'experimentalNonrapidFolderApiStallRetry\x12,\n" +
	"\x12max_retry_attempts\x18\x05 \x01(\x03R\x10maxRetryAttempts\x12&\n" +
	"\x0fmax_retry_sleep\x18\x06 \x01(\x03R\rmaxRetrySleep\x12\x1e\n" +
	"\n" +
	"multiplier\x18\a \x01(\x01R\n" +
	"multiplier\x12=\n" +
	"\n" +
	"read_stall\x18\b \x01(\v2\x1e.cfg.ReadStallGcsRetriesConfigR\treadStall\"M\n" +
	"\n" +
	"ListConfig\x12?\n" +
	"\x1cenable_empty_managed_folders\x18\x01 \x01(\bR\x19enableEmptyManagedFolders\"\x89\x01\n" +
	"\x16LogRotateLoggingConfig\x12*\n" +
	"\x11backup_file_count\x18\x01 \x01(\x03R\x0fbackupFileCount\x12\x1a\n" +
	"\bcompress\x18\x02 \x01(\bR\bcompress\x12'\n" +
	"\x10max_file_size_mb\x18\x03 \x01(\x03R\rmaxFileSizeMb\"\xb7\x01\n" +
	"\rLoggingConfig\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12:\n" +
	"\n" +
	"log_rotate\x18\x03 \x01(\v2\x1b.cfg.LogRotateLoggingConfigR\tlogRotate\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x19\n" +
	"\bwire_log\x18\x05 \x01(\tR\awireLog\"\xdc\x05\n" +
	"\x13MetadataCacheConfig\x12C\n" +
	"\x1edeprecated_stat_cache_capacity\x18\x01 \x01(\x03R\x1bdeprecatedStatCacheCapacity\x129\n" +
	"\x19deprecated_stat_cache_ttl\x18\x02 \x01(\x03R\x16deprecatedStatCacheTtl\x129\n" +
	"\x19deprecated_type_cache_ttl\x18\x03 \x01(\x03R\x16deprecatedTypeCacheTtl\x128\n" +
	"\x18enable_metadata_prefetch\x18\x04 \x01(\bR\x16enableMetadataPrefetch\x12A\n" +
	"\x1denable_nonexistent_type_cache\x18\x05 \x01(\bR\x1aenableNonexistentTypeCache\x12T\n" +
	"'experimental_metadata_prefetch_on_mount\x18\x06 \x01(\tR#experimentalMetadataPrefetchOnMount\x12E\n" +
	"\x1fmetadata_prefetch_entries_limit\x18\a \x01(\x03R\x1cmetadataPrefetchEntriesLimit\x12A\n" +
	"\x1dmetadata_prefetch_max_workers\x18\b \x01(\x03R\x1ametadataPrefetchMaxWorkers\x12*\n" +
	"\x11negative_ttl_secs\x18\t \x01(\x03R\x0fnegativeTtlSecs\x122\n" +
	"\x16stat_cache_max_size_mb\x18\n" +
	" \x01(\x03R\x12statCacheMaxSizeMb\x12\x19\n" +
	"\bttl_secs\x18\v \x01(\x03R\attlSecs\x122\n" +
	"\x16type_cache_max_size_mb\x18\f \x01(\x03R\x12typeCacheMaxSizeMb\"\xec\x02\n" +
	"\rMetricsConfig\x12\x1f\n" +
	"\vbuffer_size\x18\x01 \x01(\x03R\n" +
	"bufferSize\x12J\n" +
	"\"cloud_metrics_export_interval_secs\x18\x02 \x01(\x03R\x1ecloudMetricsExportIntervalSecs\x12G\n" +
	" experimental_enable_grpc_metrics\x18\x03 \x01(\bR\x1dexperimentalEnableGrpcMetrics\x12'\n" +
	"\x0fprometheus_port\x18\x04 \x01(\x03R\x0eprometheusPort\x12>\n" +
	"\x1bstackdriver_export_interval\x18\x05 \x01(\x03R\x19stackdriverExportInterval\x12\"\n" +
	"\ruse_new_names\x18\x06 \x01(\bR\vuseNewNames\x12\x18\n" +
	"\aworkers\x18\a \x01(\x03R\aworkers\"(\n" +
	"\tMrdConfig\x12\x1b\n" +
	"\tpool_size\x18\x01 \x01(\x03R\bpoolSize\"\x97\x03\n" +
	"\n" +
	"ReadConfig\x12\"\n" +
	"\rblock_size_mb\x18\x01 \x01(\x03R\vblockSizeMb\x120\n" +
	"\x14enable_buffered_read\x18\x02 \x01(\bR\x12enableBufferedRead\x12*\n" +
	"\x11global_max_blocks\x18\x03 \x01(\x03R\x0fglobalMaxBlocks\x126\n" +
	"\x17inactive_stream_timeout\x18\x04 \x01(\x03R\x15inactiveStreamTimeout\x121\n" +
	"\x15max_blocks_per_handle\x18\x05 \x01(\x03R\x12maxBlocksPerHandle\x121\n" +
	"\x15min_blocks_per_handle\x18\x06 \x01(\x03R\x12minBlocksPerHandle\x122\n" +
	"\x15random_seek_threshold\x18\a \x01(\x03R\x13randomSeekThreshold\x125\n" +
	"\x17start_blocks_per_handle\x18\b \x01(\x03R\x14startBlocksPerHandle\"\x93\x02\n" +
	"\x19ReadStallGcsRetriesConfig\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12.\n" +
	"\x13initial_req_timeout\x18\x02 \x01(\x03R\x11initialReqTimeout\x12&\n" +
	"\x0fmax_req_timeout\x18\x03 \x01(\x03R\rmaxReqTimeout\x12&\n" +
	"\x0fmin_req_timeout\x18\x04 \x01(\x03R\rminReqTimeout\x12*\n" +
	"\x11req_increase_rate\x18\x05 \x01(\x01R\x0freqIncreaseRate\x122\n" +
	"\x15req_target_percentile\x18\x06 \x01(\x01R\x13reqTargetPercentile\"q\n" +
	"\vTraceConfig\x12\x1c\n" +
	"\texporters\x18\x01 \x03(\tR\texporters\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12%\n" +
	"\x0esampling_ratio\x18\x03 \x01(\x01R\rsamplingRatio\"\x93\x01\n" +
	"\x15WorkloadInsightConfig\x12;\n" +
	"\x1aforward_merge_threshold_mb\x18\x01 \x01(\x03R\x17forwardMergeThresholdMb\x12\x1f\n" +
	"\voutput_file\x18\x02 \x01(\tR\n" +
	"outputFile\x12\x1c\n" +
	"\tvisualize\x18\x03 \x01(\bR\tvisualize\"\x87\x03\n" +
	"\vWriteConfig\x12\"\n" +
	"\rblock_size_mb\x18\x01 \x01(\x03R\vblockSizeMb\x12*\n" +
	"\x11create_empty_file\x18\x02 \x01(\bR\x0fcreateEmptyFile\x120\n" +
	"\x14enable_rapid_appends\x18\x03 \x01(\bR\x12enableRapidAppends\x12.\n" +
	"\x13enable_rapid_writes\x18\x04 \x01(\bR\x11enableRapidWrites\x126\n" +
	"\x17enable_streaming_writes\x18\x05 \x01(\bR\x15enableStreamingWrites\x123\n" +
	"\x16finalize_file_on_close\x18\x06 \x01(\bR\x13finalizeFileOnClose\x12*\n" +
	"\x11global_max_blocks\x18\a \x01(\x03R\x0fglobalMaxBlocks\x12-\n" +
	"\x13max_blocks_per_file\x18\b \x01(\x03R\x10maxBlocksPerFileB5Z3github.com/googlecloudplatform/gcsfuse/v3/cfg/pb;pbb\x06proto3"

var (
	file_cfg_config_proto_rawDescOnce sync.Once
	file_cfg_config_proto_rawDescData []byte
)

func file_cfg_config_proto_rawDescGZIP() []byte {
	file_cfg_config_proto_rawDescOnce.Do(func() {
		file_cfg_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cfg_config_proto_rawDesc), len(file_cfg_config_proto_rawDesc)))
	})
	return file_cfg_config_proto_rawDescData
}

var file_cfg_config_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_cfg_config_proto_goTypes = []any{
	(*CloudProfilerConfig)(nil),       // 0: cfg.CloudProfilerConfig
	(*Config)(nil),                    // 1: cfg.Config
	(*DebugConfig)(nil),               // 2: cfg.DebugConfig
	(*DummyIoConfig)(nil),             // 3: cfg.DummyIoConfig
	(*FileCacheConfig)(nil),           // 4: cfg.FileCacheConfig
	(*FileSystemConfig)(nil),          // 5: cfg.FileSystemConfig
	(*GcsAuthConfig)(nil),             // 6: cfg.GcsAuthConfig
	(*GcsConnectionConfig)(nil),       // 7: cfg.GcsConnectionConfig
	(*GcsRetriesConfig)(nil),          // 8: cfg.GcsRetriesConfig
	(*ListConfig)(nil),                // 9: cfg.ListConfig
	(*LogRotateLoggingConfig)(nil),    // 10: cfg.LogRotateLoggingConfig
	(*LoggingConfig)(nil),             // 11: cfg.LoggingConfig
	(*MetadataCacheConfig)(nil),       // 12: cfg.MetadataCacheConfig
	(*MetricsConfig)(nil),             // 13: cfg.MetricsConfig
	(*MrdConfig)(nil),                 // 14: cfg.MrdConfig
	(*ReadConfig)(nil),                // 15: cfg.ReadConfig
	(*ReadStallGcsRetriesConfig)(nil), // 16: cfg.ReadStallGcsRetriesConfig
	(*TraceConfig)(nil),               // 17: cfg.TraceConfig
	(*WorkloadInsightConfig)(nil),     // 18: cfg.WorkloadInsightConfig
	(*WriteConfig)(nil),               // 19: cfg.WriteConfig
}
var file_cfg_config_proto_depIdxs = []int32{
	0,  // 0: cfg.Config.cloud_profiler:type_name -> cfg.CloudProfilerConfig
	2,  // 1: cfg.Config.debug:type_name -> cfg.DebugConfig
	3,  // 2: cfg.Config.dummy_io:type_name -> cfg.DummyIoConfig
	4,  // 3: cfg.Config.file_cache:type_name -> cfg.FileCacheConfig
	5,  // 4: cfg.Config.file_system:type_name -> cfg.FileSystemConfig
	6,  // 5: cfg.Config.gcs_auth:type_name -> cfg.GcsAuthConfig
	7,  // 6: cfg.Config.gcs_connection:type_name -> cfg.GcsConnectionConfig
	8,  // 7: cfg.Config.gcs_retries:type_name -> cfg.GcsRetriesConfig
	9,  // 8: cfg.Config.list:type_name -> cfg.ListConfig
	11, // 9: cfg.Config.logging:type_name -> cfg.LoggingConfig
	12, // 10: cfg.Config.metadata_cache:type_name -> cfg.MetadataCacheConfig
	13, // 11: cfg.Config.metrics:type_name -> cfg.MetricsConfig
	14, // 12: cfg.Config.mrd:type_name -> cfg.MrdConfig
	15, // 13: cfg.Config.read:type_name -> cfg.ReadConfig
	17, // 14: cfg.Config.trace:type_name -> cfg.TraceConfig
	18, // 15: cfg.Config.workload_insight:type_name -> cfg.WorkloadInsightConfig
	19, // 16: cfg.Config.write:type_name -> cfg.WriteConfig
	16, // 17: cfg.GcsRetriesConfig.read_stall:type_name -> cfg.ReadStallGcsRetriesConfig
	10, // 18: cfg.LoggingConfig.log_rotate:type_name -> cfg.LogRotateLoggingConfig
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_cfg_config_proto_init() }
func file_cfg_config_proto_init() {
	if File_cfg_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cfg_config_proto_rawDesc), len(file_cfg_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cfg_config_proto_goTypes,
		DependencyIndexes: file_cfg_config_proto_depIdxs,
		MessageInfos:      file_cfg_config_proto_msgTypes,
	}.Build()
	File_cfg_config_proto = out.File
	file_cfg_config_proto_goTypes = nil
	file_cfg_config_proto_depIdxs = nil
}
