// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tools/config-gen. DO NOT EDIT.
// GENERATED CODE - DO NOT EDIT MANUALLY.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cfg/config.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state                                                 protoimpl.MessageState `protogen:"open.v1"`
	IsAppNameSet                                          bool                   `protobuf:"varint,1,opt,name=is_app_name_set,json=isAppNameSet,proto3" json:"is_app_name_set,omitempty"`
	IsCacheDirSet                                         bool                   `protobuf:"varint,2,opt,name=is_cache_dir_set,json=isCacheDirSet,proto3" json:"is_cache_dir_set,omitempty"`
	CloudProfilerAllocatedHeap                            bool                   `protobuf:"varint,3,opt,name=cloud_profiler_allocated_heap,json=cloudProfilerAllocatedHeap,proto3" json:"cloud_profiler_allocated_heap,omitempty"`
	CloudProfilerCpu                                      bool                   `protobuf:"varint,4,opt,name=cloud_profiler_cpu,json=cloudProfilerCpu,proto3" json:"cloud_profiler_cpu,omitempty"`
	CloudProfilerEnabled                                  bool                   `protobuf:"varint,5,opt,name=cloud_profiler_enabled,json=cloudProfilerEnabled,proto3" json:"cloud_profiler_enabled,omitempty"`
	CloudProfilerGoroutines                               bool                   `protobuf:"varint,6,opt,name=cloud_profiler_goroutines,json=cloudProfilerGoroutines,proto3" json:"cloud_profiler_goroutines,omitempty"`
	CloudProfilerHeap                                     bool                   `protobuf:"varint,7,opt,name=cloud_profiler_heap,json=cloudProfilerHeap,proto3" json:"cloud_profiler_heap,omitempty"`
	IsCloudProfilerLabelSet                               bool                   `protobuf:"varint,8,opt,name=is_cloud_profiler_label_set,json=isCloudProfilerLabelSet,proto3" json:"is_cloud_profiler_label_set,omitempty"`
	CloudProfilerMutex                                    bool                   `protobuf:"varint,9,opt,name=cloud_profiler_mutex,json=cloudProfilerMutex,proto3" json:"cloud_profiler_mutex,omitempty"`
	IsCloudProfilerServiceNameSet                         bool                   `protobuf:"varint,10,opt,name=is_cloud_profiler_service_name_set,json=isCloudProfilerServiceNameSet,proto3" json:"is_cloud_profiler_service_name_set,omitempty"`
	DebugExitOnInvariantViolation                         bool                   `protobuf:"varint,11,opt,name=debug_exit_on_invariant_violation,json=debugExitOnInvariantViolation,proto3" json:"debug_exit_on_invariant_violation,omitempty"`
	DebugFuse                                             bool                   `protobuf:"varint,12,opt,name=debug_fuse,json=debugFuse,proto3" json:"debug_fuse,omitempty"`
	DebugGcs                                              bool                   `protobuf:"varint,13,opt,name=debug_gcs,json=debugGcs,proto3" json:"debug_gcs,omitempty"`
	DebugLogMutex                                         bool                   `protobuf:"varint,14,opt,name=debug_log_mutex,json=debugLogMutex,proto3" json:"debug_log_mutex,omitempty"`
	DisableAutoconfig                                     bool                   `protobuf:"varint,15,opt,name=disable_autoconfig,json=disableAutoconfig,proto3" json:"disable_autoconfig,omitempty"`
	DummyIoEnable                                         bool                   `protobuf:"varint,16,opt,name=dummy_io_enable,json=dummyIoEnable,proto3" json:"dummy_io_enable,omitempty"`
	DummyIoPerMbLatency                                   int64                  `protobuf:"varint,17,opt,name=dummy_io_per_mb_latency,json=dummyIoPerMbLatency,proto3" json:"dummy_io_per_mb_latency,omitempty"`
	DummyIoReaderLatency                                  int64                  `protobuf:"varint,18,opt,name=dummy_io_reader_latency,json=dummyIoReaderLatency,proto3" json:"dummy_io_reader_latency,omitempty"`
	EnableAtomicRenameObject                              bool                   `protobuf:"varint,19,opt,name=enable_atomic_rename_object,json=enableAtomicRenameObject,proto3" json:"enable_atomic_rename_object,omitempty"`
	EnableGoogleLibAuth                                   bool                   `protobuf:"varint,20,opt,name=enable_google_lib_auth,json=enableGoogleLibAuth,proto3" json:"enable_google_lib_auth,omitempty"`
	EnableHns                                             bool                   `protobuf:"varint,21,opt,name=enable_hns,json=enableHns,proto3" json:"enable_hns,omitempty"`
	EnableNewReader                                       bool                   `protobuf:"varint,22,opt,name=enable_new_reader,json=enableNewReader,proto3" json:"enable_new_reader,omitempty"`
	EnableStandardSymlinks                                bool                   `protobuf:"varint,23,opt,name=enable_standard_symlinks,json=enableStandardSymlinks,proto3" json:"enable_standard_symlinks,omitempty"`
	EnableTypeCacheDeprecation                            bool                   `protobuf:"varint,24,opt,name=enable_type_cache_deprecation,json=enableTypeCacheDeprecation,proto3" json:"enable_type_cache_deprecation,omitempty"`
	EnableUnsupportedPathSupport                          bool                   `protobuf:"varint,25,opt,name=enable_unsupported_path_support,json=enableUnsupportedPathSupport,proto3" json:"enable_unsupported_path_support,omitempty"`
	FileCacheCacheFileForRangeRead                        bool                   `protobuf:"varint,26,opt,name=file_cache_cache_file_for_range_read,json=fileCacheCacheFileForRangeRead,proto3" json:"file_cache_cache_file_for_range_read,omitempty"`
	FileCacheDownloadChunkSizeMb                          int32                  `protobuf:"varint,27,opt,name=file_cache_download_chunk_size_mb,json=fileCacheDownloadChunkSizeMb,proto3" json:"file_cache_download_chunk_size_mb,omitempty"`
	FileCacheEnableCrc                                    bool                   `protobuf:"varint,28,opt,name=file_cache_enable_crc,json=fileCacheEnableCrc,proto3" json:"file_cache_enable_crc,omitempty"`
	FileCacheEnableExperimentalSharedChunkCache           bool                   `protobuf:"varint,29,opt,name=file_cache_enable_experimental_shared_chunk_cache,json=fileCacheEnableExperimentalSharedChunkCache,proto3" json:"file_cache_enable_experimental_shared_chunk_cache,omitempty"`
	FileCacheEnableODirect                                bool                   `protobuf:"varint,30,opt,name=file_cache_enable_o_direct,json=fileCacheEnableODirect,proto3" json:"file_cache_enable_o_direct,omitempty"`
	FileCacheEnableParallelDownloads                      bool                   `protobuf:"varint,31,opt,name=file_cache_enable_parallel_downloads,json=fileCacheEnableParallelDownloads,proto3" json:"file_cache_enable_parallel_downloads,omitempty"`
	IsFileCacheExcludeRegexSet                            bool                   `protobuf:"varint,32,opt,name=is_file_cache_exclude_regex_set,json=isFileCacheExcludeRegexSet,proto3" json:"is_file_cache_exclude_regex_set,omitempty"`
	FileCacheExperimentalDisableSizeCalculationFix        bool                   `protobuf:"varint,33,opt,name=file_cache_experimental_disable_size_calculation_fix,json=fileCacheExperimentalDisableSizeCalculationFix,proto3" json:"file_cache_experimental_disable_size_calculation_fix,omitempty"`
	FileCacheExperimentalEnableChunkCache                 bool                   `protobuf:"varint,34,opt,name=file_cache_experimental_enable_chunk_cache,json=fileCacheExperimentalEnableChunkCache,proto3" json:"file_cache_experimental_enable_chunk_cache,omitempty"`
	FileCacheExperimentalParallelDownloadsDefaultOn       bool                   `protobuf:"varint,35,opt,name=file_cache_experimental_parallel_downloads_default_on,json=fileCacheExperimentalParallelDownloadsDefaultOn,proto3" json:"file_cache_experimental_parallel_downloads_default_on,omitempty"`
	IsFileCacheIncludeRegexSet                            bool                   `protobuf:"varint,36,opt,name=is_file_cache_include_regex_set,json=isFileCacheIncludeRegexSet,proto3" json:"is_file_cache_include_regex_set,omitempty"`
	FileCacheMaxParallelDownloads                         int32                  `protobuf:"varint,37,opt,name=file_cache_max_parallel_downloads,json=fileCacheMaxParallelDownloads,proto3" json:"file_cache_max_parallel_downloads,omitempty"`
	FileCacheMaxSizeMb                                    int32                  `protobuf:"varint,38,opt,name=file_cache_max_size_mb,json=fileCacheMaxSizeMb,proto3" json:"file_cache_max_size_mb,omitempty"`
	FileCacheParallelDownloadsPerFile                     int32                  `protobuf:"varint,39,opt,name=file_cache_parallel_downloads_per_file,json=fileCacheParallelDownloadsPerFile,proto3" json:"file_cache_parallel_downloads_per_file,omitempty"`
	FileCacheSharedCacheChunkSizeMb                       int32                  `protobuf:"varint,40,opt,name=file_cache_shared_cache_chunk_size_mb,json=fileCacheSharedCacheChunkSizeMb,proto3" json:"file_cache_shared_cache_chunk_size_mb,omitempty"`
	FileCacheWriteBufferSize                              int32                  `protobuf:"varint,41,opt,name=file_cache_write_buffer_size,json=fileCacheWriteBufferSize,proto3" json:"file_cache_write_buffer_size,omitempty"`
	FileSystemCongestionThreshold                         int32                  `protobuf:"varint,42,opt,name=file_system_congestion_threshold,json=fileSystemCongestionThreshold,proto3" json:"file_system_congestion_threshold,omitempty"`
	FileSystemDirMode                                     int32                  `protobuf:"varint,43,opt,name=file_system_dir_mode,json=fileSystemDirMode,proto3" json:"file_system_dir_mode,omitempty"`
	FileSystemDisableParallelDirops                       bool                   `protobuf:"varint,44,opt,name=file_system_disable_parallel_dirops,json=fileSystemDisableParallelDirops,proto3" json:"file_system_disable_parallel_dirops,omitempty"`
	FileSystemEnableKernelReader                          bool                   `protobuf:"varint,45,opt,name=file_system_enable_kernel_reader,json=fileSystemEnableKernelReader,proto3" json:"file_system_enable_kernel_reader,omitempty"`
	FileSystemExperimentalEnableDentryCache               bool                   `protobuf:"varint,46,opt,name=file_system_experimental_enable_dentry_cache,json=fileSystemExperimentalEnableDentryCache,proto3" json:"file_system_experimental_enable_dentry_cache,omitempty"`
	FileSystemExperimentalEnablePirlo                     bool                   `protobuf:"varint,47,opt,name=file_system_experimental_enable_pirlo,json=fileSystemExperimentalEnablePirlo,proto3" json:"file_system_experimental_enable_pirlo,omitempty"`
	FileSystemExperimentalEnableReaddirplus               bool                   `protobuf:"varint,48,opt,name=file_system_experimental_enable_readdirplus,json=fileSystemExperimentalEnableReaddirplus,proto3" json:"file_system_experimental_enable_readdirplus,omitempty"`
	FileSystemExperimentalODirect                         bool                   `protobuf:"varint,49,opt,name=file_system_experimental_o_direct,json=fileSystemExperimentalODirect,proto3" json:"file_system_experimental_o_direct,omitempty"`
	FileSystemFileMode                                    int32                  `protobuf:"varint,50,opt,name=file_system_file_mode,json=fileSystemFileMode,proto3" json:"file_system_file_mode,omitempty"`
	FileSystemFuseMaxRequestSizeKb                        int32                  `protobuf:"varint,51,opt,name=file_system_fuse_max_request_size_kb,json=fileSystemFuseMaxRequestSizeKb,proto3" json:"file_system_fuse_max_request_size_kb,omitempty"`
	FileSystemFuseMaxWriteSizeKb                          int32                  `protobuf:"varint,52,opt,name=file_system_fuse_max_write_size_kb,json=fileSystemFuseMaxWriteSizeKb,proto3" json:"file_system_fuse_max_write_size_kb,omitempty"`
	IsFileSystemFuseOptionsSet                            bool                   `protobuf:"varint,53,opt,name=is_file_system_fuse_options_set,json=isFileSystemFuseOptionsSet,proto3" json:"is_file_system_fuse_options_set,omitempty"`
	FileSystemGid                                         int32                  `protobuf:"varint,54,opt,name=file_system_gid,json=fileSystemGid,proto3" json:"file_system_gid,omitempty"`
	FileSystemIgnoreInterrupts                            bool                   `protobuf:"varint,55,opt,name=file_system_ignore_interrupts,json=fileSystemIgnoreInterrupts,proto3" json:"file_system_ignore_interrupts,omitempty"`
	FileSystemInactiveMrdCacheSize                        int32                  `protobuf:"varint,56,opt,name=file_system_inactive_mrd_cache_size,json=fileSystemInactiveMrdCacheSize,proto3" json:"file_system_inactive_mrd_cache_size,omitempty"`
	FileSystemKernelListCacheTtlSecs                      int32                  `protobuf:"varint,57,opt,name=file_system_kernel_list_cache_ttl_secs,json=fileSystemKernelListCacheTtlSecs,proto3" json:"file_system_kernel_list_cache_ttl_secs,omitempty"`
	IsFileSystemKernelParamsFileSet                       bool                   `protobuf:"varint,58,opt,name=is_file_system_kernel_params_file_set,json=isFileSystemKernelParamsFileSet,proto3" json:"is_file_system_kernel_params_file_set,omitempty"`
	FileSystemMaxBackground                               int32                  `protobuf:"varint,59,opt,name=file_system_max_background,json=fileSystemMaxBackground,proto3" json:"file_system_max_background,omitempty"`
	FileSystemMaxReadAheadKb                              int32                  `protobuf:"varint,60,opt,name=file_system_max_read_ahead_kb,json=fileSystemMaxReadAheadKb,proto3" json:"file_system_max_read_ahead_kb,omitempty"`
	FileSystemRenameDirLimit                              int32                  `protobuf:"varint,61,opt,name=file_system_rename_dir_limit,json=fileSystemRenameDirLimit,proto3" json:"file_system_rename_dir_limit,omitempty"`
	FileSystemStrongConsistencyOnOpen                     bool                   `protobuf:"varint,62,opt,name=file_system_strong_consistency_on_open,json=fileSystemStrongConsistencyOnOpen,proto3" json:"file_system_strong_consistency_on_open,omitempty"`
	IsFileSystemTempDirSet                                bool                   `protobuf:"varint,63,opt,name=is_file_system_temp_dir_set,json=isFileSystemTempDirSet,proto3" json:"is_file_system_temp_dir_set,omitempty"`
	FileSystemUid                                         int32                  `protobuf:"varint,64,opt,name=file_system_uid,json=fileSystemUid,proto3" json:"file_system_uid,omitempty"`
	Foreground                                            bool                   `protobuf:"varint,65,opt,name=foreground,proto3" json:"foreground,omitempty"`
	GcsAuthAnonymousAccess                                bool                   `protobuf:"varint,66,opt,name=gcs_auth_anonymous_access,json=gcsAuthAnonymousAccess,proto3" json:"gcs_auth_anonymous_access,omitempty"`
	IsGcsAuthKeyFileSet                                   bool                   `protobuf:"varint,67,opt,name=is_gcs_auth_key_file_set,json=isGcsAuthKeyFileSet,proto3" json:"is_gcs_auth_key_file_set,omitempty"`
	GcsAuthReuseTokenFromUrl                              bool                   `protobuf:"varint,68,opt,name=gcs_auth_reuse_token_from_url,json=gcsAuthReuseTokenFromUrl,proto3" json:"gcs_auth_reuse_token_from_url,omitempty"`
	IsGcsAuthTokenUrlSet                                  bool                   `protobuf:"varint,69,opt,name=is_gcs_auth_token_url_set,json=isGcsAuthTokenUrlSet,proto3" json:"is_gcs_auth_token_url_set,omitempty"`
	IsGcsConnectionBillingProjectSet                      bool                   `protobuf:"varint,70,opt,name=is_gcs_connection_billing_project_set,json=isGcsConnectionBillingProjectSet,proto3" json:"is_gcs_connection_billing_project_set,omitempty"`
	GcsConnectionClientProtocol                           string                 `protobuf:"bytes,71,opt,name=gcs_connection_client_protocol,json=gcsConnectionClientProtocol,proto3" json:"gcs_connection_client_protocol,omitempty"`
	IsGcsConnectionCustomEndpointSet                      bool                   `protobuf:"varint,72,opt,name=is_gcs_connection_custom_endpoint_set,json=isGcsConnectionCustomEndpointSet,proto3" json:"is_gcs_connection_custom_endpoint_set,omitempty"`
	GcsConnectionEnableHttpDnsCache                       bool                   `protobuf:"varint,73,opt,name=gcs_connection_enable_http_dns_cache,json=gcsConnectionEnableHttpDnsCache,proto3" json:"gcs_connection_enable_http_dns_cache,omitempty"`
	GcsConnectionExperimentalEnableJsonRead               bool                   `protobuf:"varint,74,opt,name=gcs_connection_experimental_enable_json_read,json=gcsConnectionExperimentalEnableJsonRead,proto3" json:"gcs_connection_experimental_enable_json_read,omitempty"`
	IsGcsConnectionExperimentalLocalSocketAddressSet      bool                   `protobuf:"varint,75,opt,name=is_gcs_connection_experimental_local_socket_address_set,json=isGcsConnectionExperimentalLocalSocketAddressSet,proto3" json:"is_gcs_connection_experimental_local_socket_address_set,omitempty"`
	GcsConnectionGrpcConnPoolSize                         int32                  `protobuf:"varint,76,opt,name=gcs_connection_grpc_conn_pool_size,json=gcsConnectionGrpcConnPoolSize,proto3" json:"gcs_connection_grpc_conn_pool_size,omitempty"`
	GcsConnectionGrpcPathStrategy                         string                 `protobuf:"bytes,77,opt,name=gcs_connection_grpc_path_strategy,json=gcsConnectionGrpcPathStrategy,proto3" json:"gcs_connection_grpc_path_strategy,omitempty"`
	GcsConnectionHttpClientTimeout                        int64                  `protobuf:"varint,78,opt,name=gcs_connection_http_client_timeout,json=gcsConnectionHttpClientTimeout,proto3" json:"gcs_connection_http_client_timeout,omitempty"`
	GcsConnectionLimitBytesPerSec                         float64                `protobuf:"fixed64,79,opt,name=gcs_connection_limit_bytes_per_sec,json=gcsConnectionLimitBytesPerSec,proto3" json:"gcs_connection_limit_bytes_per_sec,omitempty"`
	GcsConnectionLimitOpsPerSec                           float64                `protobuf:"fixed64,80,opt,name=gcs_connection_limit_ops_per_sec,json=gcsConnectionLimitOpsPerSec,proto3" json:"gcs_connection_limit_ops_per_sec,omitempty"`
	GcsConnectionMaxConnsPerHost                          int32                  `protobuf:"varint,81,opt,name=gcs_connection_max_conns_per_host,json=gcsConnectionMaxConnsPerHost,proto3" json:"gcs_connection_max_conns_per_host,omitempty"`
	GcsConnectionMaxIdleConnsPerHost                      int32                  `protobuf:"varint,82,opt,name=gcs_connection_max_idle_conns_per_host,json=gcsConnectionMaxIdleConnsPerHost,proto3" json:"gcs_connection_max_idle_conns_per_host,omitempty"`
	GcsConnectionSequentialReadSizeMb                     int32                  `protobuf:"varint,83,opt,name=gcs_connection_sequential_read_size_mb,json=gcsConnectionSequentialReadSizeMb,proto3" json:"gcs_connection_sequential_read_size_mb,omitempty"`
	GcsRetriesChunkRetryDeadlineSecs                      int32                  `protobuf:"varint,84,opt,name=gcs_retries_chunk_retry_deadline_secs,json=gcsRetriesChunkRetryDeadlineSecs,proto3" json:"gcs_retries_chunk_retry_deadline_secs,omitempty"`
	GcsRetriesChunkTransferTimeoutSecs                    int32                  `protobuf:"varint,85,opt,name=gcs_retries_chunk_transfer_timeout_secs,json=gcsRetriesChunkTransferTimeoutSecs,proto3" json:"gcs_retries_chunk_transfer_timeout_secs,omitempty"`
	GcsRetriesEnableMountRetries                          bool                   `protobuf:"varint,86,opt,name=gcs_retries_enable_mount_retries,json=gcsRetriesEnableMountRetries,proto3" json:"gcs_retries_enable_mount_retries,omitempty"`
	GcsRetriesMaxRetryAttempts                            int32                  `protobuf:"varint,87,opt,name=gcs_retries_max_retry_attempts,json=gcsRetriesMaxRetryAttempts,proto3" json:"gcs_retries_max_retry_attempts,omitempty"`
	GcsRetriesMaxRetrySleep                               int64                  `protobuf:"varint,88,opt,name=gcs_retries_max_retry_sleep,json=gcsRetriesMaxRetrySleep,proto3" json:"gcs_retries_max_retry_sleep,omitempty"`
	GcsRetriesMultiplier                                  float64                `protobuf:"fixed64,89,opt,name=gcs_retries_multiplier,json=gcsRetriesMultiplier,proto3" json:"gcs_retries_multiplier,omitempty"`
	GcsRetriesReadStallEnable                             bool                   `protobuf:"varint,90,opt,name=gcs_retries_read_stall_enable,json=gcsRetriesReadStallEnable,proto3" json:"gcs_retries_read_stall_enable,omitempty"`
	GcsRetriesReadStallInitialReqTimeout                  int64                  `protobuf:"varint,91,opt,name=gcs_retries_read_stall_initial_req_timeout,json=gcsRetriesReadStallInitialReqTimeout,proto3" json:"gcs_retries_read_stall_initial_req_timeout,omitempty"`
	GcsRetriesReadStallMaxReqTimeout                      int64                  `protobuf:"varint,92,opt,name=gcs_retries_read_stall_max_req_timeout,json=gcsRetriesReadStallMaxReqTimeout,proto3" json:"gcs_retries_read_stall_max_req_timeout,omitempty"`
	GcsRetriesReadStallMinReqTimeout                      int64                  `protobuf:"varint,93,opt,name=gcs_retries_read_stall_min_req_timeout,json=gcsRetriesReadStallMinReqTimeout,proto3" json:"gcs_retries_read_stall_min_req_timeout,omitempty"`
	GcsRetriesReadStallReqIncreaseRate                    float64                `protobuf:"fixed64,94,opt,name=gcs_retries_read_stall_req_increase_rate,json=gcsRetriesReadStallReqIncreaseRate,proto3" json:"gcs_retries_read_stall_req_increase_rate,omitempty"`
	GcsRetriesReadStallReqTargetPercentile                float64                `protobuf:"fixed64,95,opt,name=gcs_retries_read_stall_req_target_percentile,json=gcsRetriesReadStallReqTargetPercentile,proto3" json:"gcs_retries_read_stall_req_target_percentile,omitempty"`
	ImplicitDirs                                          bool                   `protobuf:"varint,96,opt,name=implicit_dirs,json=implicitDirs,proto3" json:"implicit_dirs,omitempty"`
	ListEnableEmptyManagedFolders                         bool                   `protobuf:"varint,97,opt,name=list_enable_empty_managed_folders,json=listEnableEmptyManagedFolders,proto3" json:"list_enable_empty_managed_folders,omitempty"`
	LoggingExperimentalEnableOtelLogging                  bool                   `protobuf:"varint,98,opt,name=logging_experimental_enable_otel_logging,json=loggingExperimentalEnableOtelLogging,proto3" json:"logging_experimental_enable_otel_logging,omitempty"`
	IsLoggingExperimentalOtelLoggingEndpointSet           bool                   `protobuf:"varint,99,opt,name=is_logging_experimental_otel_logging_endpoint_set,json=isLoggingExperimentalOtelLoggingEndpointSet,proto3" json:"is_logging_experimental_otel_logging_endpoint_set,omitempty"`
	IsLoggingExperimentalOtelLoggingProjectIdSet          bool                   `protobuf:"varint,100,opt,name=is_logging_experimental_otel_logging_project_id_set,json=isLoggingExperimentalOtelLoggingProjectIdSet,proto3" json:"is_logging_experimental_otel_logging_project_id_set,omitempty"`
	IsLoggingFilePathSet                                  bool                   `protobuf:"varint,101,opt,name=is_logging_file_path_set,json=isLoggingFilePathSet,proto3" json:"is_logging_file_path_set,omitempty"`
	IsLoggingFormatSet                                    bool                   `protobuf:"varint,102,opt,name=is_logging_format_set,json=isLoggingFormatSet,proto3" json:"is_logging_format_set,omitempty"`
	LoggingLogRotateBackupFileCount                       int32                  `protobuf:"varint,103,opt,name=logging_log_rotate_backup_file_count,json=loggingLogRotateBackupFileCount,proto3" json:"logging_log_rotate_backup_file_count,omitempty"`
	LoggingLogRotateCompress                              bool                   `protobuf:"varint,104,opt,name=logging_log_rotate_compress,json=loggingLogRotateCompress,proto3" json:"logging_log_rotate_compress,omitempty"`
	LoggingLogRotateMaxFileSizeMb                         int32                  `protobuf:"varint,105,opt,name=logging_log_rotate_max_file_size_mb,json=loggingLogRotateMaxFileSizeMb,proto3" json:"logging_log_rotate_max_file_size_mb,omitempty"`
	LoggingSeverity                                       string                 `protobuf:"bytes,106,opt,name=logging_severity,json=loggingSeverity,proto3" json:"logging_severity,omitempty"`
	IsLoggingWireLogSet                                   bool                   `protobuf:"varint,107,opt,name=is_logging_wire_log_set,json=isLoggingWireLogSet,proto3" json:"is_logging_wire_log_set,omitempty"`
	IsMachineTypeSet                                      bool                   `protobuf:"varint,108,opt,name=is_machine_type_set,json=isMachineTypeSet,proto3" json:"is_machine_type_set,omitempty"`
	MetadataCacheDeprecatedStatCacheCapacity              int32                  `protobuf:"varint,109,opt,name=metadata_cache_deprecated_stat_cache_capacity,json=metadataCacheDeprecatedStatCacheCapacity,proto3" json:"metadata_cache_deprecated_stat_cache_capacity,omitempty"`
	MetadataCacheDeprecatedStatCacheTtl                   int64                  `protobuf:"varint,110,opt,name=metadata_cache_deprecated_stat_cache_ttl,json=metadataCacheDeprecatedStatCacheTtl,proto3" json:"metadata_cache_deprecated_stat_cache_ttl,omitempty"`
	MetadataCacheDeprecatedTypeCacheTtl                   int64                  `protobuf:"varint,111,opt,name=metadata_cache_deprecated_type_cache_ttl,json=metadataCacheDeprecatedTypeCacheTtl,proto3" json:"metadata_cache_deprecated_type_cache_ttl,omitempty"`
	MetadataCacheEnableMetadataPrefetch                   bool                   `protobuf:"varint,112,opt,name=metadata_cache_enable_metadata_prefetch,json=metadataCacheEnableMetadataPrefetch,proto3" json:"metadata_cache_enable_metadata_prefetch,omitempty"`
	MetadataCacheEnableNonexistentTypeCache               bool                   `protobuf:"varint,113,opt,name=metadata_cache_enable_nonexistent_type_cache,json=metadataCacheEnableNonexistentTypeCache,proto3" json:"metadata_cache_enable_nonexistent_type_cache,omitempty"`
	MetadataCacheExperimentalEnableOptimizedMetadataCache bool                   `protobuf:"varint,114,opt,name=metadata_cache_experimental_enable_optimized_metadata_cache,json=metadataCacheExperimentalEnableOptimizedMetadataCache,proto3" json:"metadata_cache_experimental_enable_optimized_metadata_cache,omitempty"`
	IsMetadataCacheExperimentalMetadataPrefetchOnMountSet bool                   `protobuf:"varint,115,opt,name=is_metadata_cache_experimental_metadata_prefetch_on_mount_set,json=isMetadataCacheExperimentalMetadataPrefetchOnMountSet,proto3" json:"is_metadata_cache_experimental_metadata_prefetch_on_mount_set,omitempty"`
	MetadataCacheMetadataPrefetchEntriesLimit             int32                  `protobuf:"varint,116,opt,name=metadata_cache_metadata_prefetch_entries_limit,json=metadataCacheMetadataPrefetchEntriesLimit,proto3" json:"metadata_cache_metadata_prefetch_entries_limit,omitempty"`
	MetadataCacheMetadataPrefetchMaxWorkers               int32                  `protobuf:"varint,117,opt,name=metadata_cache_metadata_prefetch_max_workers,json=metadataCacheMetadataPrefetchMaxWorkers,proto3" json:"metadata_cache_metadata_prefetch_max_workers,omitempty"`
	MetadataCacheNegativeTtlSecs                          int32                  `protobuf:"varint,118,opt,name=metadata_cache_negative_ttl_secs,json=metadataCacheNegativeTtlSecs,proto3" json:"metadata_cache_negative_ttl_secs,omitempty"`
	MetadataCacheStatCacheMaxSizeMb                       int32                  `protobuf:"varint,119,opt,name=metadata_cache_stat_cache_max_size_mb,json=metadataCacheStatCacheMaxSizeMb,proto3" json:"metadata_cache_stat_cache_max_size_mb,omitempty"`
	MetadataCacheTtlSecs                                  int32                  `protobuf:"varint,120,opt,name=metadata_cache_ttl_secs,json=metadataCacheTtlSecs,proto3" json:"metadata_cache_ttl_secs,omitempty"`
	MetadataCacheTypeCacheMaxSizeMb                       int32                  `protobuf:"varint,121,opt,name=metadata_cache_type_cache_max_size_mb,json=metadataCacheTypeCacheMaxSizeMb,proto3" json:"metadata_cache_type_cache_max_size_mb,omitempty"`
	MetricsBufferSize                                     int32                  `protobuf:"varint,122,opt,name=metrics_buffer_size,json=metricsBufferSize,proto3" json:"metrics_buffer_size,omitempty"`
	MetricsCloudMetricsExportIntervalSecs                 int32                  `protobuf:"varint,123,opt,name=metrics_cloud_metrics_export_interval_secs,json=metricsCloudMetricsExportIntervalSecs,proto3" json:"metrics_cloud_metrics_export_interval_secs,omitempty"`
	MetricsExperimentalEnableGrpcMetrics                  bool                   `protobuf:"varint,124,opt,name=metrics_experimental_enable_grpc_metrics,json=metricsExperimentalEnableGrpcMetrics,proto3" json:"metrics_experimental_enable_grpc_metrics,omitempty"`
	MetricsExperimentalEnableOtelMetrics                  bool                   `protobuf:"varint,125,opt,name=metrics_experimental_enable_otel_metrics,json=metricsExperimentalEnableOtelMetrics,proto3" json:"metrics_experimental_enable_otel_metrics,omitempty"`
	IsMetricsExperimentalOtelMetricsEndpointSet           bool                   `protobuf:"varint,126,opt,name=is_metrics_experimental_otel_metrics_endpoint_set,json=isMetricsExperimentalOtelMetricsEndpointSet,proto3" json:"is_metrics_experimental_otel_metrics_endpoint_set,omitempty"`
	IsMetricsExperimentalOtelMetricsProjectIdSet          bool                   `protobuf:"varint,127,opt,name=is_metrics_experimental_otel_metrics_project_id_set,json=isMetricsExperimentalOtelMetricsProjectIdSet,proto3" json:"is_metrics_experimental_otel_metrics_project_id_set,omitempty"`
	MetricsPrometheusPort                                 int32                  `protobuf:"varint,128,opt,name=metrics_prometheus_port,json=metricsPrometheusPort,proto3" json:"metrics_prometheus_port,omitempty"`
	MetricsStackdriverExportInterval                      int64                  `protobuf:"varint,129,opt,name=metrics_stackdriver_export_interval,json=metricsStackdriverExportInterval,proto3" json:"metrics_stackdriver_export_interval,omitempty"`
	MetricsUseNewNames                                    bool                   `protobuf:"varint,130,opt,name=metrics_use_new_names,json=metricsUseNewNames,proto3" json:"metrics_use_new_names,omitempty"`
	MetricsWorkers                                        int32                  `protobuf:"varint,131,opt,name=metrics_workers,json=metricsWorkers,proto3" json:"metrics_workers,omitempty"`
	IsMountIdSet                                          bool                   `protobuf:"varint,132,opt,name=is_mount_id_set,json=isMountIdSet,proto3" json:"is_mount_id_set,omitempty"`
	MrdPoolSize                                           int32                  `protobuf:"varint,133,opt,name=mrd_pool_size,json=mrdPoolSize,proto3" json:"mrd_pool_size,omitempty"`
	IsOnlyDirSet                                          bool                   `protobuf:"varint,134,opt,name=is_only_dir_set,json=isOnlyDirSet,proto3" json:"is_only_dir_set,omitempty"`
	IsProfileSet                                          bool                   `protobuf:"varint,135,opt,name=is_profile_set,json=isProfileSet,proto3" json:"is_profile_set,omitempty"`
	ReadBlockSizeMb                                       int32                  `protobuf:"varint,136,opt,name=read_block_size_mb,json=readBlockSizeMb,proto3" json:"read_block_size_mb,omitempty"`
	ReadEnableBufferedRead                                bool                   `protobuf:"varint,137,opt,name=read_enable_buffered_read,json=readEnableBufferedRead,proto3" json:"read_enable_buffered_read,omitempty"`
	ReadEnableGrpcReadChecksums                           bool                   `protobuf:"varint,138,opt,name=read_enable_grpc_read_checksums,json=readEnableGrpcReadChecksums,proto3" json:"read_enable_grpc_read_checksums,omitempty"`
	ReadGlobalMaxBlocks                                   int32                  `protobuf:"varint,139,opt,name=read_global_max_blocks,json=readGlobalMaxBlocks,proto3" json:"read_global_max_blocks,omitempty"`
	ReadInactiveStreamTimeout                             int64                  `protobuf:"varint,140,opt,name=read_inactive_stream_timeout,json=readInactiveStreamTimeout,proto3" json:"read_inactive_stream_timeout,omitempty"`
	ReadMaxBlocksPerHandle                                int32                  `protobuf:"varint,141,opt,name=read_max_blocks_per_handle,json=readMaxBlocksPerHandle,proto3" json:"read_max_blocks_per_handle,omitempty"`
	ReadMinBlocksPerHandle                                int32                  `protobuf:"varint,142,opt,name=read_min_blocks_per_handle,json=readMinBlocksPerHandle,proto3" json:"read_min_blocks_per_handle,omitempty"`
	ReadRandomSeekThreshold                               int32                  `protobuf:"varint,143,opt,name=read_random_seek_threshold,json=readRandomSeekThreshold,proto3" json:"read_random_seek_threshold,omitempty"`
	ReadStartBlocksPerHandle                              int32                  `protobuf:"varint,144,opt,name=read_start_blocks_per_handle,json=readStartBlocksPerHandle,proto3" json:"read_start_blocks_per_handle,omitempty"`
	IsTraceExportersSet                                   bool                   `protobuf:"varint,145,opt,name=is_trace_exporters_set,json=isTraceExportersSet,proto3" json:"is_trace_exporters_set,omitempty"`
	IsTraceProjectIdSet                                   bool                   `protobuf:"varint,146,opt,name=is_trace_project_id_set,json=isTraceProjectIdSet,proto3" json:"is_trace_project_id_set,omitempty"`
	TraceSamplingRatio                                    float64                `protobuf:"fixed64,147,opt,name=trace_sampling_ratio,json=traceSamplingRatio,proto3" json:"trace_sampling_ratio,omitempty"`
	WorkloadInsightForwardMergeThresholdMb                int32                  `protobuf:"varint,148,opt,name=workload_insight_forward_merge_threshold_mb,json=workloadInsightForwardMergeThresholdMb,proto3" json:"workload_insight_forward_merge_threshold_mb,omitempty"`
	IsWorkloadInsightOutputFileSet                        bool                   `protobuf:"varint,149,opt,name=is_workload_insight_output_file_set,json=isWorkloadInsightOutputFileSet,proto3" json:"is_workload_insight_output_file_set,omitempty"`
	WorkloadInsightVisualize                              bool                   `protobuf:"varint,150,opt,name=workload_insight_visualize,json=workloadInsightVisualize,proto3" json:"workload_insight_visualize,omitempty"`
	WriteBlockSizeMb                                      float64                `protobuf:"fixed64,151,opt,name=write_block_size_mb,json=writeBlockSizeMb,proto3" json:"write_block_size_mb,omitempty"`
	WriteCreateEmptyFile                                  bool                   `protobuf:"varint,152,opt,name=write_create_empty_file,json=writeCreateEmptyFile,proto3" json:"write_create_empty_file,omitempty"`
	WriteEnableRapidAppends                               bool                   `protobuf:"varint,153,opt,name=write_enable_rapid_appends,json=writeEnableRapidAppends,proto3" json:"write_enable_rapid_appends,omitempty"`
	WriteEnableRapidWrites                                bool                   `protobuf:"varint,154,opt,name=write_enable_rapid_writes,json=writeEnableRapidWrites,proto3" json:"write_enable_rapid_writes,omitempty"`
	WriteEnableStreamingWrites                            bool                   `protobuf:"varint,155,opt,name=write_enable_streaming_writes,json=writeEnableStreamingWrites,proto3" json:"write_enable_streaming_writes,omitempty"`
	WriteFinalizeFileForRapid                             bool                   `protobuf:"varint,156,opt,name=write_finalize_file_for_rapid,json=writeFinalizeFileForRapid,proto3" json:"write_finalize_file_for_rapid,omitempty"`
	WriteGlobalMaxBlocks                                  int32                  `protobuf:"varint,157,opt,name=write_global_max_blocks,json=writeGlobalMaxBlocks,proto3" json:"write_global_max_blocks,omitempty"`
	WriteMaxBlocksPerFile                                 int32                  `protobuf:"varint,158,opt,name=write_max_blocks_per_file,json=writeMaxBlocksPerFile,proto3" json:"write_max_blocks_per_file,omitempty"`
	unknownFields                                         protoimpl.UnknownFields
	sizeCache                                             protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_cfg_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_cfg_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetIsAppNameSet() bool {
	if x != nil {
		return x.IsAppNameSet
	}
	return false
}

func (x *Config) GetIsCacheDirSet() bool {
	if x != nil {
		return x.IsCacheDirSet
	}
	return false
}

func (x *Config) GetCloudProfilerAllocatedHeap() bool {
	if x != nil {
		return x.CloudProfilerAllocatedHeap
	}
	return false
}

func (x *Config) GetCloudProfilerCpu() bool {
	if x != nil {
		return x.CloudProfilerCpu
	}
	return false
}

func (x *Config) GetCloudProfilerEnabled() bool {
	if x != nil {
		return x.CloudProfilerEnabled
	}
	return false
}

func (x *Config) GetCloudProfilerGoroutines() bool {
	if x != nil {
		return x.CloudProfilerGoroutines
	}
	return false
}

func (x *Config) GetCloudProfilerHeap() bool {
	if x != nil {
		return x.CloudProfilerHeap
	}
	return false
}

func (x *Config) GetIsCloudProfilerLabelSet() bool {
	if x != nil {
		return x.IsCloudProfilerLabelSet
	}
	return false
}

func (x *Config) GetCloudProfilerMutex() bool {
	if x != nil {
		return x.CloudProfilerMutex
	}
	return false
}

func (x *Config) GetIsCloudProfilerServiceNameSet() bool {
	if x != nil {
		return x.IsCloudProfilerServiceNameSet
	}
	return false
}

func (x *Config) GetDebugExitOnInvariantViolation() bool {
	if x != nil {
		return x.DebugExitOnInvariantViolation
	}
	return false
}

func (x *Config) GetDebugFuse() bool {
	if x != nil {
		return x.DebugFuse
	}
	return false
}

func (x *Config) GetDebugGcs() bool {
	if x != nil {
		return x.DebugGcs
	}
	return false
}

func (x *Config) GetDebugLogMutex() bool {
	if x != nil {
		return x.DebugLogMutex
	}
	return false
}

func (x *Config) GetDisableAutoconfig() bool {
	if x != nil {
		return x.DisableAutoconfig
	}
	return false
}

func (x *Config) GetDummyIoEnable() bool {
	if x != nil {
		return x.DummyIoEnable
	}
	return false
}

func (x *Config) GetDummyIoPerMbLatency() int64 {
	if x != nil {
		return x.DummyIoPerMbLatency
	}
	return 0
}

func (x *Config) GetDummyIoReaderLatency() int64 {
	if x != nil {
		return x.DummyIoReaderLatency
	}
	return 0
}

func (x *Config) GetEnableAtomicRenameObject() bool {
	if x != nil {
		return x.EnableAtomicRenameObject
	}
	return false
}

func (x *Config) GetEnableGoogleLibAuth() bool {
	if x != nil {
		return x.EnableGoogleLibAuth
	}
	return false
}

func (x *Config) GetEnableHns() bool {
	if x != nil {
		return x.EnableHns
	}
	return false
}

func (x *Config) GetEnableNewReader() bool {
	if x != nil {
		return x.EnableNewReader
	}
	return false
}

func (x *Config) GetEnableStandardSymlinks() bool {
	if x != nil {
		return x.EnableStandardSymlinks
	}
	return false
}

func (x *Config) GetEnableTypeCacheDeprecation() bool {
	if x != nil {
		return x.EnableTypeCacheDeprecation
	}
	return false
}

func (x *Config) GetEnableUnsupportedPathSupport() bool {
	if x != nil {
		return x.EnableUnsupportedPathSupport
	}
	return false
}

func (x *Config) GetFileCacheCacheFileForRangeRead() bool {
	if x != nil {
		return x.FileCacheCacheFileForRangeRead
	}
	return false
}

func (x *Config) GetFileCacheDownloadChunkSizeMb() int32 {
	if x != nil {
		return x.FileCacheDownloadChunkSizeMb
	}
	return 0
}

func (x *Config) GetFileCacheEnableCrc() bool {
	if x != nil {
		return x.FileCacheEnableCrc
	}
	return false
}

func (x *Config) GetFileCacheEnableExperimentalSharedChunkCache() bool {
	if x != nil {
		return x.FileCacheEnableExperimentalSharedChunkCache
	}
	return false
}

func (x *Config) GetFileCacheEnableODirect() bool {
	if x != nil {
		return x.FileCacheEnableODirect
	}
	return false
}

func (x *Config) GetFileCacheEnableParallelDownloads() bool {
	if x != nil {
		return x.FileCacheEnableParallelDownloads
	}
	return false
}

func (x *Config) GetIsFileCacheExcludeRegexSet() bool {
	if x != nil {
		return x.IsFileCacheExcludeRegexSet
	}
	return false
}

func (x *Config) GetFileCacheExperimentalDisableSizeCalculationFix() bool {
	if x != nil {
		return x.FileCacheExperimentalDisableSizeCalculationFix
	}
	return false
}

func (x *Config) GetFileCacheExperimentalEnableChunkCache() bool {
	if x != nil {
		return x.FileCacheExperimentalEnableChunkCache
	}
	return false
}

func (x *Config) GetFileCacheExperimentalParallelDownloadsDefaultOn() bool {
	if x != nil {
		return x.FileCacheExperimentalParallelDownloadsDefaultOn
	}
	return false
}

func (x *Config) GetIsFileCacheIncludeRegexSet() bool {
	if x != nil {
		return x.IsFileCacheIncludeRegexSet
	}
	return false
}

func (x *Config) GetFileCacheMaxParallelDownloads() int32 {
	if x != nil {
		return x.FileCacheMaxParallelDownloads
	}
	return 0
}

func (x *Config) GetFileCacheMaxSizeMb() int32 {
	if x != nil {
		return x.FileCacheMaxSizeMb
	}
	return 0
}

func (x *Config) GetFileCacheParallelDownloadsPerFile() int32 {
	if x != nil {
		return x.FileCacheParallelDownloadsPerFile
	}
	return 0
}

func (x *Config) GetFileCacheSharedCacheChunkSizeMb() int32 {
	if x != nil {
		return x.FileCacheSharedCacheChunkSizeMb
	}
	return 0
}

func (x *Config) GetFileCacheWriteBufferSize() int32 {
	if x != nil {
		return x.FileCacheWriteBufferSize
	}
	return 0
}

func (x *Config) GetFileSystemCongestionThreshold() int32 {
	if x != nil {
		return x.FileSystemCongestionThreshold
	}
	return 0
}

func (x *Config) GetFileSystemDirMode() int32 {
	if x != nil {
		return x.FileSystemDirMode
	}
	return 0
}

func (x *Config) GetFileSystemDisableParallelDirops() bool {
	if x != nil {
		return x.FileSystemDisableParallelDirops
	}
	return false
}

func (x *Config) GetFileSystemEnableKernelReader() bool {
	if x != nil {
		return x.FileSystemEnableKernelReader
	}
	return false
}

func (x *Config) GetFileSystemExperimentalEnableDentryCache() bool {
	if x != nil {
		return x.FileSystemExperimentalEnableDentryCache
	}
	return false
}

func (x *Config) GetFileSystemExperimentalEnablePirlo() bool {
	if x != nil {
		return x.FileSystemExperimentalEnablePirlo
	}
	return false
}

func (x *Config) GetFileSystemExperimentalEnableReaddirplus() bool {
	if x != nil {
		return x.FileSystemExperimentalEnableReaddirplus
	}
	return false
}

func (x *Config) GetFileSystemExperimentalODirect() bool {
	if x != nil {
		return x.FileSystemExperimentalODirect
	}
	return false
}

func (x *Config) GetFileSystemFileMode() int32 {
	if x != nil {
		return x.FileSystemFileMode
	}
	return 0
}

func (x *Config) GetFileSystemFuseMaxRequestSizeKb() int32 {
	if x != nil {
		return x.FileSystemFuseMaxRequestSizeKb
	}
	return 0
}

func (x *Config) GetFileSystemFuseMaxWriteSizeKb() int32 {
	if x != nil {
		return x.FileSystemFuseMaxWriteSizeKb
	}
	return 0
}

func (x *Config) GetIsFileSystemFuseOptionsSet() bool {
	if x != nil {
		return x.IsFileSystemFuseOptionsSet
	}
	return false
}

func (x *Config) GetFileSystemGid() int32 {
	if x != nil {
		return x.FileSystemGid
	}
	return 0
}

func (x *Config) GetFileSystemIgnoreInterrupts() bool {
	if x != nil {
		return x.FileSystemIgnoreInterrupts
	}
	return false
}

func (x *Config) GetFileSystemInactiveMrdCacheSize() int32 {
	if x != nil {
		return x.FileSystemInactiveMrdCacheSize
	}
	return 0
}

func (x *Config) GetFileSystemKernelListCacheTtlSecs() int32 {
	if x != nil {
		return x.FileSystemKernelListCacheTtlSecs
	}
	return 0
}

func (x *Config) GetIsFileSystemKernelParamsFileSet() bool {
	if x != nil {
		return x.IsFileSystemKernelParamsFileSet
	}
	return false
}

func (x *Config) GetFileSystemMaxBackground() int32 {
	if x != nil {
		return x.FileSystemMaxBackground
	}
	return 0
}

func (x *Config) GetFileSystemMaxReadAheadKb() int32 {
	if x != nil {
		return x.FileSystemMaxReadAheadKb
	}
	return 0
}

func (x *Config) GetFileSystemRenameDirLimit() int32 {
	if x != nil {
		return x.FileSystemRenameDirLimit
	}
	return 0
}

func (x *Config) GetFileSystemStrongConsistencyOnOpen() bool {
	if x != nil {
		return x.FileSystemStrongConsistencyOnOpen
	}
	return false
}

func (x *Config) GetIsFileSystemTempDirSet() bool {
	if x != nil {
		return x.IsFileSystemTempDirSet
	}
	return false
}

func (x *Config) GetFileSystemUid() int32 {
	if x != nil {
		return x.FileSystemUid
	}
	return 0
}

func (x *Config) GetForeground() bool {
	if x != nil {
		return x.Foreground
	}
	return false
}

func (x *Config) GetGcsAuthAnonymousAccess() bool {
	if x != nil {
		return x.GcsAuthAnonymousAccess
	}
	return false
}

func (x *Config) GetIsGcsAuthKeyFileSet() bool {
	if x != nil {
		return x.IsGcsAuthKeyFileSet
	}
	return false
}

func (x *Config) GetGcsAuthReuseTokenFromUrl() bool {
	if x != nil {
		return x.GcsAuthReuseTokenFromUrl
	}
	return false
}

func (x *Config) GetIsGcsAuthTokenUrlSet() bool {
	if x != nil {
		return x.IsGcsAuthTokenUrlSet
	}
	return false
}

func (x *Config) GetIsGcsConnectionBillingProjectSet() bool {
	if x != nil {
		return x.IsGcsConnectionBillingProjectSet
	}
	return false
}

func (x *Config) GetGcsConnectionClientProtocol() string {
	if x != nil {
		return x.GcsConnectionClientProtocol
	}
	return ""
}

func (x *Config) GetIsGcsConnectionCustomEndpointSet() bool {
	if x != nil {
		return x.IsGcsConnectionCustomEndpointSet
	}
	return false
}

func (x *Config) GetGcsConnectionEnableHttpDnsCache() bool {
	if x != nil {
		return x.GcsConnectionEnableHttpDnsCache
	}
	return false
}

func (x *Config) GetGcsConnectionExperimentalEnableJsonRead() bool {
	if x != nil {
		return x.GcsConnectionExperimentalEnableJsonRead
	}
	return false
}

func (x *Config) GetIsGcsConnectionExperimentalLocalSocketAddressSet() bool {
	if x != nil {
		return x.IsGcsConnectionExperimentalLocalSocketAddressSet
	}
	return false
}

func (x *Config) GetGcsConnectionGrpcConnPoolSize() int32 {
	if x != nil {
		return x.GcsConnectionGrpcConnPoolSize
	}
	return 0
}

func (x *Config) GetGcsConnectionGrpcPathStrategy() string {
	if x != nil {
		return x.GcsConnectionGrpcPathStrategy
	}
	return ""
}

func (x *Config) GetGcsConnectionHttpClientTimeout() int64 {
	if x != nil {
		return x.GcsConnectionHttpClientTimeout
	}
	return 0
}

func (x *Config) GetGcsConnectionLimitBytesPerSec() float64 {
	if x != nil {
		return x.GcsConnectionLimitBytesPerSec
	}
	return 0
}

func (x *Config) GetGcsConnectionLimitOpsPerSec() float64 {
	if x != nil {
		return x.GcsConnectionLimitOpsPerSec
	}
	return 0
}

func (x *Config) GetGcsConnectionMaxConnsPerHost() int32 {
	if x != nil {
		return x.GcsConnectionMaxConnsPerHost
	}
	return 0
}

func (x *Config) GetGcsConnectionMaxIdleConnsPerHost() int32 {
	if x != nil {
		return x.GcsConnectionMaxIdleConnsPerHost
	}
	return 0
}

func (x *Config) GetGcsConnectionSequentialReadSizeMb() int32 {
	if x != nil {
		return x.GcsConnectionSequentialReadSizeMb
	}
	return 0
}

func (x *Config) GetGcsRetriesChunkRetryDeadlineSecs() int32 {
	if x != nil {
		return x.GcsRetriesChunkRetryDeadlineSecs
	}
	return 0
}

func (x *Config) GetGcsRetriesChunkTransferTimeoutSecs() int32 {
	if x != nil {
		return x.GcsRetriesChunkTransferTimeoutSecs
	}
	return 0
}

func (x *Config) GetGcsRetriesEnableMountRetries() bool {
	if x != nil {
		return x.GcsRetriesEnableMountRetries
	}
	return false
}

func (x *Config) GetGcsRetriesMaxRetryAttempts() int32 {
	if x != nil {
		return x.GcsRetriesMaxRetryAttempts
	}
	return 0
}

func (x *Config) GetGcsRetriesMaxRetrySleep() int64 {
	if x != nil {
		return x.GcsRetriesMaxRetrySleep
	}
	return 0
}

func (x *Config) GetGcsRetriesMultiplier() float64 {
	if x != nil {
		return x.GcsRetriesMultiplier
	}
	return 0
}

func (x *Config) GetGcsRetriesReadStallEnable() bool {
	if x != nil {
		return x.GcsRetriesReadStallEnable
	}
	return false
}

func (x *Config) GetGcsRetriesReadStallInitialReqTimeout() int64 {
	if x != nil {
		return x.GcsRetriesReadStallInitialReqTimeout
	}
	return 0
}

func (x *Config) GetGcsRetriesReadStallMaxReqTimeout() int64 {
	if x != nil {
		return x.GcsRetriesReadStallMaxReqTimeout
	}
	return 0
}

func (x *Config) GetGcsRetriesReadStallMinReqTimeout() int64 {
	if x != nil {
		return x.GcsRetriesReadStallMinReqTimeout
	}
	return 0
}

func (x *Config) GetGcsRetriesReadStallReqIncreaseRate() float64 {
	if x != nil {
		return x.GcsRetriesReadStallReqIncreaseRate
	}
	return 0
}

func (x *Config) GetGcsRetriesReadStallReqTargetPercentile() float64 {
	if x != nil {
		return x.GcsRetriesReadStallReqTargetPercentile
	}
	return 0
}

func (x *Config) GetImplicitDirs() bool {
	if x != nil {
		return x.ImplicitDirs
	}
	return false
}

func (x *Config) GetListEnableEmptyManagedFolders() bool {
	if x != nil {
		return x.ListEnableEmptyManagedFolders
	}
	return false
}

func (x *Config) GetLoggingExperimentalEnableOtelLogging() bool {
	if x != nil {
		return x.LoggingExperimentalEnableOtelLogging
	}
	return false
}

func (x *Config) GetIsLoggingExperimentalOtelLoggingEndpointSet() bool {
	if x != nil {
		return x.IsLoggingExperimentalOtelLoggingEndpointSet
	}
	return false
}

func (x *Config) GetIsLoggingExperimentalOtelLoggingProjectIdSet() bool {
	if x != nil {
		return x.IsLoggingExperimentalOtelLoggingProjectIdSet
	}
	return false
}

func (x *Config) GetIsLoggingFilePathSet() bool {
	if x != nil {
		return x.IsLoggingFilePathSet
	}
	return false
}

func (x *Config) GetIsLoggingFormatSet() bool {
	if x != nil {
		return x.IsLoggingFormatSet
	}
	return false
}

func (x *Config) GetLoggingLogRotateBackupFileCount() int32 {
	if x != nil {
		return x.LoggingLogRotateBackupFileCount
	}
	return 0
}

func (x *Config) GetLoggingLogRotateCompress() bool {
	if x != nil {
		return x.LoggingLogRotateCompress
	}
	return false
}

func (x *Config) GetLoggingLogRotateMaxFileSizeMb() int32 {
	if x != nil {
		return x.LoggingLogRotateMaxFileSizeMb
	}
	return 0
}

func (x *Config) GetLoggingSeverity() string {
	if x != nil {
		return x.LoggingSeverity
	}
	return ""
}

func (x *Config) GetIsLoggingWireLogSet() bool {
	if x != nil {
		return x.IsLoggingWireLogSet
	}
	return false
}

func (x *Config) GetIsMachineTypeSet() bool {
	if x != nil {
		return x.IsMachineTypeSet
	}
	return false
}

func (x *Config) GetMetadataCacheDeprecatedStatCacheCapacity() int32 {
	if x != nil {
		return x.MetadataCacheDeprecatedStatCacheCapacity
	}
	return 0
}

func (x *Config) GetMetadataCacheDeprecatedStatCacheTtl() int64 {
	if x != nil {
		return x.MetadataCacheDeprecatedStatCacheTtl
	}
	return 0
}

func (x *Config) GetMetadataCacheDeprecatedTypeCacheTtl() int64 {
	if x != nil {
		return x.MetadataCacheDeprecatedTypeCacheTtl
	}
	return 0
}

func (x *Config) GetMetadataCacheEnableMetadataPrefetch() bool {
	if x != nil {
		return x.MetadataCacheEnableMetadataPrefetch
	}
	return false
}

func (x *Config) GetMetadataCacheEnableNonexistentTypeCache() bool {
	if x != nil {
		return x.MetadataCacheEnableNonexistentTypeCache
	}
	return false
}

func (x *Config) GetMetadataCacheExperimentalEnableOptimizedMetadataCache() bool {
	if x != nil {
		return x.MetadataCacheExperimentalEnableOptimizedMetadataCache
	}
	return false
}

func (x *Config) GetIsMetadataCacheExperimentalMetadataPrefetchOnMountSet() bool {
	if x != nil {
		return x.IsMetadataCacheExperimentalMetadataPrefetchOnMountSet
	}
	return false
}

func (x *Config) GetMetadataCacheMetadataPrefetchEntriesLimit() int32 {
	if x != nil {
		return x.MetadataCacheMetadataPrefetchEntriesLimit
	}
	return 0
}

func (x *Config) GetMetadataCacheMetadataPrefetchMaxWorkers() int32 {
	if x != nil {
		return x.MetadataCacheMetadataPrefetchMaxWorkers
	}
	return 0
}

func (x *Config) GetMetadataCacheNegativeTtlSecs() int32 {
	if x != nil {
		return x.MetadataCacheNegativeTtlSecs
	}
	return 0
}

func (x *Config) GetMetadataCacheStatCacheMaxSizeMb() int32 {
	if x != nil {
		return x.MetadataCacheStatCacheMaxSizeMb
	}
	return 0
}

func (x *Config) GetMetadataCacheTtlSecs() int32 {
	if x != nil {
		return x.MetadataCacheTtlSecs
	}
	return 0
}

func (x *Config) GetMetadataCacheTypeCacheMaxSizeMb() int32 {
	if x != nil {
		return x.MetadataCacheTypeCacheMaxSizeMb
	}
	return 0
}

func (x *Config) GetMetricsBufferSize() int32 {
	if x != nil {
		return x.MetricsBufferSize
	}
	return 0
}

func (x *Config) GetMetricsCloudMetricsExportIntervalSecs() int32 {
	if x != nil {
		return x.MetricsCloudMetricsExportIntervalSecs
	}
	return 0
}

func (x *Config) GetMetricsExperimentalEnableGrpcMetrics() bool {
	if x != nil {
		return x.MetricsExperimentalEnableGrpcMetrics
	}
	return false
}

func (x *Config) GetMetricsExperimentalEnableOtelMetrics() bool {
	if x != nil {
		return x.MetricsExperimentalEnableOtelMetrics
	}
	return false
}

func (x *Config) GetIsMetricsExperimentalOtelMetricsEndpointSet() bool {
	if x != nil {
		return x.IsMetricsExperimentalOtelMetricsEndpointSet
	}
	return false
}

func (x *Config) GetIsMetricsExperimentalOtelMetricsProjectIdSet() bool {
	if x != nil {
		return x.IsMetricsExperimentalOtelMetricsProjectIdSet
	}
	return false
}

func (x *Config) GetMetricsPrometheusPort() int32 {
	if x != nil {
		return x.MetricsPrometheusPort
	}
	return 0
}

func (x *Config) GetMetricsStackdriverExportInterval() int64 {
	if x != nil {
		return x.MetricsStackdriverExportInterval
	}
	return 0
}

func (x *Config) GetMetricsUseNewNames() bool {
	if x != nil {
		return x.MetricsUseNewNames
	}
	return false
}

func (x *Config) GetMetricsWorkers() int32 {
	if x != nil {
		return x.MetricsWorkers
	}
	return 0
}

func (x *Config) GetIsMountIdSet() bool {
	if x != nil {
		return x.IsMountIdSet
	}
	return false
}

func (x *Config) GetMrdPoolSize() int32 {
	if x != nil {
		return x.MrdPoolSize
	}
	return 0
}

func (x *Config) GetIsOnlyDirSet() bool {
	if x != nil {
		return x.IsOnlyDirSet
	}
	return false
}

func (x *Config) GetIsProfileSet() bool {
	if x != nil {
		return x.IsProfileSet
	}
	return false
}

func (x *Config) GetReadBlockSizeMb() int32 {
	if x != nil {
		return x.ReadBlockSizeMb
	}
	return 0
}

func (x *Config) GetReadEnableBufferedRead() bool {
	if x != nil {
		return x.ReadEnableBufferedRead
	}
	return false
}

func (x *Config) GetReadEnableGrpcReadChecksums() bool {
	if x != nil {
		return x.ReadEnableGrpcReadChecksums
	}
	return false
}

func (x *Config) GetReadGlobalMaxBlocks() int32 {
	if x != nil {
		return x.ReadGlobalMaxBlocks
	}
	return 0
}

func (x *Config) GetReadInactiveStreamTimeout() int64 {
	if x != nil {
		return x.ReadInactiveStreamTimeout
	}
	return 0
}

func (x *Config) GetReadMaxBlocksPerHandle() int32 {
	if x != nil {
		return x.ReadMaxBlocksPerHandle
	}
	return 0
}

func (x *Config) GetReadMinBlocksPerHandle() int32 {
	if x != nil {
		return x.ReadMinBlocksPerHandle
	}
	return 0
}

func (x *Config) GetReadRandomSeekThreshold() int32 {
	if x != nil {
		return x.ReadRandomSeekThreshold
	}
	return 0
}

func (x *Config) GetReadStartBlocksPerHandle() int32 {
	if x != nil {
		return x.ReadStartBlocksPerHandle
	}
	return 0
}

func (x *Config) GetIsTraceExportersSet() bool {
	if x != nil {
		return x.IsTraceExportersSet
	}
	return false
}

func (x *Config) GetIsTraceProjectIdSet() bool {
	if x != nil {
		return x.IsTraceProjectIdSet
	}
	return false
}

func (x *Config) GetTraceSamplingRatio() float64 {
	if x != nil {
		return x.TraceSamplingRatio
	}
	return 0
}

func (x *Config) GetWorkloadInsightForwardMergeThresholdMb() int32 {
	if x != nil {
		return x.WorkloadInsightForwardMergeThresholdMb
	}
	return 0
}

func (x *Config) GetIsWorkloadInsightOutputFileSet() bool {
	if x != nil {
		return x.IsWorkloadInsightOutputFileSet
	}
	return false
}

func (x *Config) GetWorkloadInsightVisualize() bool {
	if x != nil {
		return x.WorkloadInsightVisualize
	}
	return false
}

func (x *Config) GetWriteBlockSizeMb() float64 {
	if x != nil {
		return x.WriteBlockSizeMb
	}
	return 0
}

func (x *Config) GetWriteCreateEmptyFile() bool {
	if x != nil {
		return x.WriteCreateEmptyFile
	}
	return false
}

func (x *Config) GetWriteEnableRapidAppends() bool {
	if x != nil {
		return x.WriteEnableRapidAppends
	}
	return false
}

func (x *Config) GetWriteEnableRapidWrites() bool {
	if x != nil {
		return x.WriteEnableRapidWrites
	}
	return false
}

func (x *Config) GetWriteEnableStreamingWrites() bool {
	if x != nil {
		return x.WriteEnableStreamingWrites
	}
	return false
}

func (x *Config) GetWriteFinalizeFileForRapid() bool {
	if x != nil {
		return x.WriteFinalizeFileForRapid
	}
	return false
}

func (x *Config) GetWriteGlobalMaxBlocks() int32 {
	if x != nil {
		return x.WriteGlobalMaxBlocks
	}
	return 0
}

func (x *Config) GetWriteMaxBlocksPerFile() int32 {
	if x != nil {
		return x.WriteMaxBlocksPerFile
	}
	return 0
}

var File_cfg_config_proto protoreflect.FileDescriptor

const file_cfg_config_proto_rawDesc = "" +
	"\n" +
	"\x10cfg/config.proto\x12\x0egcsfuse.cfg.v1\"\xfdT\n" +
	"\x06Config\x12%\n" +
	"\x0fis_app_name_set\x18\x01 \x01(\bR\fisAppNameSet\x12'\n" +
	"\x10is_cache_dir_set\x18\x02 \x01(\bR\risCacheDirSet\x12A\n" +
	"\x1dcloud_profiler_allocated_heap\x18\x03 \x01(\bR\x1acloudProfilerAllocatedHeap\x12,\n" +
	"\x12cloud_profiler_cpu\x18\x04 \x01(\bR\x10cloudProfilerCpu\x124\n" +
	"\x16cloud_profiler_enabled\x18\x05 \x01(\bR\x14cloudProfilerEnabled\x12:\n" +
	"\x19cloud_profiler_goroutines\x18\x06 \x01(\bR\x17cloudProfilerGoroutines\x12.\n" +
	"\x13cloud_profiler_heap\x18\a \x01(\bR\x11cloudProfilerHeap\x12<\n" +
	"\x1bis_cloud_profiler_label_set\x18\b \x01(\bR\x17isCloudProfilerLabelSet\x120\n" +
	"\x14cloud_profiler_mutex\x18\t \x01(\bR\x12cloudProfilerMutex\x12I\n" +
	"\"is_cloud_profiler_service_name_set\x18\n" +
	" \x01(\bR\x1disCloudProfilerServiceNameSet\x12H\n" +
	"!debug_exit_on_invariant_violation\x18\v \x01(\bR\x1ddebugExitOnInvariantViolation\x12\x1d\n" +
	"\n" +
	"debug_fuse\x18\f \x01(\bR\tdebugFuse\x12\x1b\n" +
	"\tdebug_gcs\x18\r \x01(\bR\bdebugGcs\x12&\n" +
	"\x0fdebug_log_mutex\x18\x0e \x01(\bR\rdebugLogMutex\x12-\n" +
	"\x12disable_autoconfig\x18\x0f \x01(\bR\x11disableAutoconfig\x12&\n" +
	"\x0fdummy_io_enable\x18\x10 \x01(\bR\rdummyIoEnable\x124\n" +
	"\x17dummy_io_per_mb_latency\x18\x11 \x01(\x03R\x13dummyIoPerMbLatency\x125\n" +
	"\x17dummy_io_reader_latency\x18\x12 \x01(\x03R\x14dummyIoReaderLatency\x12=\n" +
	"\x1benable_atomic_rename_object\x18\x13 \x01(\bR\x18enableAtomicRenameObject\x123\n" +
	"\x16enable_google_lib_auth\x18\x14 \x01(\bR\x13enableGoogleLibAuth\x12\x1d\n" +
	"\n" +
	"enable_hns\x18\x15 \x01(\bR\tenableHns\x12*\n" +
	"\x11enable_new_reader\x18\x16 \x01(\bR\x0fenableNewReader\x128\n" +
	"\x18enable_standard_symlinks\x18\x17 \x01(\bR\x16enableStandardSymlinks\x12A\n" +
	"\x1denable_type_cache_deprecation\x18\x18 \x01(\bR\x1aenableTypeCacheDeprecation\x12E\n" +
	"\x1fenable_unsupported_path_support\x18\x19 \x01(\bR\x1cenableUnsupportedPathSupport\x12L\n" +
	"$file_cache_cache_file_for_range_read\x18\x1a \x01(\bR\x1efileCacheCacheFileForRangeRead\x12G\n" +
	"!file_cache_download_chunk_size_mb\x18\x1b \x01(\x05R\x1cfileCacheDownloadChunkSizeMb\x121\n" +
	"\x15file_cache_enable_crc\x18\x1c \x01(\bR\x12fileCacheEnableCrc\x12f\n" +
	"1file_cache_enable_experimental_shared_chunk_cache\x18\x1d \x01(\bR+fileCacheEnableExperimentalSharedChunkCache\x12:\n" +
	"\x1afile_cache_enable_o_direct\x18\x1e \x01(\bR\x16fileCacheEnableODirect\x12N\n" +
	"$file_cache_enable_parallel_downloads\x18\x1f \x01(\bR fileCacheEnableParallelDownloads\x12C\n" +
	"\x1fis_file_cache_exclude_regex_set\x18  \x01(\bR\x1aisFileCacheExcludeRegexSet\x12l\n" +
	"4file_cache_experimental_disable_size_calculation_fix\x18! \x01(\bR.fileCacheExperimentalDisableSizeCalculationFix\x12Y\n" +
	"*file_cache_experimental_enable_chunk_cache\x18\" \x01(\bR%fileCacheExperimentalEnableChunkCache\x12n\n" +
	"5file_cache_experimental_parallel_downloads_default_on\x18# \x01(\bR/fileCacheExperimentalParallelDownloadsDefaultOn\x12C\n" +
	"\x1fis_file_cache_include_regex_set\x18$ \x01(\bR\x1aisFileCacheIncludeRegexSet\x12H\n" +
	"!file_cache_max_parallel_downloads\x18% \x01(\x05R\x1dfileCacheMaxParallelDownloads\x122\n" +
	"\x16file_cache_max_size_mb\x18& \x01(\x05R\x12fileCacheMaxSizeMb\x12Q\n" +
	"&file_cache_parallel_downloads_per_file\x18' \x01(\x05R!fileCacheParallelDownloadsPerFile\x12N\n" +
	"%file_cache_shared_cache_chunk_size_mb\x18( \x01(\x05R\x1ffileCacheSharedCacheChunkSizeMb\x12>\n" +
	"\x1cfile_cache_write_buffer_size\x18) \x01(\x05R\x18fileCacheWriteBufferSize\x12G\n" +
	" file_system_congestion_threshold\x18* \x01(\x05R\x1dfileSystemCongestionThreshold\x12/\n" +
	"\x14file_system_dir_mode\x18+ \x01(\x05R\x11fileSystemDirMode\x12L\n" +
	"#file_system_disable_parallel_dirops\x18, \x01(\bR\x1ffileSystemDisableParallelDirops\x12F\n" +
	" file_system_enable_kernel_reader\x18- \x01(\bR\x1cfileSystemEnableKernelReader\x12]\n" +
	",file_system_experimental_enable_dentry_cache\x18. \x01(\bR'fileSystemExperimentalEnableDentryCache\x12P\n" +
	"%file_system_experimental_enable_pirlo\x18/ \x01(\bR!fileSystemExperimentalEnablePirlo\x12\\\n" +
	"+file_system_experimental_enable_readdirplus\x180 \x01(\bR'fileSystemExperimentalEnableReaddirplus\x12H\n" +
	"!file_system_experimental_o_direct\x181 \x01(\bR\x1dfileSystemExperimentalODirect\x121\n" +
	"\x15file_system_file_mode\x182 \x01(\x05R\x12fileSystemFileMode\x12L\n" +
	"$file_system_fuse_max_request_size_kb\x183 \x01(\x05R\x1efileSystemFuseMaxRequestSizeKb\x12H\n" +
	"\"file_system_fuse_max_write_size_kb\x184 \x01(\x05R\x1cfileSystemFuseMaxWriteSizeKb\x12C\n" +
	"\x1fis_file_system_fuse_options_set\x185 \x01(\bR\x1aisFileSystemFuseOptionsSet\x12&\n" +
	"\x0ffile_system_gid\x186 \x01(\x05R\rfileSystemGid\x12A\n" +
	"\x1dfile_system_ignore_interrupts\x187 \x01(\bR\x1afileSystemIgnoreInterrupts\x12K\n" +
	"#file_system_inactive_mrd_cache_size\x188 \x01(\x05R\x1efileSystemInactiveMrdCacheSize\x12P\n" +
	"&file_system_kernel_list_cache_ttl_secs\x189 \x01(\x05R fileSystemKernelListCacheTtlSecs\x12N\n" +
	"%is_file_system_kernel_params_file_set\x18: \x01(\bR\x1fisFileSystemKernelParamsFileSet\x12;\n" +
	"\x1afile_system_max_background\x18; \x01(\x05R\x17fileSystemMaxBackground\x12?\n" +
	"\x1dfile_system_max_read_ahead_kb\x18< \x01(\x05R\x18fileSystemMaxReadAheadKb\x12>\n" +
	"\x1cfile_system_rename_dir_limit\x18= \x01(\x05R\x18fileSystemRenameDirLimit\x12Q\n" +
	"&file_system_strong_consistency_on_open\x18> \x01(\bR!fileSystemStrongConsistencyOnOpen\x12;\n" +
	"\x1bis_file_system_temp_dir_set\x18? \x01(\bR\x16isFileSystemTempDirSet\x12&\n" +
	"\x0ffile_system_uid\x18@ \x01(\x05R\rfileSystemUid\x12\x1e\n" +
	"\n" +
	"foreground\x18A \x01(\bR\n" +
	"foreground\x129\n" +
	"\x19gcs_auth_anonymous_access\x18B \x01(\bR\x16gcsAuthAnonymousAccess\x125\n" +
	"\x18is_gcs_auth_key_file_set\x18C \x01(\bR\x13isGcsAuthKeyFileSet\x12?\n" +
	"\x1dgcs_auth_reuse_token_from_url\x18D \x01(\bR\x18gcsAuthReuseTokenFromUrl\x127\n" +
	"\x19is_gcs_auth_token_url_set\x18E \x01(\bR\x14isGcsAuthTokenUrlSet\x12O\n" +
	"%is_gcs_connection_billing_project_set\x18F \x01(\bR isGcsConnectionBillingProjectSet\x12C\n" +
	"\x1egcs_connection_client_protocol\x18G \x01(\tR\x1bgcsConnectionClientProtocol\x12O\n" +
	"%is_gcs_connection_custom_endpoint_set\x18H \x01(\bR isGcsConnectionCustomEndpointSet\x12M\n" +
	"$gcs_connection_enable_http_dns_cache\x18I \x01(\bR\x1fgcsConnectionEnableHttpDnsCache\x12]\n" +
	",gcs_connection_experimental_enable_json_read\x18J \x01(\bR'gcsConnectionExperimentalEnableJsonRead\x12q\n" +
	"7is_gcs_connection_experimental_local_socket_address_set\x18K \x01(\bR0isGcsConnectionExperimentalLocalSocketAddressSet\x12I\n" +
	"\"gcs_connection_grpc_conn_pool_size\x18L \x01(\x05R\x1dgcsConnectionGrpcConnPoolSize\x12H\n" +
	"!gcs_connection_grpc_path_strategy\x18M \x01(\tR\x1dgcsConnectionGrpcPathStrategy\x12J\n" +
	"\"gcs_connection_http_client_timeout\x18N \x01(\x03R\x1egcsConnectionHttpClientTimeout\x12I\n" +
	"\"gcs_connection_limit_bytes_per_sec\x18O \x01(\x01R\x1dgcsConnectionLimitBytesPerSec\x12E\n" +
	" gcs_connection_limit_ops_per_sec\x18P \x01(\x01R\x1bgcsConnectionLimitOpsPerSec\x12G\n" +
	"!gcs_connection_max_conns_per_host\x18Q \x01(\x05R\x1cgcsConnectionMaxConnsPerHost\x12P\n" +
	"&gcs_connection_max_idle_conns_per_host\x18R \x01(\x05R gcsConnectionMaxIdleConnsPerHost\x12Q\n" +
	"&gcs_connection_sequential_read_size_mb\x18S \x01(\x05R!gcsConnectionSequentialReadSizeMb\x12O\n" +
	"%gcs_retries_chunk_retry_deadline_secs\x18T \x01(\x05R gcsRetriesChunkRetryDeadlineSecs\x12S\n" +
	"'gcs_retries_chunk_transfer_timeout_secs\x18U \x01(\x05R\"gcsRetriesChunkTransferTimeoutSecs\x12F\n" +
	" gcs_retries_enable_mount_retries\x18V \x01(\bR\x1cgcsRetriesEnableMountRetries\x12B\n" +
	"\x1egcs_retries_max_retry_attempts\x18W \x01(\x05R\x1agcsRetriesMaxRetryAttempts\x12<\n" +
	"\x1bgcs_retries_max_retry_sleep\x18X \x01(\x03R\x17gcsRetriesMaxRetrySleep\x124\n" +
	"\x16gcs_retries_multiplier\x18Y \x01(\x01R\x14gcsRetriesMultiplier\x12@\n" +
	"\x1dgcs_retries_read_stall_enable\x18Z \x01(\bR\x19gcsRetriesReadStallEnable\x12X\n" +
	"*gcs_retries_read_stall_initial_req_timeout\x18[ \x01(\x03R$gcsRetriesReadStallInitialReqTimeout\x12P\n" +
	"&gcs_retries_read_stall_max_req_timeout\x18\\ \x01(\x03R gcsRetriesReadStallMaxReqTimeout\x12P\n" +
	"&gcs_retries_read_stall_min_req_timeout\x18] \x01(\x03R gcsRetriesReadStallMinReqTimeout\x12T\n" +
	"(gcs_retries_read_stall_req_increase_rate\x18^ \x01(\x01R\"gcsRetriesReadStallReqIncreaseRate\x12\\\n" +
	",gcs_retries_read_stall_req_target_percentile\x18_ \x01(\x01R&gcsRetriesReadStallReqTargetPercentile\x12#\n" +
	"\rimplicit_dirs\x18` \x01(\bR\fimplicitDirs\x12H\n" +
	"!list_enable_empty_managed_folders\x18a \x01(\bR\x1dlistEnableEmptyManagedFolders\x12V\n" +
	"(logging_experimental_enable_otel_logging\x18b \x01(\bR$loggingExperimentalEnableOtelLogging\x12f\n" +
	"1is_logging_experimental_otel_logging_endpoint_set\x18c \x01(\bR+isLoggingExperimentalOtelLoggingEndpointSet\x12i\n" +
	"3is_logging_experimental_otel_logging_project_id_set\x18d \x01(\bR,isLoggingExperimentalOtelLoggingProjectIdSet\x126\n" +
	"\x18is_logging_file_path_set\x18e \x01(\bR\x14isLoggingFilePathSet\x121\n" +
	"\x15is_logging_format_set\x18f \x01(\bR\x12isLoggingFormatSet\x12M\n" +
	"$logging_log_rotate_backup_file_count\x18g \x01(\x05R\x1floggingLogRotateBackupFileCount\x12=\n" +
	"\x1blogging_log_rotate_compress\x18h \x01(\bR\x18loggingLogRotateCompress\x12J\n" +
	"#logging_log_rotate_max_file_size_mb\x18i \x01(\x05R\x1dloggingLogRotateMaxFileSizeMb\x12)\n" +
	"\x10logging_severity\x18j \x01(\tR\x0floggingSeverity\x124\n" +
	"\x17is_logging_wire_log_set\x18k \x01(\bR\x13isLoggingWireLogSet\x12-\n" +
	"\x13is_machine_type_set\x18l \x01(\bR\x10isMachineTypeSet\x12_\n" +
	"-metadata_cache_deprecated_stat_cache_capacity\x18m \x01(\x05R(metadataCacheDeprecatedStatCacheCapacity\x12U\n" +
	"(metadata_cache_deprecated_stat_cache_ttl\x18n \x01(\x03R#metadataCacheDeprecatedStatCacheTtl\x12U\n" +
	"(metadata_cache_deprecated_type_cache_ttl\x18o \x01(\x03R#metadataCacheDeprecatedTypeCacheTtl\x12T\n" +
	"'metadata_cache_enable_metadata_prefetch\x18p \x01(\bR#metadataCacheEnableMetadataPrefetch\x12]\n" +
	",metadata_cache_enable_nonexistent_type_cache\x18q \x01(\bR'metadataCacheEnableNonexistentTypeCache\x12z\n" +
	";metadata_cache_experimental_enable_optimized_metadata_cache\x18r \x01(\bR5metadataCacheExperimentalEnableOptimizedMetadataCache\x12|\n" +
	"=is_metadata_cache_experimental_metadata_prefetch_on_mount_set\x18s \x01(\bR5isMetadataCacheExperimentalMetadataPrefetchOnMountSet\x12a\n" +
	".metadata_cache_metadata_prefetch_entries_limit\x18t \x01(\x05R)metadataCacheMetadataPrefetchEntriesLimit\x12]\n" +
	",metadata_cache_metadata_prefetch_max_workers\x18u \x01(\x05R'metadataCacheMetadataPrefetchMaxWorkers\x12F\n" +
	" metadata_cache_negative_ttl_secs\x18v \x01(\x05R\x1cmetadataCacheNegativeTtlSecs\x12N\n" +
	"%metadata_cache_stat_cache_max_size_mb\x18w \x01(\x05R\x1fmetadataCacheStatCacheMaxSizeMb\x125\n" +
	"\x17metadata_cache_ttl_secs\x18x \x01(\x05R\x14metadataCacheTtlSecs\x12N\n" +
	"%metadata_cache_type_cache_max_size_mb\x18y \x01(\x05R\x1fmetadataCacheTypeCacheMaxSizeMb\x12.\n" +
	"\x13metrics_buffer_size\x18z \x01(\x05R\x11metricsBufferSize\x12Y\n" +
	"*metrics_cloud_metrics_export_interval_secs\x18{ \x01(\x05R%metricsCloudMetricsExportIntervalSecs\x12V\n" +
	"(metrics_experimental_enable_grpc_metrics\x18| \x01(\bR$metricsExperimentalEnableGrpcMetrics\x12V\n" +
	"(metrics_experimental_enable_otel_metrics\x18} \x01(\bR$metricsExperimentalEnableOtelMetrics\x12f\n" +
	"1is_metrics_experimental_otel_metrics_endpoint_set\x18~ \x01(\bR+isMetricsExperimentalOtelMetricsEndpointSet\x12i\n" +
	"3is_metrics_experimental_otel_metrics_project_id_set\x18\x7f \x01(\bR,isMetricsExperimentalOtelMetricsProjectIdSet\x127\n" +
	"\x17metrics_prometheus_port\x18\x80\x01 \x01(\x05R\x15metricsPrometheusPort\x12N\n" +
	"#metrics_stackdriver_export_interval\x18\x81\x01 \x01(\x03R metricsStackdriverExportInterval\x122\n" +
	"\x15metrics_use_new_names\x18\x82\x01 \x01(\bR\x12metricsUseNewNames\x12(\n" +
	"\x0fmetrics_workers\x18\x83\x01 \x01(\x05R\x0emetricsWorkers\x12&\n" +
	"\x0fis_mount_id_set\x18\x84\x01 \x01(\bR\fisMountIdSet\x12#\n" +
	"\rmrd_pool_size\x18\x85\x01 \x01(\x05R\vmrdPoolSize\x12&\n" +
	"\x0fis_only_dir_set\x18\x86\x01 \x01(\bR\fisOnlyDirSet\x12%\n" +
	"\x0eis_profile_set\x18\x87\x01 \x01(\bR\fisProfileSet\x12,\n" +
	"\x12read_block_size_mb\x18\x88\x01 \x01(\x05R\x0freadBlockSizeMb\x12:\n" +
	"\x19read_enable_buffered_read\x18\x89\x01 \x01(\bR\x16readEnableBufferedRead\x12E\n" +
	"\x1fread_enable_grpc_read_checksums\x18\x8a\x01 \x01(\bR\x1breadEnableGrpcReadChecksums\x124\n" +
	"\x16read_global_max_blocks\x18\x8b\x01 \x01(\x05R\x13readGlobalMaxBlocks\x12@\n" +
	"\x1cread_inactive_stream_timeout\x18\x8c\x01 \x01(\x03R\x19readInactiveStreamTimeout\x12;\n" +
	"\x1aread_max_blocks_per_handle\x18\x8d\x01 \x01(\x05R\x16readMaxBlocksPerHandle\x12;\n" +
	"\x1aread_min_blocks_per_handle\x18\x8e\x01 \x01(\x05R\x16readMinBlocksPerHandle\x12<\n" +
	"\x1aread_random_seek_threshold\x18\x8f\x01 \x01(\x05R\x17readRandomSeekThreshold\x12?\n" +
	"\x1cread_start_blocks_per_handle\x18\x90\x01 \x01(\x05R\x18readStartBlocksPerHandle\x124\n" +
	"\x16is_trace_exporters_set\x18\x91\x01 \x01(\bR\x13isTraceExportersSet\x125\n" +
	"\x17is_trace_project_id_set\x18\x92\x01 \x01(\bR\x13isTraceProjectIdSet\x121\n" +
	"\x14trace_sampling_ratio\x18\x93\x01 \x01(\x01R\x12traceSamplingRatio\x12\\\n" +
	"+workload_insight_forward_merge_threshold_mb\x18\x94\x01 \x01(\x05R&workloadInsightForwardMergeThresholdMb\x12L\n" +
	"#is_workload_insight_output_file_set\x18\x95\x01 \x01(\bR\x1eisWorkloadInsightOutputFileSet\x12=\n" +
	"\x1aworkload_insight_visualize\x18\x96\x01 \x01(\bR\x18workloadInsightVisualize\x12.\n" +
	"\x13write_block_size_mb\x18\x97\x01 \x01(\x01R\x10writeBlockSizeMb\x126\n" +
	"\x17write_create_empty_file\x18\x98\x01 \x01(\bR\x14writeCreateEmptyFile\x12<\n" +
	"\x1awrite_enable_rapid_appends\x18\x99\x01 \x01(\bR\x17writeEnableRapidAppends\x12:\n" +
	"\x19write_enable_rapid_writes\x18\x9a\x01 \x01(\bR\x16writeEnableRapidWrites\x12B\n" +
	"\x1dwrite_enable_streaming_writes\x18\x9b\x01 \x01(\bR\x1awriteEnableStreamingWrites\x12A\n" +
	"\x1dwrite_finalize_file_for_rapid\x18\x9c\x01 \x01(\bR\x19writeFinalizeFileForRapid\x126\n" +
	"\x17write_global_max_blocks\x18\x9d\x01 \x01(\x05R\x14writeGlobalMaxBlocks\x129\n" +
	"\x19write_max_blocks_per_file\x18\x9e\x01 \x01(\x05R\x15writeMaxBlocksPerFileB2Z0github.com/googlecloudplatform/gcsfuse/v3/cfg/pbb\x06proto3"

var (
	file_cfg_config_proto_rawDescOnce sync.Once
	file_cfg_config_proto_rawDescData []byte
)

func file_cfg_config_proto_rawDescGZIP() []byte {
	file_cfg_config_proto_rawDescOnce.Do(func() {
		file_cfg_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cfg_config_proto_rawDesc), len(file_cfg_config_proto_rawDesc)))
	})
	return file_cfg_config_proto_rawDescData
}

var file_cfg_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cfg_config_proto_goTypes = []any{
	(*Config)(nil), // 0: gcsfuse.cfg.v1.Config
}
var file_cfg_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cfg_config_proto_init() }
func file_cfg_config_proto_init() {
	if File_cfg_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cfg_config_proto_rawDesc), len(file_cfg_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cfg_config_proto_goTypes,
		DependencyIndexes: file_cfg_config_proto_depIdxs,
		MessageInfos:      file_cfg_config_proto_msgTypes,
	}.Build()
	File_cfg_config_proto = out.File
	file_cfg_config_proto_goTypes = nil
	file_cfg_config_proto_depIdxs = nil
}
