#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Script Usage Documentation
usage() {
  echo "Usage: $0 [options]"
  echo "Options:"
  echo "    --bucket-location             <location>     Google Cloud Storage bucket location (e.g, 'us-central1') (Defaults to VM region if not provided)."
  echo "    --project-id                  <project-id>   Google Cloud Project ID in which the bucket should be created. (e.g., 'gcs-fuse-test')"
  echo "                                                 (Defaults to VM project if not provided or gcs-fuse-test if running on cloudtop)."
  echo "    --test-installed-package                     Test installed gcsfuse package. (Default: false)"
  echo "    --install-package-from-path   <path>         Google Cloud Storage bucket path for GCSFuse package for testing (e.g. gs://<bucket-name>/my-gcsfuse-package.rpm)"
  echo "                                                 This option is mutually exclusive with --test-installed-package. (Default: "")"
  echo "    --skip-non-essential-tests                   Skip non-essential tests inside packages. (Default: false)"
  echo "    --test-on-tpc-endpoint                       Run tests on TPC endpoint. (Default: false)"
  echo "    --presubmit                                  Run tests with presubmit flag. (Default: false)"
  echo "    --zonal                                      Run tests with zonal bucket in --bucket-location region."
  echo "                                                 The placement for Zonal buckets by deafault is Zone A of --bucket-location. (Default: false)"
  echo "    --no-build-binary-in-script                  To disable building gcsfuse binary in script. (Default: false)"
  echo "    --package-level-parallelism   <parallelism>  To adjust the number of packages to execute in parallel. (Default: 10)"
  echo "    --track-resource-usage                       To track resource(cpu/mem/disk) usage during e2e run. (Default: false)"
  echo "    --output-dir                  <output-dir>   Directory in which all of log files generated by this script will be stored. (Default: /tmp)"
  echo "    --help                                       Display this help and exit."
  exit "$1"
}

# Logging Helpers
log_info() {
  echo "[INFO] $(date +"%Y-%m-%d %H:%M:%S"): $1"
}

log_error() {
  echo "[ERROR] $(date +"%Y-%m-%d %H:%M:%S"): $1"
}

# Check or install bash version before continuing script.
readonly REQUIRED_BASH_MAJOR=5
readonly REQUIRED_BASH_MINOR=1
readonly BASH_INSTALL_VERSION="5.3"
readonly BASH_INSTALLATION_PATH="/usr/local/bin/bash" # Using 5.3 for installation as bash 5.1 has an installation bug.

if (( BASH_VERSINFO[0] < REQUIRED_BASH_MAJOR || ( BASH_VERSINFO[0] == REQUIRED_BASH_MAJOR && BASH_VERSINFO[1] < REQUIRED_BASH_MINOR ) )); then
  log_info "Current Bash version (${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}) is older than required (${REQUIRED_BASH_MAJOR}.${REQUIRED_BASH_MINOR})."
  log_info "Installing Bash ${BASH_INSTALL_VERSION}..."

  # Dynamically find the repo root so we can locate the install script safely
  SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
  REPO_ROOT=$(realpath "${SCRIPT_DIR}/../..")

  # Run the installation script
  "${REPO_ROOT}/perfmetrics/scripts/install_bash.sh" "${BASH_INSTALL_VERSION}"
  if [[ ! -x "${BASH_INSTALLATION_PATH}" ]]; then
    log_error "Failed to locate the newly installed bash at ${BASH_INSTALLATION_PATH}"
    exit 1
  fi

  log_info "Re-executing the e2e script using the newly installed Bash ${BASH_INSTALL_VERSION}..."
  # The 'exec' command completely replaces the current old-bash process 
  # with the new bash process, passing along the script name ($0) and all arguments ($@).
  exec "${BASH_INSTALLATION_PATH}" "$0" "$@"
fi
log_info "Bash version: ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}"

# Constants
readonly GO_VERSION=$(cat .go-version)
readonly TPCZERO_PROJECT_ID="tpczero-system:gcsfuse-test-project"
readonly TPC_BUCKET_LOCATION="u-us-prp1"
readonly BUCKET_PREFIX="gcsfuse-e2e"
readonly INTEGRATION_TEST_PACKAGE_DIR="./tools/integration_tests"
readonly INTEGRATION_TEST_PACKAGE_TIMEOUT_IN_MINS=90 
readonly TMP_PREFIX="gcsfuse_e2e"
readonly ZONAL_BUCKET_SUPPORTED_LOCATIONS=("us-central1" "us-west4")
# e2e buckets created are retained for upto 10 days before deletion.
readonly BUCKET_RETENTION_PERIOD_DAYS=10
# 6 second delay between creating buckets as both hns and flat runs create buckets in parallel.
# Ref: https://cloud.google.com/storage/quotas#buckets
readonly DELAY_BETWEEN_BUCKET_CREATION=6 
readonly ZONAL="zonal"
readonly FLAT="flat"
readonly HNS="hns"
readonly SUCCESS_DIR_NAME="success_package_logs"
readonly FAILED_DIR_NAME="failed_package_logs"

# Extract GCE VM Project and Location.
ZONE=$(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/zone)
ZONE_NAME=$(basename "$ZONE")
GCE_VM_LOCATION="${ZONE_NAME%-*}"
GCE_VM_PROJECT_ID=$(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/project/project-id)
log_info "Project ID from GCE VM: '$GCE_VM_PROJECT_ID'"
log_info "Location from GCE VM: '$GCE_VM_LOCATION'"
log_info "Running e2e script as '$(whoami)'"
log_info "Current directory is '$(pwd)'"
# If HOME is not set, find it dynamically and export it
if [ -z "$HOME" ]; then
    export HOME=$(getent passwd "$(whoami)" | cut -d: -f6)
fi
log_info "HOME is set to '$HOME'"

# This variable will store the path if the script builds GCSFuse binaries (gcsfuse, mount.gcsfuse)
BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR=""

# Output directory where all artifacts generated by this script will be stored.
OUTPUT_DIR=""

KOKORO_DIR_AVAILABLE=false
if [[ -n "$KOKORO_ARTIFACTS_DIR" ]]; then
  KOKORO_DIR_AVAILABLE=true
fi

# Argument Parsing and Assignments
# Set default values for optional arguments
SKIP_NON_ESSENTIAL_TESTS_ON_PACKAGE=false
TEST_INSTALLED_PACKAGE=false
BUCKET_LOCATION=""
PROJECT_ID=""
INSTALL_PACKAGE_FROM_PATH=""
RUN_TEST_ON_TPC_ENDPOINT=false
RUN_TESTS_WITH_PRESUBMIT_FLAG=false
RUN_TESTS_WITH_ZONAL_BUCKET=false
BUILD_BINARY_IN_SCRIPT=true
TRACK_RESOURCE_USAGE=false
PACKAGE_LEVEL_PARALLELISM=10 # Controls how many test packages are run in parallel for hns, flat or zonal buckets.

# Define options for getopt
# A long option name followed by a colon indicates it requires an argument.
LONG=bucket-location:,project-id:,test-installed-package,install-package-from-path:,skip-non-essential-tests,no-build-binary-in-script,test-on-tpc-endpoint,presubmit,zonal,package-level-parallelism:,track-resource-usage,output-dir:,help

# Parse the options using getopt
# --options "" specifies that there are no short options.
PARSED=$(getopt --options "" --longoptions "$LONG" --name "$0" -- "$@")
if [[ $? -ne 0 ]]; then
    # getopt will have already printed an error message
    usage 1
fi

# Read the parsed options back into the positional parameters.
eval set -- "$PARSED"

# Loop through the options and assign values to our variables
while (( $# >= 1 )); do
    case "$1" in
        --bucket-location)
            BUCKET_LOCATION="$2"
            shift 2
            ;;
        --project-id)
            PROJECT_ID="$2"
            shift 2
            ;;
        --package-level-parallelism)
            PACKAGE_LEVEL_PARALLELISM="$2"
            shift 2
            ;;
        --test-installed-package)
            TEST_INSTALLED_PACKAGE=true
            shift 
            ;;
        --install-package-from-path)
            INSTALL_PACKAGE_FROM_PATH="$2"
            shift 2
            ;;
        --skip-non-essential-tests)
            SKIP_NON_ESSENTIAL_TESTS_ON_PACKAGE=true
            shift
            ;;
        --no-build-binary-in-script)
            BUILD_BINARY_IN_SCRIPT=false
            shift
            ;;
        --test-on-tpc-endpoint)
            RUN_TEST_ON_TPC_ENDPOINT=true
            shift
            ;;
        --presubmit)
            RUN_TESTS_WITH_PRESUBMIT_FLAG=true
            shift
            ;;
        --zonal)
            RUN_TESTS_WITH_ZONAL_BUCKET=true
            shift
            ;;
        --track-resource-usage)
            TRACK_RESOURCE_USAGE=true
            shift
            ;;
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --help)
            usage 0
            ;;
        --)
            shift
            break
            ;;
        *)
            log_error "Unrecognized arguments [$*]."
            usage 1
            ;;
    esac
done

# Validates option value to be non-empty and should not be another option name.
validate_option_value() {
  local option=$1
  local value=$2
  if [[ -z "$value" || "$value" == -* ]]; then
    log_error "Invalid or empty value [$value] for option $option."
    usage 1
  fi
}

# Fallback to /tmp if OUTPUT_DIR is unset
BASE_PATH="${OUTPUT_DIR:-/tmp}"
mkdir -p "$BASE_PATH" || { 
    log_error "Failed to create or access output directory '$BASE_PATH'"; 
    exit 1 
}
OUTPUT_DIR=$(mktemp -d "${BASE_PATH%/}/gcsfuse-e2e-run-XXXXXXXX") || {
    log_error "Failed to create unique output directory in '$BASE_PATH'";
    exit 1
}
log_info "Output directory for the e2e run is set to '$OUTPUT_DIR'"

if [[ -z "$BUCKET_LOCATION" ]]; then
  log_info "Bucket Location is not provided, using GCE VM Location '$GCE_VM_LOCATION' as bucket location."
  BUCKET_LOCATION="$GCE_VM_LOCATION"
fi

if [[ -z "$PROJECT_ID" ]]; then 
  log_info "Project ID is not provided, using GCE VM Project ID '$GCE_VM_PROJECT_ID' as Project ID."
  PROJECT_ID="$GCE_VM_PROJECT_ID"
fi

# Check if it contains "cloudtop"
if [[ "$PROJECT_ID" == *"cloudtop"* ]]; then
  log_info "You are running this script on cloudtop. Manually overriding the Project ID to 'gcs-fuse-test'."
  PROJECT_ID="gcs-fuse-test"
fi

# Validate long options which need values(default or user provided).
validate_option_value "--bucket-location" "$BUCKET_LOCATION"
validate_option_value "--project-id" "$PROJECT_ID"
validate_option_value "--package-level-parallelism" "$PACKAGE_LEVEL_PARALLELISM"

# Validate test install package from path
if ${TEST_INSTALLED_PACKAGE} && [[ -n "$INSTALL_PACKAGE_FROM_PATH" ]]; then 
  log_error "Option --test-installed-package and --install-package-from-path are mutually exclusive. Please set only one"
  usage 1
fi

# Zonal Bucket location validation.
if ${RUN_TESTS_WITH_ZONAL_BUCKET}; then
  supported_bucket=false
  for location in "${ZONAL_BUCKET_SUPPORTED_LOCATIONS[@]}"; do
    if [[ "$BUCKET_LOCATION" == "$location" ]]; then
      supported_bucket=true
      break
    fi
  done
  if ! ${supported_bucket}; then
    log_error "Unsupported Bucket Location ${BUCKET_LOCATION} for Zonal Run. Supported Locations are: ${ZONAL_BUCKET_SUPPORTED_LOCATIONS[*]}"
    exit 1
  fi
fi

# Create file helper creates a file in the output directory.
create_file_helper() {
  local relative_path="$1"

  if [[ -z "$relative_path" ]]; then
    log_error "Usage: create_file_helper <relative_path>"
    exit 1
  fi

  local full_path="${OUTPUT_DIR%/}/$relative_path"
  local target_dir
  target_dir=$(dirname "$full_path")

  # Create parent directories and then the empty file
  {
    mkdir -p "$target_dir" && touch "$full_path" 
  } &> /dev/null || {
    log_error "Failed to create file at: $full_path"
    exit 1
  }
  echo "$full_path"
}

LOG_LOCK_FILE=$(create_file_helper "logging.lock")
BUCKET_CREATION_LOCK_FILE=$(create_file_helper "bucket_creation.lock")
PACKAGE_RUNTIME_STATS=$(create_file_helper "package_runtime_stats.txt")
RESOURCE_USAGE_FILE=$(create_file_helper "system_resource_usage.txt")
CREATED_BUCKETS_LIST_FILE=$(create_file_helper "created_buckets_list.txt")

# Test packages which can be run for both Zonal and Regional buckets.
# Sorted list descending run times. (Longest Processing Time first strategy) 
TEST_PACKAGES_COMMON=(
  "managed_folders"
  "operations"
  "read_large_files"
  "concurrent_operations"
  # "read_cache"
  "list_large_dir"
  "mount_timeout"
  "write_large_files"
  "implicit_dir"
  "interrupt"
  "local_file"
  "readonly"
  "readonly_creds"
  "rename_dir_limit"
  "kernel_list_cache"
  "streaming_writes"
  "benchmarking"
  "explicit_dir"
  "gzip"
  "log_rotation"
  "monitoring"
  "mounting"
  "unsupported_path"
  # "grpc_validation"
  "negative_stat_cache"
  "stale_handle"
  "release_version"
  "readdirplus"
  "dentry_cache"
  "buffered_read"
  "flag_optimizations"
)

# Test packages for regional buckets.
TEST_PACKAGES_FOR_RB=("${TEST_PACKAGES_COMMON[@]}" "read_cache" "inactive_stream_timeout" "cloud_profiler" "requester_pays_bucket")
# Test packages for zonal buckets.
TEST_PACKAGES_FOR_ZB=("${TEST_PACKAGES_COMMON[@]}" "rapid_appends" "unfinalized_object")
# Test packages for TPC buckets.
TEST_PACKAGES_FOR_TPC=("operations")

# acquire_lock: Acquires exclusive lock or exits script on failure.
# Args: $1 = path to lock file.
acquire_lock() {
  if [[ -z "$1" ]]; then
    log_error "acquire_lock: Lock file path is required."
    exit 1
  fi
  local lock_file="$1"
  local timeout_seconds=600 # 10 minutes
  exec 200>"$lock_file" || {
    log_error "Could not open lock file $lock_file."
    exit 1
  }
  # Attempt to acquire the lock with a timeout
  if ! flock -x -w "$timeout_seconds" 200; then
    log_error "Failed to acquire lock on $lock_file within $timeout_seconds seconds."
    # Close the file descriptor if the lock was not acquired
    exec 200>&-
    exit 1
  fi
  return 0
}

# release_lock: Releases lock or exits script on failure.
# Args: $1 = path to lock file
release_lock() {
  if [[ -z "$1" ]]; then
    log_error "release_lock: Lock file path is required."
    exit 1
  fi
  local lock_file="$1"
  [[ -e "/proc/self/fd/200" || -L "/proc/self/fd/200" ]] && exec 200>&- || {
    log_error "Lock file descriptor (FD 200) not open for $lock_file. Possible previous error or double release."
    exit 1
  } # FD not open or close failed
  return 0
}

# logs info to stdout exclusively. used in background commands to ensure logs aren't interleaved.
log_info_locked() {
  acquire_lock "$LOG_LOCK_FILE"
  log_info "$1"
  release_lock "$LOG_LOCK_FILE"
}

# logs error to stdout exclusively. Used in background commands to ensure logs aren't interleaved.
log_error_locked() {
  acquire_lock "$LOG_LOCK_FILE"
  log_error "$1"
  release_lock "$LOG_LOCK_FILE"
}

# Helper method to organize the test log file based on exit code and remove the original.
process_test_log() {
  if [[ $# -lt 3 ]]; then
    log_error "process_test_log() called with incorrect number of arguments."
    return 1
  fi
  local exit_code="$1"
  local log_file="$2"
  local base_filename="$3"
  local bucket_type="$4"

  local status_dir
  if [[ "$exit_code" -eq 0 ]]; then
    status_dir="${SUCCESS_DIR_NAME}"
  else
    status_dir="${FAILED_DIR_NAME}"
  fi

  local dest_dir="${OUTPUT_DIR}/${status_dir}"
  if [[ -n "$bucket_type" ]]; then
    dest_dir="${dest_dir}/${bucket_type}"
  fi

  mkdir -p "$dest_dir"
  cp "$log_file" "$dest_dir/${base_filename}.txt"
  rm -f "$log_file"
}


# Helper method to create "flat", "hns" or "zonal" bucket.
create_bucket() {
  if [[ $# -ne 2 ]]; then
    log_error "create_bucket() called with incorrect number of arguments."
    return 1
  fi
  local package="$1"
  local bucket_type="$2"
  local bucket_name="${BUCKET_PREFIX}-${package}-${bucket_type}-$(date +%s%N)"
  local bucket_cmd_parts=("gcloud" "alpha" "storage" "buckets" "create" "gs://${bucket_name}" "--project=${PROJECT_ID}" "--location=${BUCKET_LOCATION}" "--uniform-bucket-level-access")
  if [[ "$bucket_type" == "$HNS" ]]; then
    bucket_cmd_parts+=("--enable-hierarchical-namespace")
  elif [[ "$bucket_type" == "$ZONAL" ]]; then
    bucket_cmd_parts+=("--enable-hierarchical-namespace" "--placement=${BUCKET_LOCATION}-a" "--default-storage-class=RAPID")
  elif [[ "$bucket_type" != "$FLAT" ]]; then
    log_error "Invalid bucket type: $bucket_type."
    return 1
  fi
  local bucket_cmd bucket_cmd_log attempt=5
  bucket_cmd=$(printf "%q " "${bucket_cmd_parts[@]}")
  bucket_cmd_log=$(create_file_helper "bucket_creation_logs/${bucket_name}.txt")
  while : ; do
    attempt=$((attempt - 1))
    if [ $attempt -lt 0 ]; then
      log_error "Unable to create bucket [${bucket_name}] after 5 attempts." 
      cat "$bucket_cmd_log"
      return 1
    fi
    acquire_lock "$BUCKET_CREATION_LOCK_FILE"
    eval "$bucket_cmd" > "$bucket_cmd_log" 2>&1
    local status=$?
    sleep "$DELAY_BETWEEN_BUCKET_CREATION" # have 6 seconds gap between creating buckets.
    release_lock "$BUCKET_CREATION_LOCK_FILE"
    if [ $status -eq 0 ]; then
      break
    fi
  done
  echo "$bucket_name"
  # Append to created buckets list file for cleanup
  acquire_lock "$BUCKET_CREATION_LOCK_FILE"
  echo "$bucket_name" >> "$CREATED_BUCKETS_LIST_FILE"
  release_lock "$BUCKET_CREATION_LOCK_FILE"
  rm -rf "$bucket_cmd_log"
  return 0
}

# Helper method to cleanup buckets created during this run.
cleanup_created_buckets() {
    if [ ! -f "$CREATED_BUCKETS_LIST_FILE" ]; then
        return 0
    fi

    local -a bucket_uris
    mapfile -t bucket_uris < "$CREATED_BUCKETS_LIST_FILE"

    if [ ${#bucket_uris[@]} -eq 0 ]; then
        log_info "No buckets were created to cleanup."
        return 0
    fi

    log_info "Found ${#bucket_uris[@]} buckets created during run to cleanup."

    local batch_count=0
    local start_index=0
    local total_buckets=${#bucket_uris[@]}
    # Number of buckets to delete in a single batch.
    local readonly bucket_deletion_batch_size=10

    while [ "$start_index" -lt "$total_buckets" ]; do
        # Calculate end index for the current batch
        local end_index=$((start_index + bucket_deletion_batch_size))
        if [ "$end_index" -gt "$total_buckets" ]; then
            end_index=$total_buckets
        fi

        # Extract batch slice
        local length=$((end_index - start_index))
        local batch=("${bucket_uris[@]:$start_index:$length}")
        
        # Add gs:// prefix if missing (bucket names are stored as name only)
        local batch_uris=()
        local batch_names_str=""
        for b in "${batch[@]}"; do
            batch_uris+=("gs://$b")
            if [ -z "$batch_names_str" ]; then
                batch_names_str="$b"
            else
                batch_names_str="$batch_names_str, $b"
            fi
        done

        batch_count=$((batch_count + 1))
        log_info "Deleting bucket batch: $batch_count ..."

        # Delete batch
        if ! gcloud storage rm -r "${batch_uris[@]}" --no-user-output-enabled --verbosity=error; then
            log_error "Failed to delete one or more buckets in batch: $batch_count. These buckets would be cleaned up by the periodic cleanup job."
            # We continue here to try deleting other batches if one fails
        fi

        start_index=$end_index
    done
    
    rm -f "$CREATED_BUCKETS_LIST_FILE"
    log_info "Bucket cleanup complete."
}

# Get command of the PID and check if it contains the string. Kill if it does.
safe_kill() {
  local pid=$1
  local str=$2
  local cmd

  if [[ -n "$pid" && -n "$str" ]] && cmd=$(ps -p "$pid" -o cmd=) && [[ "$cmd" == *"$str"* ]]; then
    kill "$pid"
  else
    return 1
  fi
}

# Cleanup ensures each of the buckets created is destroyed and the temp files are cleaned up.
clean_up() {
  if ${TRACK_RESOURCE_USAGE}; then
    if ! safe_kill "$RESOURCE_USAGE_PID" "resource_usage.sh"; then
      log_error "Failed to stop resource usage collection process (or it's already stopped)"
    else
      log_info "Resource usage collection process stopped."
    fi
  fi
  if [ -n "${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}" ] && [ -d "${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}" ]; then
    log_info "Cleaning up GCSFuse build directory created by script: ${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}"
    rm -rf "${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}"
  fi
  cleanup_created_buckets
}

# Helper method to process any of the background process and
# returns exit status of waited pid.
process_any_pid() {
  local -n cmds_by_pid_ref="$1"
  local waited_pid
  local pid_status # To store the exit status of the waited pid

  wait -n -p waited_pid # waited_pid gets the PID, $? gets the status
  pid_status=$?

  unset "cmds_by_pid_ref[$waited_pid]"
  if [[ "$pid_status" -ne 0 ]]; then
    return 1
  fi
  return 0
}

# run_parallel: Executes commands in parallel based on a template and substitutes.
#   The function returns a non-zero exit status if any of the parallel commands fail.
#
# Usage: run_parallel "parallelism" "command_template_with_@" "substitute1" "substitute2" ...
#   First argument is extent of parallelism for this command.
#   Second argument is the command template with single @.
#   Rest of the arguments are values that would be substituted in the command template.
#
# Example:
#   run_parallel 2 "echo 'Processing @' && sleep 1" "itemA" "itemB" "itemC"
# This command will run at max 2 commands in parallel.
run_parallel() {
  if [[ $# -lt 2 ]]; then
    log_error_locked "run_parallel() called with incorrect number of arguments."
    return 1
  fi
  local parallelism="$1"
  shift
  local cmd_template="$1"
  shift
  local -A cmds_by_pid=()
  local overall_exit_code=0 parallel_cmd pid
  # Launch parallel commands in the background based on parallelism.
  for arg in "$@"; do
    parallel_cmd="${cmd_template//@/$arg}"
    eval "$parallel_cmd" &
    pid=$!
    cmds_by_pid["$pid"]="$parallel_cmd"
    if [[ ${#cmds_by_pid[@]} -eq $parallelism ]]; then
      process_any_pid "cmds_by_pid"
      overall_exit_code=$((overall_exit_code || $? ))
    fi
  done
  # Process any remaining PIDs
  while [[ ${#cmds_by_pid[@]} -gt 0 ]]; do
      process_any_pid "cmds_by_pid"
      overall_exit_code=$((overall_exit_code || $? ))
  done
  return $overall_exit_code
}

# Helper method that creates a bucket and then runs the test package.
create_bucket_and_run_test() {
  if [[ $# -ne 2 ]]; then
    log_error_locked "create_bucket_and_run_test() called with incorrect number of arguments."
    return 1
  fi
  local package_name="$1"
  local bucket_type="$2"

  if ! bucket_name=$(create_bucket "$package_name" "$bucket_type"); then
    log_error_locked "Failed to create bucket of type ${bucket_type} for package ${package_name}. Bucket creation output: ${bucket_name}"
    return 1
  fi
  test_package "$package_name" "$bucket_name" "$bucket_type"
}

# Helper method to executes e2e test package.
test_package() {
  if [[ $# -ne 3 ]]; then
    log_error_locked "test_package() called with incorrect number of arguments."
    return 1
  fi
  local package_name="$1"
  local bucket_name="$2"
  local bucket_type="$3"

  # Build go package test command.
  local go_test_cmd_parts=("GODEBUG=asyncpreemptoff=1" "go" "test" "-v" "-timeout=${INTEGRATION_TEST_PACKAGE_TIMEOUT_IN_MINS}m" "${INTEGRATION_TEST_PACKAGE_DIR}/${package_name}")
  if ${SKIP_NON_ESSENTIAL_TESTS_ON_PACKAGE}; then
    go_test_cmd_parts+=("-short")
  fi
  if [[ "$package_name" == "benchmarking" ]]; then
    go_test_cmd_parts+=("-bench=." "-benchtime=100x")
  fi
  # Test Binary flags after this.
  go_test_cmd_parts+=("-args" "--integrationTest" "--testbucket=${bucket_name}")
  if ${TEST_INSTALLED_PACKAGE}; then
    go_test_cmd_parts+=("--testInstalledPackage")
  fi
  if ${RUN_TESTS_WITH_PRESUBMIT_FLAG}; then
    go_test_cmd_parts+=("--presubmit")
  fi
  if [[ "$bucket_type" == "$ZONAL" ]]; then
    go_test_cmd_parts+=("--zonal")
  fi
  if ${RUN_TEST_ON_TPC_ENDPOINT}; then
    go_test_cmd_parts+=("--testOnTPCEndPoint")
  fi
  if [[ -n "$BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR" ]]; then 
    go_test_cmd_parts+=("--gcsfuse_prebuilt_dir=${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}")
  fi

  local go_test_cmd test_package_log_file start=$SECONDS exit_code=0 
  # Use printf %q to quote each argument safely for eval
  # This ensures spaces and special characters within arguments are handled correctly.
  go_test_cmd=$(printf "%q " "${go_test_cmd_parts[@]}")  
  test_package_log_file=$(create_file_helper "running_package_logs/${bucket_type}/${package_name}.txt")
  # Run the package test command and capture log output with runtime stats.
  log_info "Started running test package [$package_name] for bucket type [$bucket_type] with bucket name [$bucket_name]"

  local status_dir
  if ! eval "$go_test_cmd" > "$test_package_log_file" 2>&1; then
    exit_code=1
    log_info "Failed test package [$package_name] for bucket type [$bucket_type]"
  else
    log_info "Passed test package [$package_name] for bucket type [$bucket_type]"
  fi

  local dest_dir="${OUTPUT_DIR}/${status_dir}/${bucket_type}"
  mkdir -p "$dest_dir"
  cp "$test_package_log_file" "$dest_dir/${package_name}.txt"
  local end=$SECONDS

  # Add the package stats to the file.
  echo "${package_name} ${bucket_type} ${exit_code} ${start} ${end}" >> "$PACKAGE_RUNTIME_STATS"
  # Generate Kokoro artifacts(log) files.
  generate_test_log_artifacts "$test_package_log_file" "$package_name" "$bucket_type"
  # Call the helper to organize logs and cleanup the original file
  process_test_log "$exit_code" "$test_package_log_file" "$package_name" "$bucket_type"
  return "$exit_code"
}

# Helper method to generate Kokoro artifacts(log) files when building in Kokoro environment.
generate_test_log_artifacts() {
  # If KOKORO_ARTIFACTS_DIR is not set, skip artifact generation.
  if ! $KOKORO_DIR_AVAILABLE; then
    return 0
  fi

  if [[ $# -ne 3 ]]; then
    log_error_locked "generate_test_log_artifacts() called with incorrect number of arguments."
    return 1
  fi

  local log_file="$1"
  local package_name="$2"
  local bucket_type="$3"

  if [ ! -f "$log_file" ]; then
    return 0
  fi

  local output_dir="${KOKORO_ARTIFACTS_DIR}/${bucket_type}/${package_name}"
  mkdir -p "$output_dir"
  local sponge_log_file="${output_dir}/sponge_log.log"
  local sponge_xml_file="${output_dir}/sponge_log.xml"

  cp "$log_file" "$sponge_log_file"
  
  echo '<?xml version="1.0" encoding="UTF-8"?>' > "${sponge_xml_file}"
  echo '<testsuites>' >> "${sponge_xml_file}"

  # Remove first 2 lines and last line from log.
  local report_log=$(cat "$log_file")
  # For benchmarking package, filter out benchmark results to avoid incorrect XML results.
  if [[ "$package_name" == "benchmarking" ]]; then
    report_log=$(echo "$report_log" | grep -v '^Benchmark_[^[:space:]]*$')
  fi

  echo "$report_log" | go-junit-report | sed '1,2d;$d' >> "${sponge_xml_file}"
  echo '</testsuites>' >> "${sponge_xml_file}"
  
  return 0
}

install_package_from_path() {
  if [[ $# -ne 1 ]]; then
    log_error_locked "install_package_from_path() called with incorrect number of arguments."
    return 1
  fi
  local package_path="$1"
  log_info "Downloading $(basename "${package_path}")..."
  gcloud storage cp "${package_path}" /tmp/ --quiet || return 1
  if [ -f /etc/os-release ]; then
    # We source in a subshell to prevent variable pollution, 
    # then capture only the ID and ID_LIKE fields.
    DISTRO_DATA=$( (source /etc/os-release; echo "${ID:-} ${ID_LIKE:-}") )
    # Check for debian or ubuntu in the ID or the ID_LIKE chain
    if [[ "$DISTRO_DATA" == *"debian"* ]] || [[ "$DISTRO_DATA" == *"ubuntu"* ]]; then
      sudo dpkg -i "/tmp/$(basename "${package_path}")"
    elif [[ "$DISTRO_DATA" == *"rhel"* ]] || [[ "$DISTRO_DATA" == *"centos"* ]]; then
      sudo yum -y localinstall "/tmp/$(basename "${package_path}")"
    else
        log_error "This script only supports Debian/Ubuntu/rhel/centos based distributions."
        log_info "Your distribution is:"
        cat /etc/os-release
        exit 1
    fi
  else
    log_error "/etc/os-release not found. Unable to determine distribution"
    exit 1
  fi
}

build_gcsfuse_once() {
  local build_output_dir # For the final gcsfuse binaries
  build_output_dir=$(mktemp -d -t gcsfuse_e2e_run_build_XXXXXX)
  log_info "GCSFuse binaries will be built in ${build_output_dir}/"

  local gcsfuse_src_dir
  # Determine GCSFuse source directory
  # If this script is in tools/integration_tests, project root is ../../
  SCRIPT_DIR_REALPATH=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
  gcsfuse_src_dir=$(realpath "${SCRIPT_DIR_REALPATH}/../../")

  if [[ ! -f "${gcsfuse_src_dir}/go.mod" ]]; then
    log_error "Could not reliably determine GCSFuse project root from ${SCRIPT_DIR_REALPATH}. Expected go.mod at ${gcsfuse_src_dir}" >&2
    rm -rf "${build_output_dir}"
    exit 1
  fi
  log_info "Using GCSFuse source directory: ${gcsfuse_src_dir}"

  log_info "Building GCSFuse using 'go run ./tools/build_gcsfuse/main.go'..."
  (cd "${gcsfuse_src_dir}" && go run ./tools/build_gcsfuse/main.go . "${build_output_dir}" "0.0.0")
  if [ $? -ne 0 ]; then
    log_error "Building GCSFuse binaries using 'go run ./tools/build_gcsfuse/main.go' failed."
    rm -rf "${build_output_dir}" # Clean up created temp dir
    return 1
  fi

  # Set the directory path for use by the script (to form the go test flag)
  BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR="${build_output_dir}"
  log_info "GCSFuse binaries built by script in: ${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}"
  log_info "GCSFuse executable: ${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}/bin/gcsfuse"
  return 0
}

install_packages() {
  local os_id
  
  # Determine the absolute location of THIS script
  SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

  # Calculate the Repo Root
  REPO_ROOT="${SCRIPT_DIR}/../.."

  source "${REPO_ROOT}/perfmetrics/scripts/os_utils.sh"
  
  if ! os_id=$(get_os_id); then
    log_error "Failed to detect OS ID."
    exit 1
  fi
  log_info "Detected OS ID: $os_id"

  install_packages_by_os "$os_id" "python3" "gcc" "python3-dev" "python3-setuptools" "python3-crcmod" || {
    log_error "Failed to install required packages."
    exit 1
  }

  # Execute install_go.sh using the absolute path
  bash "${REPO_ROOT}/perfmetrics/scripts/install_go.sh" "$GO_VERSION"
  export PATH="/usr/local/go/bin:$PATH"
  
  # Install latest gcloud version.
  bash "${REPO_ROOT}/perfmetrics/scripts/install_latest_gcloud.sh"
  export PATH="/usr/local/google-cloud-sdk/bin:$PATH"
  export CLOUDSDK_PYTHON="$HOME/.local/python-3.11.9/bin/python3.11"
  export PATH="$HOME/.local/python-3.11.9/bin:$PATH"
  if ${KOKORO_DIR_AVAILABLE} ; then
    # Install go-junit-report to generate XML test reports from go logs.
    go install github.com/jstemmer/go-junit-report/v2@latest
    export PATH="$(go env GOPATH)/bin:$PATH"
  fi
}

# Generic function to run a group of E2E tests for a given bucket type.
# Args:
#   $1: Descriptive group name (e.g., "REGIONAL", "ZONAL", "TPC")
#   $2: Bucket type ("flat", "hns", "zonal")
#   $@: A list of test package names to run.
run_test_group() {
  local group_name="$1"
  local bucket_type="$2"
  shift 2
  local -a test_packages=("$@")
  local group_exit_code=0
  log_info_locked "Started running e2e tests for ${group_name} group (bucket type: ${bucket_type})."

  run_parallel "$PACKAGE_LEVEL_PARALLELISM" "create_bucket_and_run_test @ ${bucket_type}" "${test_packages[@]}"
  group_exit_code=$?

  if [ "$group_exit_code" -ne 0 ]; then
    log_error_locked "The e2e tests for ${group_name} group (bucket type: ${bucket_type}) FAILED."
    return 1
  fi
  log_info_locked "The e2e tests for ${group_name} group (bucket type: ${bucket_type}) successful."
  return 0
}

run_e2e_tests_for_emulator() {
  log_info_locked "Started running e2e tests for emulator."
  local emulator_test_log
  emulator_test_log=$(create_file_helper "running_package_logs/emulator_package.txt")

  local exit_code=0
  if ! ./tools/integration_tests/emulator_tests/emulator_tests.sh "$TEST_INSTALLED_PACKAGE" > "$emulator_test_log" 2>&1; then
    log_error_locked "Failed e2e tests for emulator."
    exit_code=1
  else
    log_info_locked "Passed e2e tests for emulator."
  fi

  # Call the helper to copy log to the right status directory and delete the original log
  process_test_log "$exit_code" "$emulator_test_log" "emulator_package"

  return "$exit_code"
}

main() {
  # Clean up everything on exit.
  trap clean_up EXIT
  log_info ""
  log_info "------ Upgrading gcloud and installing packages ------"
  log_info ""
  set -e
  install_packages
  set +e
  log_info "------ Upgrading gcloud and installing packages took $SECONDS seconds ------"

  log_info ""
  log_info "------ Started running E2E test packages ------"
  log_info ""

   # Decide whether to install a package from a path or build GCSFuse based on RUN_E2E_TESTS_ON_PACKAGE
  if [[ -n "$INSTALL_PACKAGE_FROM_PATH" ]]; then
    log_info "Installing package from the path '${INSTALL_PACKAGE_FROM_PATH}'"
    if ! install_package_from_path "$INSTALL_PACKAGE_FROM_PATH"; then 
      log_error "Unable to install the package from path '${INSTALL_PACKAGE_FROM_PATH}'. Exiting."
      exit 1
    fi
    # Setting test installed package to true
    TEST_INSTALLED_PACKAGE=true
  elif (! ${TEST_INSTALLED_PACKAGE} ) && ${BUILD_BINARY_IN_SCRIPT}; then
    log_info "TEST_INSTALLED_PACKAGE is not 'true' (value: '${TEST_INSTALLED_PACKAGE}') and BUILD_BINARY_IN_SCRIPT is 'true'."
    log_info "Building GCSFuse inside script..."
    if ! build_gcsfuse_once; then
        log_error "build_gcsfuse_once failed. Exiting."
        # The trap will handle cleanup
        exit 1
    fi
    log_info "Script built GCSFuse at: ${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}"
  fi

  # Reset SECONDS to 0
  SECONDS=0

  if ${TRACK_RESOURCE_USAGE}; then
    # Start collecting system resource usage in background.
    log_info "Starting resource usage collection process."
    ./tools/integration_tests/resource_usage.sh "COLLECT" "$RESOURCE_USAGE_FILE" &
    RESOURCE_USAGE_PID=$!
    log_info "Resource usage collection process started at PID: $RESOURCE_USAGE_PID"
  fi

  local pids=()
  local overall_exit_code=0
  if ${RUN_TESTS_WITH_ZONAL_BUCKET}; then
    run_test_group "ZONAL" "$ZONAL" "${TEST_PACKAGES_FOR_ZB[@]}" & pids+=($!)
  elif ${RUN_TEST_ON_TPC_ENDPOINT}; then
    # Override PROJECT_ID and BUCKET_LOCATION for TPC tests
    PROJECT_ID="$TPCZERO_PROJECT_ID"
    BUCKET_LOCATION="$TPC_BUCKET_LOCATION"
    run_test_group "TPC" "$HNS" "${TEST_PACKAGES_FOR_TPC[@]}" & pids+=($!)
    run_test_group "TPC" "$FLAT" "${TEST_PACKAGES_FOR_TPC[@]}" & pids+=($!)
  else
    run_test_group "REGIONAL" "$HNS" "${TEST_PACKAGES_FOR_RB[@]}" & pids+=($!)
    run_test_group "REGIONAL" "$FLAT" "${TEST_PACKAGES_FOR_RB[@]}" & pids+=($!)
    run_e2e_tests_for_emulator & pids+=($!) # Emulator tests are a separate group
  fi
  # Wait for all background processes to complete and aggregate their exit codes
  for pid in "${pids[@]}"; do
    wait "$pid"
    overall_exit_code=$((overall_exit_code || $?))
  done
  elapsed_min=$(((SECONDS + 60) / 60))
  log_info "------ E2E test packages complete run took ${elapsed_min} minutes ------"
  log_info ""

  # Print package runtime stats table.
  ./tools/integration_tests/create_package_runtime_table.sh "$PACKAGE_RUNTIME_STATS"

  if ${TRACK_RESOURCE_USAGE}; then
    # Kill resource usage background PID and print resource usage.
    log_info "Stopping resource usage collection process: $RESOURCE_USAGE_PID"
    if safe_kill "$RESOURCE_USAGE_PID" "resource_usage.sh"; then
      log_info "Resource usage collection process stopped."
      ./tools/integration_tests/resource_usage.sh "PRINT" "$RESOURCE_USAGE_FILE"
    else
      log_error "Failed to stop resource usage collection process (or it's already stopped)"
    fi
  fi
  exit $overall_exit_code
}

#Main method to run script
main
