#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Script Usage Documentation
usage() {
  echo "Usage: $0 [options]"
  echo "Options:"
  echo "    --test-installed-package                     Test installed gcsfuse package. (Default: false)"
  echo "    --install-package-from-path   <path>         Google Cloud Storage bucket path for GCSFuse package for testing (e.g. gs://<bucket-name>/my-gcsfuse-package.rpm)"
  echo "                                                 This option is mutually exclusive with --test-installed-package. (Default: "")"
  echo "    --skip-non-essential-tests                   Skip non-essential tests inside packages. (Default: false)"
  echo "    --presubmit                                  Run tests with presubmit flag. (Default: false)"
  echo "    --no-build-binary-in-script                  To disable building gcsfuse binary in script. (Default: false)"
  echo "    --package-level-parallelism   <parallelism>  To adjust the number of packages to execute in parallel. (Default: 10)"
  echo "    --track-resource-usage                       To track resource(cpu/mem/disk) usage during e2e run. (Default: false)"
  echo "    --output-dir                  <output-dir>   Directory in which all of log files generated by this script will be stored. (Default: /tmp)"
  echo "    --run-package                 <regex>        Regex for packages to run. Supports '!' prefix for exclusion."
  echo "                                                 Example: 'cloud_profiler|operations' to run only cloud_profiler and operations test packages."
  echo "                                                 Example: '!cloud_profiler|operations' to run all test packages except cloud_profiler and operations."
  echo "    --flake-attempts              <number>       Number of attempts to run a package if it fails. (Default: 1)"
  echo "    --help                                       Display this help and exit."
  exit "$1"
}

# Logging Helpers
log_info() {
  echo "[INFO] $(date +"%Y-%m-%d %H:%M:%S"): $1"
}

log_error() {
  echo "[ERROR] $(date +"%Y-%m-%d %H:%M:%S"): $1"
}

# Check or install bash version before continuing script.
readonly REQUIRED_BASH_MAJOR=5
readonly REQUIRED_BASH_MINOR=1
readonly BASH_INSTALL_VERSION="5.3"
readonly BASH_INSTALLATION_PATH="/usr/local/bin/bash" # Using 5.3 for installation as bash 5.1 has an installation bug.

if (( BASH_VERSINFO[0] < REQUIRED_BASH_MAJOR || ( BASH_VERSINFO[0] == REQUIRED_BASH_MAJOR && BASH_VERSINFO[1] < REQUIRED_BASH_MINOR ) )); then
  log_info "Current Bash version (${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}) is older than required (${REQUIRED_BASH_MAJOR}.${REQUIRED_BASH_MINOR})."
  log_info "Installing Bash ${BASH_INSTALL_VERSION}..."

  # Dynamically find the repo root so we can locate the install script safely
  SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
  REPO_ROOT=$(realpath "${SCRIPT_DIR}/../..")

  # Run the installation script
  "${REPO_ROOT}/perfmetrics/scripts/install_bash.sh" "${BASH_INSTALL_VERSION}"
  if [[ ! -x "${BASH_INSTALLATION_PATH}" ]]; then
    log_error "Failed to locate the newly installed bash at ${BASH_INSTALLATION_PATH}"
    exit 1
  fi

  log_info "Re-executing the e2e script using the newly installed Bash ${BASH_INSTALL_VERSION}..."
  # The 'exec' command completely replaces the current old-bash process 
  # with the new bash process, passing along the script name ($0) and all arguments ($@).
  exec "${BASH_INSTALLATION_PATH}" "$0" "$@"
fi
log_info "Bash version: ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}"

# Constants
readonly GO_VERSION=$(cat "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../../.go-version")
readonly INTEGRATION_TEST_PACKAGE_DIR="./tools/integration_tests"
readonly INTEGRATION_TEST_PACKAGE_TIMEOUT_IN_MINS=90 
readonly SUCCESS_DIR_NAME="success_package_logs"
readonly FAILED_DIR_NAME="failed_package_logs"

# Extract GCE VM Project and Location.
ZONE=$(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/zone)
ZONE_NAME=$(basename "$ZONE")
GCE_VM_LOCATION="${ZONE_NAME%-*}"
GCE_VM_PROJECT_ID=$(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/project/project-id)
log_info "Project ID from GCE VM: '$GCE_VM_PROJECT_ID'"
log_info "Location from GCE VM: '$GCE_VM_LOCATION'"
log_info "Running e2e script as '$(whoami)'"
log_info "Current directory is '$(pwd)'"
# If HOME is not set, find it dynamically and export it
if [ -z "$HOME" ]; then
    export HOME=$(getent passwd "$(whoami)" | cut -d: -f6)
fi
log_info "HOME is set to '$HOME'"

# This variable will store the path if the script builds GCSFuse binaries (gcsfuse, mount.gcsfuse)
BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR=""

# Output directory where all artifacts generated by this script will be stored.
OUTPUT_DIR=""

KOKORO_DIR_AVAILABLE=false
if [[ -n "$KOKORO_ARTIFACTS_DIR" ]]; then
  KOKORO_DIR_AVAILABLE=true
fi

# Argument Parsing and Assignments
# Set default values for optional arguments
SKIP_NON_ESSENTIAL_TESTS_ON_PACKAGE=false
TEST_INSTALLED_PACKAGE=false
INSTALL_PACKAGE_FROM_PATH=""
RUN_TESTS_WITH_PRESUBMIT_FLAG=false
BUILD_BINARY_IN_SCRIPT=true
TRACK_RESOURCE_USAGE=false
PACKAGE_LEVEL_PARALLELISM=10 # Controls how many test packages are run in parallel for hns, flat or zonal buckets.
RUN_PACKAGE_REGEX=""
FLAKE_ATTEMPTS=1

# Define options for getopt
# A long option name followed by a colon indicates it requires an argument.
LONG=test-installed-package,install-package-from-path:,skip-non-essential-tests,no-build-binary-in-script,presubmit,package-level-parallelism:,track-resource-usage,output-dir:,help,run-package:,flake-attempts:

# Parse the options using getopt
# --options "" specifies that there are no short options.
PARSED=$(getopt --options "" --longoptions "$LONG" --name "$0" -- "$@")
if [[ $? -ne 0 ]]; then
    # getopt will have already printed an error message
    usage 1
fi

# Read the parsed options back into the positional parameters.
eval set -- "$PARSED"

# Loop through the options and assign values to our variables
while (( $# >= 1 )); do
    case "$1" in
        --package-level-parallelism)
            PACKAGE_LEVEL_PARALLELISM="$2"
            shift 2
            ;;
        --test-installed-package)
            TEST_INSTALLED_PACKAGE=true
            shift 
            ;;
        --install-package-from-path)
            INSTALL_PACKAGE_FROM_PATH="$2"
            shift 2
            ;;
        --skip-non-essential-tests)
            SKIP_NON_ESSENTIAL_TESTS_ON_PACKAGE=true
            shift
            ;;
        --no-build-binary-in-script)
            BUILD_BINARY_IN_SCRIPT=false
            shift
            ;;
        --presubmit)
            RUN_TESTS_WITH_PRESUBMIT_FLAG=true
            shift
            ;;
        --track-resource-usage)
            TRACK_RESOURCE_USAGE=true
            shift
            ;;
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --run-package)
            RUN_PACKAGE_REGEX="$2"
            shift 2
            ;;
        --flake-attempts)
            FLAKE_ATTEMPTS="$2"
            shift 2
            ;;
        --help)
            usage 0
            ;;
        --)
            shift
            break
            ;;
        *)
            log_error "Unrecognized arguments [$*]."
            usage 1
            ;;
    esac
done

# Validates option value to be non-empty and should not be another option name.
validate_option_value() {
  local option=$1
  local value=$2
  if [[ -z "$value" || "$value" == -* ]]; then
    log_error "Invalid or empty value [$value] for option $option."
    usage 1
  fi
}

# Fallback to /tmp if OUTPUT_DIR is unset
BASE_PATH="${OUTPUT_DIR:-/tmp}"
mkdir -p "$BASE_PATH" || { 
    log_error "Failed to create or access output directory '$BASE_PATH'"; 
    exit 1 
}
OUTPUT_DIR=$(mktemp -d "${BASE_PATH%/}/gcsfuse-e2e-run-XXXXXXXX") || {
    log_error "Failed to create unique output directory in '$BASE_PATH'";
    exit 1
}
OUTPUT_DIR=$(realpath "$OUTPUT_DIR")
log_info "Output directory for the e2e run is set to '$OUTPUT_DIR'"

# Validate long options which need values(default or user provided).
validate_option_value "--package-level-parallelism" "$PACKAGE_LEVEL_PARALLELISM"
validate_option_value "--flake-attempts" "$FLAKE_ATTEMPTS"

# Validate test install package from path
if ${TEST_INSTALLED_PACKAGE} && [[ -n "$INSTALL_PACKAGE_FROM_PATH" ]]; then 
  log_error "Option --test-installed-package and --install-package-from-path are mutually exclusive. Please set only one"
  usage 1
fi

# Create file helper creates a file in the output directory.
create_file_helper() {
  local relative_path="$1"

  if [[ -z "$relative_path" ]]; then
    log_error "Usage: create_file_helper <relative_path>"
    exit 1
  fi

  local full_path="${OUTPUT_DIR%/}/$relative_path"
  local target_dir
  target_dir=$(dirname "$full_path")

  # Create parent directories and then the empty file
  {
    mkdir -p "$target_dir" && touch "$full_path" 
  } &> /dev/null || {
    log_error "Failed to create file at: $full_path"
    exit 1
  }
  echo "$full_path"
}

LOG_LOCK_FILE=$(create_file_helper "logging.lock")
PACKAGE_RUNTIME_STATS=$(create_file_helper "package_runtime_stats.txt")
RESOURCE_USAGE_FILE=$(create_file_helper "system_resource_usage.txt")

# Test packages which can be run for Pirlo buckets.
# Sorted list descending run times. (Longest Processing Time first strategy) 
TEST_PACKAGES=(
  "managed_folders"
  "operations"
  "read_large_files"
  "concurrent_operations"
  "read_cache"
  "list_large_dir"
  "write_large_files"
  "implicit_dir"
  "interrupt"
  "local_file"
  "readonly"
  "readonly_creds"
  "rename_dir_limit"
  "kernel_list_cache"
  "streaming_writes"
  "benchmarking"
  "explicit_dir"
  "gzip"
  "log_rotation"
  "monitoring"
  "mounting"
  "unsupported_path"
  "negative_stat_cache"
  "stale_handle"
  "release_version"
  "readdirplus"
  "dentry_cache"
  "buffered_read"
  "flag_optimizations"
  "symlink_handling"
  "rapid_operations"
  "unfinalized_object"
)

# filter_array: Filters an array in place keeping only elements matching the regex.
# Supports '!' prefix to invert the match (exclude).
# Args: $1 = name of the array variable, $2 = regex pattern.
filter_array() {
  local -n arr=$1
  local regex=$2

  # Return early if regex or array is empty
  [[ -z "$regex" || ${#arr[@]} -eq 0 ]] && return

  # Check if regex starts with '!', meaning we want to exclude matches
  local invert=""
  if [[ "$regex" == !* ]]; then
    invert="-v"
    regex="${regex#!}" # Strip the '!' prefix
  fi

  # Filter the array using grep and map the results back to the array
  mapfile -t arr < <(printf '%s\n' "${arr[@]}" | grep $invert -E "$regex")
}

# Parse and apply --run-package filters if provided
if [[ -n "$RUN_PACKAGE_REGEX" ]]; then
  filter_array TEST_PACKAGES "$RUN_PACKAGE_REGEX"
fi

# acquire_lock: Acquires exclusive lock or exits script on failure.
# Args: $1 = path to lock file.
acquire_lock() {
  if [[ -z "$1" ]]; then
    log_error "acquire_lock: Lock file path is required."
    exit 1
  fi
  local lock_file="$1"
  local timeout_seconds=600 # 10 minutes
  exec 200>"$lock_file" || {
    log_error "Could not open lock file $lock_file."
    exit 1
  }
  # Attempt to acquire the lock with a timeout
  if ! flock -x -w "$timeout_seconds" 200; then
    log_error "Failed to acquire lock on $lock_file within $timeout_seconds seconds."
    # Close the file descriptor if the lock was not acquired
    exec 200>&-
    exit 1
  fi
  return 0
}

# release_lock: Releases lock or exits script on failure.
# Args: $1 = path to lock file
release_lock() {
  if [[ -z "$1" ]]; then
    log_error "release_lock: Lock file path is required."
    exit 1
  fi
  local lock_file="$1"
  [[ -e "/proc/self/fd/200" || -L "/proc/self/fd/200" ]] && exec 200>&- || {
    log_error "Lock file descriptor (FD 200) not open for $lock_file. Possible previous error or double release."
    exit 1
  } # FD not open or close failed
  return 0
}

# logs info to stdout exclusively. used in background commands to ensure logs aren't interleaved.
log_info_locked() {
  acquire_lock "$LOG_LOCK_FILE"
  log_info "$1"
  release_lock "$LOG_LOCK_FILE"
}

# logs error to stdout exclusively. Used in background commands to ensure logs aren't interleaved.
log_error_locked() {
  acquire_lock "$LOG_LOCK_FILE"
  log_error "$1"
  release_lock "$LOG_LOCK_FILE"
}

# Helper method to organize the test log file based on exit code and bucket type.
# It organizes the log files in the following directory.
# ${OUTPUT_DIR}/failed_package_logs/${BUCKET_TYPE}/...
# ${OUTPUT_DIR}/success_package_logs/${BUCKET_TYPE}/...
organize_test_logfile() {
  if [[ $# -ne 4 ]]; then
    log_error "organize_test_logfile() called with incorrect number of arguments."
    return 1
  fi
  local exit_code="$1"
  local log_file="$2"
  local base_filename="$3"
  local bucket_type="$4"

  local status_dir
  if [[ "$exit_code" -eq 0 ]]; then
    status_dir="${SUCCESS_DIR_NAME}"
  else
    status_dir="${FAILED_DIR_NAME}"
  fi

  local dest_dir="${OUTPUT_DIR}/${status_dir}"
  if [[ -n "$bucket_type" ]]; then
    dest_dir="${dest_dir}/${bucket_type}"
  fi

  mkdir -p "$dest_dir"
  cp "$log_file" "$dest_dir/${base_filename}.txt"
  rm -f "$log_file"
}

# Get command of the PID and check if it contains the string. Kill if it does.
safe_kill() {
  local pid=$1
  local str=$2
  local cmd

  if [[ -n "$pid" && -n "$str" ]] && cmd=$(ps -p "$pid" -o cmd=) && [[ "$cmd" == *"$str"* ]]; then
    kill "$pid"
  else
    return 1
  fi
}

# Cleanup ensures each of the buckets created is destroyed and the temp files are cleaned up.
clean_up() {
  if ${TRACK_RESOURCE_USAGE}; then
    if ! safe_kill "$RESOURCE_USAGE_PID" "resource_usage.sh"; then
      log_error "Failed to stop resource usage collection process (or it's already stopped)"
    else
      log_info "Resource usage collection process stopped."
    fi
  fi
  if [ -n "${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}" ] && [ -d "${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}" ]; then
    log_info "Cleaning up GCSFuse build directory created by script: ${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}"
    rm -rf "${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}"
  fi
}

# run_package_parallel: Executes test packages in parallel.
#   The function returns a non-zero exit status if any of the packages fail all attempts.
#
# Usage: run_package_parallel "parallelism" "bucket_type" "max_retries" "package1" "package2" ...
#   First argument is extent of parallelism for this command.
#   Second argument is the bucket type ("flat", "hns", "zonal").
#   Third argument is the maximum number of retries for failed commands.
#   Rest of the arguments are package names to run.
#
# Example:
#   run_package_parallel 2 "flat" 2 "managed_folders" "operations" "read_large_files"
# This command will run at max 2 packages in parallel, with up to 2 retries on failure.
run_package_parallel() {
  if [[ $# -lt 3 ]]; then
    log_error_locked "run_package_parallel() called with incorrect number of arguments."
    return 1
  fi
  local parallelism="$1" bucket_type="$2" flake_attempts="$3"
  shift 3

  local -a package_list=("$@")
  local -A package_status=()
  local -A package_attempt=()

  for pkg in "${package_list[@]}"; do
    package_status["$pkg"]=1
    package_attempt["$pkg"]=1
  done

  local -A package_name_by_pid=()

  while :; do
    # Launch packages up to parallelism limit
    for pkg in "${package_list[@]}"; do
      # Skip if we hit parallelism limit
      [[ ${#package_name_by_pid[@]} -ge $parallelism ]] && continue
      
      # Skip if package already succeeded
      [[ "${package_status["$pkg"]}" -eq 0 ]] && continue
      
      # Skip if max retries exceeded
      [[ "${package_attempt["$pkg"]}" -gt "$flake_attempts" ]] && continue
      
      # Skip if already running
      [[ " ${package_name_by_pid[@]} " =~ " $pkg " ]] && continue
      
      create_bucket_and_run_package "${bucket_type}" "$pkg" "${package_attempt["$pkg"]}" &
      local pid=$!
      package_name_by_pid["$pid"]="$pkg"
    done

    # Break if no commands are running
    [[ ${#package_name_by_pid[@]} -eq 0 ]] && break

    # Wait for any background process to finish
    local waited_pid
    wait -n -p waited_pid
    local exit_status=$?
    
    local pkg="${package_name_by_pid[$waited_pid]}"
    unset "package_name_by_pid[$waited_pid]"
    
    package_status["$pkg"]=$exit_status

    if [[ "$exit_status" -ne 0 ]]; then
      package_attempt["$pkg"]=$((package_attempt[$pkg] + 1))
    fi
  done

  # Return non-zero if any package failed all attempts
  for s in "${package_status[@]}"; do
    if [[ "$s" -ne 0 ]]; then
      return 1
    fi
  done
  
  return 0
}

# Helper method that creates a bucket and then runs the test package.
create_bucket_and_run_package() {
  if [[ $# -ne 3 ]]; then
    log_error_locked "create_bucket_and_run_package() called with incorrect number of arguments."
    return 1
  fi
  local bucket_type="$1"
  local package_name="$2"
  local attempt_number="$3"

  local bucket_name="gcsfuse-test-hns-pirlo-${package_name}"
  log_info_locked "Using HNS Pirlo bucket: gs://${bucket_name} for package ${package_name}"

  test_package "$package_name" "$bucket_name" "$bucket_type" "$attempt_number"
}

# Helper method to execute an E2E test package.
test_package() {
  if [[ $# -ne 4 ]]; then
    log_error_locked "test_package() called with incorrect number of arguments."
    return 1
  fi
  local package_name="$1"
  local bucket_name="$2"
  local bucket_type="$3"
  local attempt_number="$4"

  local config_file_path
  config_file_path=$(realpath "${INTEGRATION_TEST_PACKAGE_DIR}/test_config.yaml")

  # Build go package test command.
  local go_test_cmd_parts=(
    "BUCKET_NAME=${bucket_name}"
    "GODEBUG=asyncpreemptoff=1"
    "go" "test" "-v"
    "-timeout=${INTEGRATION_TEST_PACKAGE_TIMEOUT_IN_MINS}m"
    "${INTEGRATION_TEST_PACKAGE_DIR}/${package_name}"
  )
  if [[ "$package_name" == "benchmarking" ]]; then
    go_test_cmd_parts+=("-bench=." "-benchtime=100x")
  fi
  if ${SKIP_NON_ESSENTIAL_TESTS_ON_PACKAGE}; then
    go_test_cmd_parts+=("-short")
  fi
  # Test Binary flags after this.
  go_test_cmd_parts+=("-args" "--integrationTest")
  go_test_cmd_parts+=("--config-file=${config_file_path}")

  if ${TEST_INSTALLED_PACKAGE}; then
    go_test_cmd_parts+=("--testInstalledPackage")
  fi
  if ${RUN_TESTS_WITH_PRESUBMIT_FLAG}; then
    go_test_cmd_parts+=("--presubmit")
  fi
  go_test_cmd_parts+=("--pirlo")
  if [[ -n "$BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR" ]]; then 
    go_test_cmd_parts+=("--gcsfuse_prebuilt_dir=${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}")
  fi

  local go_test_cmd test_package_log_file start=$SECONDS exit_code=0 
  # Use printf %q to quote each argument safely for eval
  # This ensures spaces and special characters within arguments are handled correctly.
  go_test_cmd=$(printf "%q " "${go_test_cmd_parts[@]}")
  test_package_log_file=$(create_file_helper "running_package_logs/${bucket_type}/${package_name}_attempt_${attempt_number}.txt")
  # Run the package test command and capture log output with runtime stats.
  log_info_locked "Started running test package [$package_name] for bucket type [$bucket_type] with bucket name [$bucket_name] (Attempt: $attempt_number)"

  if ! eval "$go_test_cmd" > "$test_package_log_file" 2>&1; then
    exit_code=1
    if [[ "$attempt_number" -lt "$FLAKE_ATTEMPTS" ]]; then
      log_info_locked "Failed test package [$package_name] for bucket type [$bucket_type] (Attempt: $attempt_number). Will retry."
    else
      log_info_locked "Failed test package [$package_name] for bucket type [$bucket_type] (Attempt: $attempt_number). No more retries."
    fi
  else
    log_info_locked "Passed test package [$package_name] for bucket type [$bucket_type] (Attempt: $attempt_number)"
  fi

  local end=$SECONDS

  # Add the package stats to the file.
  echo "${package_name} ${bucket_type} ${exit_code} ${start} ${end}" >> "$PACKAGE_RUNTIME_STATS"
  # Generate Kokoro artifacts(log) files only on terminal attempt.
  if [[ "$exit_code" -eq 0 || "$attempt_number" -ge "$FLAKE_ATTEMPTS" ]]; then
    generate_test_log_artifacts "$test_package_log_file" "$package_name" "$bucket_type"
  fi
  # Call the helper to organize logs and cleanup the original file
  organize_test_logfile "$exit_code" "$test_package_log_file" "${package_name}_attempt_${attempt_number}" "$bucket_type"
  return "$exit_code"
}

# Helper method to generate Kokoro artifacts(log) files when building in Kokoro environment.
generate_test_log_artifacts() {
  # If KOKORO_ARTIFACTS_DIR is not set, skip artifact generation.
  if ! $KOKORO_DIR_AVAILABLE; then
    return 0
  fi

  if [[ $# -ne 3 ]]; then
    log_error_locked "generate_test_log_artifacts() called with incorrect number of arguments."
    return 1
  fi

  local log_file="$1"
  local package_name="$2"
  local bucket_type="$3"

  if [ ! -f "$log_file" ]; then
    return 0
  fi

  local output_dir="${KOKORO_ARTIFACTS_DIR}/${bucket_type}/${package_name}"
  mkdir -p "$output_dir"
  local sponge_log_file="${output_dir}/sponge_log.log"
  local sponge_xml_file="${output_dir}/sponge_log.xml"

  cp "$log_file" "$sponge_log_file"
  
  echo '<?xml version="1.0" encoding="UTF-8"?>' > "${sponge_xml_file}"
  echo '<testsuites>' >> "${sponge_xml_file}"

  # Remove first 2 lines and last line from log.
  local report_log=$(cat "$log_file")
  # For benchmarking package, filter out benchmark results to avoid incorrect XML results.
  if [[ "$package_name" == "benchmarking" ]]; then
    report_log=$(echo "$report_log" | grep -v '^Benchmark_[^[:space:]]*$')
  fi

  echo "$report_log" | go-junit-report | sed '1,2d;$d' >> "${sponge_xml_file}"
  echo '</testsuites>' >> "${sponge_xml_file}"
  
  return 0
}

install_package_from_path() {
  if [[ $# -ne 1 ]]; then
    log_error_locked "install_package_from_path() called with incorrect number of arguments."
    return 1
  fi
  local package_path="$1"
  log_info "Downloading $(basename "${package_path}")..."
  gcloud storage cp "${package_path}" /tmp/ --quiet || return 1
  if [ -f /etc/os-release ]; then
    # We source in a subshell to prevent variable pollution, 
    # then capture only the ID and ID_LIKE fields.
    DISTRO_DATA=$( (source /etc/os-release; echo "${ID:-} ${ID_LIKE:-}") )
    # Check for debian or ubuntu in the ID or the ID_LIKE chain
    if [[ "$DISTRO_DATA" == *"debian"* ]] || [[ "$DISTRO_DATA" == *"ubuntu"* ]]; then
      sudo dpkg -i "/tmp/$(basename "${package_path}")"
    elif [[ "$DISTRO_DATA" == *"rhel"* ]] || [[ "$DISTRO_DATA" == *"centos"* ]]; then
      sudo yum -y localinstall "/tmp/$(basename "${package_path}")"
    else
        log_error "This script only supports Debian/Ubuntu/rhel/centos based distributions."
        log_info "Your distribution is:"
        cat /etc/os-release
        exit 1
    fi
  else
    log_error "/etc/os-release not found. Unable to determine distribution"
    exit 1
  fi
}

build_gcsfuse_once() {
  local build_output_dir # For the final gcsfuse binaries
  build_output_dir=$(mktemp -d -t gcsfuse_e2e_run_build_XXXXXX)
  log_info "GCSFuse binaries will be built in ${build_output_dir}/"

  local gcsfuse_src_dir
  # Determine GCSFuse source directory
  # We are already at the repository root due to the cd in main()
  gcsfuse_src_dir="$(pwd)"

  if [[ ! -f "${gcsfuse_src_dir}/go.mod" ]]; then
    log_error "Could not reliably determine GCSFuse project root. Expected go.mod at ${gcsfuse_src_dir}" >&2
    rm -rf "${build_output_dir}"
    exit 1
  fi
  log_info "Using GCSFuse source directory: ${gcsfuse_src_dir}"

  log_info "Building GCSFuse using 'go run ./tools/build_gcsfuse/main.go'..."
  # Ensure dependencies are tidy and vendored to avoid "inconsistent vendoring" errors
  (cd "${gcsfuse_src_dir}" && go mod tidy && go mod vendor && go run ./tools/build_gcsfuse/main.go . "${build_output_dir}" "0.0.0")
  if [ $? -ne 0 ]; then
    log_error "Building GCSFuse binaries using 'go run ./tools/build_gcsfuse/main.go' failed."
    rm -rf "${build_output_dir}" # Clean up created temp dir
    return 1
  fi

  # Set the directory path for use by the script (to form the go test flag)
  BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR="${build_output_dir}"
  log_info "GCSFuse binaries built by script in: ${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}"
  log_info "GCSFuse executable: ${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}/bin/gcsfuse"
  return 0
}

install_packages() {
  local arch
  
  # We are already at the repository root due to the cd in main()
  local REPO_ROOT="$(pwd)"

  # Identify the OS and Architecture
  if [ -f /etc/os-release ]; then
    # We source in a subshell to prevent variable pollution, 
    # then capture only the ID and ID_LIKE fields.
    DISTRO_DATA=$( (source /etc/os-release; echo "${ID:-} ${ID_LIKE:-}") )
    
    # Check for debian or ubuntu in the ID or the ID_LIKE chain
    if [[ "$DISTRO_DATA" == *"debian"* ]] || [[ "$DISTRO_DATA" == *"ubuntu"* ]]; then
      arch=$(dpkg --print-architecture)
      log_info "Detected Debian/Ubuntu-based OS. Architecture: $arch"
      
      local os_id="debian"
      [[ "$DISTRO_DATA" == *"ubuntu"* ]] && os_id="ubuntu"
      
      # Fix broken Docker apt repositories to match current OS
      sudo sed -i "s|download.docker.com/linux/[a-z]*|download.docker.com/linux/$os_id|g" /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null || true
      
      # Prevent interactive prompts during package installation
      export DEBIAN_FRONTEND=noninteractive
      echo 'Dpkg::Options { "--force-confdef"; "--force-confold"; };' | sudo tee /etc/apt/apt.conf.d/90force-confold > /dev/null
      
      sudo apt-get update -y
      sudo apt-get install -y python3 gcc python3-dev python3-setuptools python3-crcmod fuse3 wget tar
      
    elif [[ "$DISTRO_DATA" == *"rhel"* ]] || [[ "$DISTRO_DATA" == *"centos"* ]]; then
      arch=$(uname -m)
      if [[ "$arch" == "x86_64" ]]; then arch="amd64"; elif [[ "$arch" == "aarch64" ]]; then arch="arm64"; fi
      log_info "Detected RHEL/CentOS-based OS. Architecture: $arch"
      
      sudo yum makecache
      sudo yum -y update
      sudo yum -y install python3 gcc python3-devel python3-setuptools fuse3 wget tar
    else
        log_error "This script only supports Debian/Ubuntu/rhel/centos based distributions."
        log_info "Your distribution is:"
        cat /etc/os-release
        exit 1
    fi
  else
    log_error "/etc/os-release not found. Unable to determine distribution."
    exit 1
  fi

  log_info "Installing Go version ${GO_VERSION} for linux-${arch}..."
  wget -qO /tmp/go_tar.tar.gz "https://go.dev/dl/go${GO_VERSION}.linux-${arch}.tar.gz"
  sudo rm -rf /usr/local/go
  sudo tar -C /usr/local -xzf /tmp/go_tar.tar.gz
  rm -f /tmp/go_tar.tar.gz
  export PATH="/usr/local/go/bin:$PATH"
  
  # Install latest gcloud version.
  log_info "Installing the latest Google Cloud SDK..."
  wget -qO /tmp/gcloud.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
  sudo tar -C /usr/local -xzf /tmp/gcloud.tar.gz
  rm -f /tmp/gcloud.tar.gz
  sudo /usr/local/google-cloud-sdk/install.sh --quiet
  
  export PATH="/usr/local/google-cloud-sdk/bin:$PATH"
  export CLOUDSDK_PYTHON="$(which python3)"
  if ${KOKORO_DIR_AVAILABLE} ; then
    # Install go-junit-report to generate XML test reports from go logs.
    go install github.com/jstemmer/go-junit-report/v2@latest
    export PATH="$(go env GOPATH)/bin:$PATH"
  fi
}

# Generic function to run a group of E2E tests for a given bucket type.
# Args:
#   $1: Descriptive group name (e.g., "REGIONAL", "ZONAL", "TPC")
#   $2: Bucket type ("flat", "hns", "zonal")
#   $@: A list of test package names to run.
run_test_group() {
  local group_name="$1"
  local bucket_type="$2"
  shift 2
  local -a test_packages=("$@")
  local group_exit_code=0
  log_info_locked "Started running e2e tests for ${group_name} group (bucket type: ${bucket_type})."

  run_package_parallel "$PACKAGE_LEVEL_PARALLELISM" "$bucket_type" "$FLAKE_ATTEMPTS" "${test_packages[@]}"
  group_exit_code=$?

  if [ "$group_exit_code" -ne 0 ]; then
    log_error_locked "The e2e tests for ${group_name} group (bucket type: ${bucket_type}) FAILED."
    return 1
  fi
  log_info_locked "The e2e tests for ${group_name} group (bucket type: ${bucket_type}) successful."
  return 0
}

main() {
  # Change directory to the root of the repository so go tests and relative paths work correctly
  local script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
  cd "${script_dir}/../.." || exit 1

  # Clean up everything on exit.
  trap clean_up EXIT
  log_info ""
  log_info "------ Upgrading gcloud and installing packages ------"
  log_info ""
  set -e
  install_packages
  set +e
  log_info "------ Upgrading gcloud and installing packages took $SECONDS seconds ------"

  log_info ""
  log_info "------ Started running E2E test packages ------"
  log_info ""

   # Decide whether to install a package from a path or build GCSFuse based on RUN_E2E_TESTS_ON_PACKAGE
  if [[ -n "$INSTALL_PACKAGE_FROM_PATH" ]]; then
    log_info "Installing package from the path '${INSTALL_PACKAGE_FROM_PATH}'"
    if ! install_package_from_path "$INSTALL_PACKAGE_FROM_PATH"; then 
      log_error "Unable to install the package from path '${INSTALL_PACKAGE_FROM_PATH}'. Exiting."
      exit 1
    fi
    # Setting test installed package to true
    TEST_INSTALLED_PACKAGE=true
  elif (! ${TEST_INSTALLED_PACKAGE} ) && ${BUILD_BINARY_IN_SCRIPT}; then
    log_info "TEST_INSTALLED_PACKAGE is not 'true' (value: '${TEST_INSTALLED_PACKAGE}') and BUILD_BINARY_IN_SCRIPT is 'true'."
    log_info "Building GCSFuse inside script..."
    if ! build_gcsfuse_once; then
        log_error "build_gcsfuse_once failed. Exiting."
        # The trap will handle cleanup
        exit 1
    fi
    log_info "Script built GCSFuse at: ${BUILT_BY_SCRIPT_GCSFUSE_BUILD_DIR}"
  fi

  # Reset SECONDS to 0
  SECONDS=0

  if ${TRACK_RESOURCE_USAGE}; then
    # Start collecting system resource usage in background.
    log_info "Starting resource usage collection process."
    ./tools/integration_tests/resource_usage.sh "COLLECT" "$RESOURCE_USAGE_FILE" &
    RESOURCE_USAGE_PID=$!
    log_info "Resource usage collection process started at PID: $RESOURCE_USAGE_PID"
  fi

  local pids=()
  local overall_exit_code=0
  run_test_group "PIRLO" "hns_pirlo" "${TEST_PACKAGES[@]}" & pids+=($!)
  # Wait for all background processes to complete and aggregate their exit codes
  for pid in "${pids[@]}"; do
    wait "$pid"
    overall_exit_code=$((overall_exit_code || $?))
  done
  elapsed_min=$(((SECONDS + 60) / 60))
  log_info "------ E2E test packages complete run took ${elapsed_min} minutes ------"
  log_info ""

  # Print package runtime stats table.
  ./tools/integration_tests/create_package_runtime_table.sh "$PACKAGE_RUNTIME_STATS"

  if ${TRACK_RESOURCE_USAGE}; then
    # Kill resource usage background PID and print resource usage.
    log_info "Stopping resource usage collection process: $RESOURCE_USAGE_PID"
    if safe_kill "$RESOURCE_USAGE_PID" "resource_usage.sh"; then
      log_info "Resource usage collection process stopped."
      ./tools/integration_tests/resource_usage.sh "PRINT" "$RESOURCE_USAGE_FILE"
    else
      log_error "Failed to stop resource usage collection process (or it's already stopped)"
    fi
  fi
  exit $overall_exit_code
}

#Main method to run script
main
