#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit on error, treat unset variables as errors, and propagate pipeline errors.
set -euo pipefail

# This script is used to collect the resource(mem,cpu,disk) usage of the machine in the file at given interval.
# This script can also be in use to print the resource usage visualisation in graph format.
usage() {
    echo "A script to collect and visualize system resource usage."
    echo ""
    echo "========================================================================"
    echo ""
    echo "COMMAND: COLLECT"
    echo ""
    echo "  Gathers resource usage (CPU, memory, disk) at predefined intervals."
    echo ""
    echo "  USAGE:"
    echo "    $0 COLLECT <FILE_PATH>"
    echo ""
    echo "  ARGUMENTS:"
    echo ""
    echo "    <FILE_PATH>   The path to the output file where resource data will be"
    echo "                  saved. The script will create or overwrite this file."
    echo ""
    echo "========================================================================"
    echo ""
    echo "COMMAND: PRINT"
    echo ""
    echo "  Visualizes resource data from a file in a graph format."
    echo ""
    echo "  USAGE:"
    echo "    $0 PRINT <FILE_PATH>"
    echo ""
    echo "  ARGUMENTS:"
    echo "    <FILE_PATH>   The path to the input data file (generated by COLLECT)"
    echo "                  that contains the statistics to be visualized."
    echo ""
    echo "========================================================================"
    exit 1
}

readonly USAGE_COLLECTION_INTERVAL_SECONDS=10      # Collect usage every 10s.
readonly USAGE_COLLECTION_DURATION_SECONDS=$((3 * 60 * 60)) # Auto collect usage for upto 3 hrs only (VM timeout is 3 hrs in kokoro).
readonly COLLECT="COLLECT"
readonly PRINT="PRINT"

# Validate number of arguments.
if [[ $# -ne 2 ]]; then
    echo "Error: Invalid number of arguments."
    usage
fi

readonly COMMAND="$1"
readonly FILE_PATH="$2"

# Calculates CPU usage and returns the ceiling value (smallest integer greater than or equal to the usage).
get_cpu_usage() {
    # First reading
    read -r _ user nice system idle iowait irq softirq steal guest guest_nice </proc/stat

    # Default guest values to 0 for older kernels
    guest=${guest:-0}
    guest_nice=${guest_nice:-0}

    local prev_total=$((user + nice + system + idle + iowait + irq + softirq + steal + guest + guest_nice))
    local prev_idle=$((idle + iowait))

    # Wait for a second
    sleep 1

    # Second reading
    read -r _ user nice system idle iowait irq softirq steal guest guest_nice </proc/stat
    guest=${guest:-0}
    guest_nice=${guest_nice:-0}

    local current_total=$((user + nice + system + idle + iowait + irq + softirq + steal + guest + guest_nice))
    local current_idle=$((idle + iowait))

    # Calculate the differences in total and idle time
    local total_diff=$((current_total - prev_total))
    local idle_diff=$((current_idle - prev_idle))

    # Avoid division by zero
    if [ "$total_diff" -eq 0 ]; then
        echo "0"
        return
    fi

    # Calculate the numerator and denominator for the usage percentage
    local busy_diff=$((total_diff - idle_diff))

    # Calculate ceiling of (100 * busy_diff / total_diff) using integer arithmetic
    local cpu_usage=$(((100 * busy_diff + total_diff - 1) / total_diff))

    echo "$cpu_usage"
}

# Calculates memory usage as a ceiling integer percentage without forking.
# Reads /proc/meminfo directly using only Bash built-ins.
get_mem_usage() {
    # Declare local variables to avoid affecting the global scope.
    local line mem_total=0 mem_available=0

    # Read /proc/meminfo line by line. Input redirection `<` is a shell
    # feature and does not fork a new process.
    while read -r line; do
        # Use a case statement for efficient pattern matching.
        case "$line" in
        MemTotal:*)
            # Use parameter expansion to strip non-numeric characters.
            mem_total=${line//[^0-9]/}
            ;;
        MemAvailable:*)
            mem_available=${line//[^0-9]/}
            ;;
        esac

        # For efficiency, break the loop once we have both values.
        if [[ "$mem_total" -gt 0 && "$mem_available" -gt 0 ]]; then
            break
        fi
    done </proc/meminfo

    # Safety check to prevent division by zero if values weren't read.
    if [[ "$mem_total" -eq 0 ]]; then
        echo "0"
        return 1
    fi

    # Calculate used memory.
    local mem_used=$((mem_total - mem_available))

    # Calculate the ceiling of the percentage using pure integer arithmetic.
    # The formula for ceiling(a / b) is (a + b - 1) / b.
    # Here, a = mem_used * 100 and b = mem_total.
    local usage_percent=$(((mem_used * 100 + mem_total - 1) / mem_total))

    echo "$usage_percent"
}

# Helper function to get Disk Usage for / (root)
# Outputs: Disk Usage percentage, or 0 on failure.
get_disk_usage() {
    local disk_usage
    disk_usage=$(df -P / | awk 'END{printf "%.0f", $5}')
    echo "${disk_usage:-0}"
}

# Helper function to collect the usage and write to file.
# Output: Appends new line to file with %cpu %mem %disk at given interval.
collect_all_metric() {
    echo "CPU MEM DISK" >"$FILE_PATH"
    while true; do
        if [ "$SECONDS" -ge "$USAGE_COLLECTION_DURATION_SECONDS" ]; then
            echo "Exiting due to monitoring time limit."
            exit 0
        fi
        cpu=$(get_cpu_usage)
        mem=$(get_mem_usage)
        disk=$(get_disk_usage)
        echo "${cpu} ${mem} ${disk}" >>"$FILE_PATH"
        sleep "$USAGE_COLLECTION_INTERVAL_SECONDS"
    done
}

# Helper function to print usage of all metrics.
print_each_metric() {
    declare -A resource_usage_map
    read -r -a headers <"$FILE_PATH"
    for header in "${headers[@]}"; do
        resource_usage_map["$header"]=""
    done

    while IFS= read -r line; do
        read -r -a values <<<"$line"
        for i in "${!headers[@]}"; do
            header=${headers[$i]}
            value=${values[$i]}
            resource_usage_map["$header"]+="$value "
        done
    done < <(tail -n +2 "$FILE_PATH")

    for resource in "${!resource_usage_map[@]}"; do
        usage=(${resource_usage_map["$resource"]})
        echo ""
        echo "$resource usage in percentage every $USAGE_COLLECTION_INTERVAL_SECONDS seconds:"
        echo ""

        max_value=$(printf "%s\n" "${usage[@]}" | sort -n | tail -n 1)
        max_value=$(((max_value + 5 > 100) ? 100 : max_value + 5)) # Add some buffer upwards from max usage.
        # Make graph for each value
        for ((i = max_value; i >= 0; i--)); do
            printf "%s@ %3d%%|" "$resource" "$i"
            for val in "${usage[@]}"; do
                if [[ $val -ge $i ]]; then
                    echo -n "*"
                else
                    echo -n " "
                fi
            done
            echo ""
        done
        SEPARATOR_LINE=$(printf '=%.0s' $(seq 1 $((${#usage[@]} + 15)))) # data points + 15 more for to cover label and %.
        echo "$SEPARATOR_LINE"
    done
}

# Exit the script if SIGTERM or SIGINT is received.
trap 'exit 0' SIGINT SIGTERM

if [[ "$COMMAND" == "$COLLECT" ]]; then
    collect_all_metric
elif [[ "$COMMAND" == "$PRINT" ]]; then
    print_each_metric
else
    echo "Error: Invalid command."
    usage
fi
