# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

explicit_dir:
  - mounted_directory: "${MOUNTED_DIR}" # To be passed by GKE after mounting
    test_bucket: "${BUCKET_NAME}" # To be passed by both gcsfuse and gke tests
    log_file: # Optional flag required by some tests where log parsing is done to validate end behavior
    flags:
      - "--implicit-dirs=false"
      - "--implicit-dirs=false --client-protocol=grpc"
    compatible: # Bucket type to run these tests with
      - flat: true
      - hns: false
      - zonal: false
    run_on_gke: false

operations:
  - mounted_directory: "${MOUNTED_DIR}" # To be passed by GKE after mounting
    test_bucket: "${BUCKET_NAME}" # To be passed by both gcsfuse and gke tests
    log_file: # Optional flag required by some tests where log parsing is done to validate end behavior
    flags:
      - "--enable-atomic-rename-object=true"
      - "--experimental-enable-json-read=true"
      - "--client-protocol=grpc --implicit-dirs=true --enable-atomic-rename-object=true"
      - "--experimental-enable-json-read=true --enable-atomic-rename-object=true"
      - "--create-empty-file=true --enable-atomic-rename-object=true"
      - "--metadata-cache-ttl-secs=0 --enable-streaming-writes=false"
      - "--kernel-list-cache-ttl-secs=-1 --implicit-dirs=true"
      # - "--file-cache-max-size-mb=2 --cache-dir=${TMPDIR}/cache-dir-operations-hns"
    compatible: # Bucket type to run these tests with
      - flat: true
      - hns: true
      - zonal: true
    run_on_gke: false
