apiVersion: v1
kind: PersistentVolume
metadata:
  name: serving-bucket-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 64Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gcsfuse-sc # dummy storage class
  claimRef:
    namespace: <customer-namespace>
    name: serving-bucket-pvc
  mountOptions:
  - implicit-dirs #set because most prefer ease of use
  - metadata-cache:negative-ttl-secs:0 # disable negative cache
  - metadata-cache:ttl-secs:-1 #no expiry
  - metadata-cache:stat-cache-max-size-mb:-1 #unlimited
  - metadata-cache:type-cache-max-size-mb:-1 #unlimited
  - file-cache:max-size-mb:-1 #unlimited
  - file-cache:cache-file-for-range-read:true
  - file-cache:enable-parallel-downloads:true
  - read_ahead_kb=1024
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: <serving-bucket> # unique bucket name
    volumeAttributes:
      skipCSIBucketAccessCheck: "true"
      gcsfuseMetadataPrefetchOnMount: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serving-bucket-pvc
  namespace: <customer-namespace>
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  volumeName: serving-bucket-pv
  storageClassName: gcsfuse-sc # dummy storage class
