apiVersion: v1
kind: Pod
metadata:
  name: gcs-fuse-csi-example-pod
  namespace: <customer-namespace>
  annotations:
    gke-gcsfuse/volumes: "true"

spec:
  containers:
    # Your workload container spec
    ...
    volumeMounts:
    - name: serving-bucket-vol
      mountPath: /serving-data
  serviceAccountName: <YOUR_K8S_SA>
  volumes:
  # RAM disk file cache for best performance of Parallel Download. Can use L-SSD if not available memory
  - name: gke-gcsfuse-cache # gcsfuse file cache backed by RAM Disk
    emptyDir:
      medium: Memory
  - name: serving-bucket-vol
    persistentVolumeClaim:
      claimName: serving-bucket-pvc
