apiVersion: v1
kind: PersistentVolume
metadata:
  name: training-bucket-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 64Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gcsfuse-sc # dummy storage class
  claimRef:
    namespace: <customer-namespace>
    name: training-bucket-pvc
  mountOptions:
  - implicit-dirs #set because most prefer ease of use
  - metadata-cache:negative-ttl-secs:0 #disabled
  - metadata-cache:ttl-secs:-1 #unlimited
  - metadata-cache:stat-cache-max-size-mb:-1 #unlimited
  - metadata-cache:type-cache-max-size-mb:-1 #unlimited
  # if enabling the file cache, uncomment out to use #
  #    - file-cache:max-size-mb:-1 # only for GPUs
  #    - file-cache:cache-file-for-range-read:true
  #    - read_ahead_kb=1024
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: <training-bucket> # unique bucket name
    volumeAttributes:
      skipCSIBucketAccessCheck: "true"
      gcsfuseMetadataPrefetchOnMount: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-bucket-pvc
  namespace: <customer-namespace>
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  volumeName: training-bucket-pv
  storageClassName: gcsfuse-sc # dummy storage class
