name: Code Coverage
on: [push, pull_request]
jobs:
  codecov:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
          cache: false

      - name: Download dependencies
        run: go mod download

      - name: Coverage for all except cache tests parallely.
        run: CGO_ENABLED=0 go test -count 1 -v -covermode=atomic -coverprofile=coverage.out `go list ./... | grep -v internal/cache/...`

      - name: Coverage  for cache tests
        run: CGO_ENABLED=0 go test -p 1 -count 1 -v -covermode=atomic -coverprofile=coverage_cache.out ./internal/cache/...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.3.1
        timeout-minutes: 5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests

