name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  img_name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker buildx create --use
      - run: docker buildx build -t ${{ env.img_name }} --platform=linux/amd64,linux/arm64 --push .
