name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write

    steps:
    - name: Check PR title format
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "PR Title: $PR_TITLE"
        
        # Updated regex pattern:
        # Allows any non-empty string inside the first set of brackets.
        # Example: [ANY_TEXT_HERE], [Bug Fix], [Feature]
        if [[ "$PR_TITLE" =~ ^\[[^\]]+\](.+)$ ]]; then
          echo "PR title '$PR_TITLE' adheres to the required format."
          exit 0
        else
          echo "Error: PR title '$PR_TITLE' does not follow the required format."
          echo "Please ensure the title starts with a category enclosed in square brackets. e.g., [Category] Your concise title."
          echo "Examples:"
          echo "  [Auth] Implement password reset feature"
          echo "  [Bug Fix] Fix infinite loop in user login"
          echo "  [Feature] Add dark mode toggle"
          exit 1
        fi
      shell: bash
